### ISSUE TITLE
Wasmtime panic for processors without SIMD support

### ISSUE THREAD

**Issue by superlou** [lapce/lapce#1041]
When starting Lapce (built from master) with plugins installed (in the following, only lapce-rust is installed), the console shows a panic related to wasmtime's use of SIMD:

```
lsimons@bestever:~/workspace/lapce-python$ RUST_BACKTRACE=1 lapce .
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported feature: SIMD support requires SSE3, SSSE3, SSE4.1, and SSE4.2 on x86_64.', /home/lsimons/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-0.39.1/src/engine.rs:524:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: <wasmtime::engine::Engine as core::default::Default>::default
   4: lapce_proxy::plugin::wasi::start_volt
```

I think the last comments at https://github.com/bytecodealliance/wasmtime/issues/3809 are indicating wasmtime are suggesting that this SIMD support is simply a required baseline for using wasmtime, so I'm out of luck. Is there a way to work around that?

**Comment by TudbuT** [comment]
Issue also happens on my ThinkPad T400, which while it is not recent, I would expect to be supported by something like wasmtime. The CPU is an Intel Core 2 Duo from 2008, so about 15 years old now.

**Comment by hbina** [comment]
Is there a way to check for SIMD support at runtime?

**Comment by Reokodoku** [comment]
I searched and I found this macro [std::is_x86_feature_detected](https://doc.rust-lang.org/std/macro.is_x86_feature_detected.html). <br>Theoretically, from this macro you have to see if your processor supports see3, ssse3, sse4.1 and sse4.2.
