### ISSUE TITLE
Crash: thread panic on double-click  with Alt key pressed

### ISSUE THREAD

**Issue by gsurrel** [lapce/lapce#1048]
I could get a mostly reproducible crash doing the following:

1. Open Lapce, and any file in the editor
2. Keeping (left) Alt key pressed, double-click here and there in the text. You will be adding editing cursors
3. At some point, Lapce will crash

<details>
<summary>Here is a stacktrace I captured</summary>

```
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 8', lapce-core/src/selection.rs:331:9
stack backtrace:
   0:     0x55db33583ba1 - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55db33583ba1 - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55db33583ba1 - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55db33583ba1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55db3290d12c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55db33559d64 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55db33585ab6 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55db33585ab6 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55db33585ab6 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55db33586b47 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x55db33586b47 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x55db33586622 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x55db33586596 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55db33586552 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x55db327b0572 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x55db327b05f1 - core::panicking::panic_bounds_check::hfef1f84c4a547e72
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:84:5
  16:     0x55db32e0d178 - lapce_data::editor::LapceEditorBufferData::get_code_actions::h47962b19ba2eb631
  17:     0x55db33142966 - <lapce_ui::editor::LapceEditor as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::event::he776c4c3bcbead6c
  18:     0x55db3313faea - <lapce_ui::scroll::LapceIdentityWrapper<W> as druid::widget::widget::Widget<T>>::event::haebf72bb4ea231df
  19:     0x55db3313c83f - <lapce_ui::editor::container::LapceEditorContainer as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::event::h1742ee81ad010a04
  20:     0x55db33137df7 - <lapce_ui::editor::view::LapceEditorView as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::event::h7adf468a3f21d3af
  21:     0x55db330a3cc5 - druid::core::WidgetPod<T,W>::event::h2b4aef2b18d4b8d8
  22:     0x55db3318c6c8 - <lapce_ui::editor::tab::LapceEditorTab as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::event::h8cb52472be10571e
  23:     0x55db330a3cc5 - druid::core::WidgetPod<T,W>::event::h2b4aef2b18d4b8d8
  24:     0x55db3316cbe8 - <lapce_ui::split::LapceSplit as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::event::h4f3636f4fc47c333
  25:     0x55db330a3cc5 - druid::core::WidgetPod<T,W>::event::h2b4aef2b18d4b8d8
  26:     0x55db3307e9db - <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::event::h6b777071dbd2f0cc
  27:     0x55db3327658d - druid::core::WidgetPod<T,W>::event::h3252fefa67c599c2
  28:     0x55db3327139a - <lapce_ui::window::LapceWindow as druid::widget::widget::Widget<lapce_data::data::LapceWindowData>>::event::hfdacac9d2b1573b7
  29:     0x55db33263e24 - <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::event::hcc344322657995be
  30:     0x55db33256827 - druid::window::Window<T>::event::hf2148d42b6b0813f
  31:     0x55db332550b9 - druid::win_handler::InnerAppState<T>::do_window_event::h03686767e343b81e
  32:     0x55db332626bb - druid::win_handler::AppState<T>::do_window_event::ha957a2c5479e6f11
  33:     0x55db33261126 - <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::mouse_down::h27009a7ea918883e
  34:     0x55db32ab2e6a - <O as gtk::auto::widget::WidgetExt>::connect_button_press_event::button_press_event_trampoline::hbccded95870896f3
  35:     0x7ffbe42f7b77 - <unknown>
  36:     0x7ffbe474fd2f - g_closure_invoke
  37:     0x7ffbe476bb76 - <unknown>
  38:     0x7ffbe476cf66 - g_signal_emit_valist
  39:     0x7ffbe476d7a3 - g_signal_emit
  40:     0x7ffbe42c0724 - <unknown>
  41:     0x7ffbe4163680 - <unknown>
  42:     0x7ffbe416452a - gtk_main_do_event
  43:     0x7ffbe3e42743 - <unknown>
  44:     0x7ffbe3e79f56 - <unknown>
  45:     0x7ffbe3b1cd1b - g_main_context_dispatch
  46:     0x7ffbe3b716f8 - <unknown>
  47:     0x7ffbe3b1a3c3 - g_main_context_iteration
  48:     0x7ffbe3ce1c85 - g_application_run
  49:     0x55db3323d2b7 - lapce_ui::app::launch::hd15c8707b5c5e2ba
  50:     0x55db3284fb83 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc34edafa94416cdb
  51:     0x55db3284fef6 - main
  52:     0x7ffbe37b0d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  53:     0x7ffbe37b0e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  54:     0x55db3284fa4a - _start
  55:                0x0 - <unknown>
```

</details>

I'm not totally sure what's the condition for the crash to happen, but it's quite easy and fast to trigger on my machine (Ubuntu 22.04 on amd64, Lapce 0.2.0).

**Comment by Mart-Bogdan** [comment]
It reproduces on Lapce 0.2.0 on Windows 10

Don't know how to get stack trace, but I belive it would be similar.

I guess would be nice to have PDB inside windlows build (portable zip) to have stack lines in trace
