### ISSUE TITLE
error: GLSL 3.30 is not supported

### ISSUE THREAD

**Issue by L3P3** [lapce/lapce#1062]
## Lapce Version

Lapce 0.2.0

## System information

Ubuntu jammy amd64, Intel i5 M480

OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 22.0.5
OpenGL shading language version string: 1.20

## Describe the bug

Cannot run the app when using Intel HD. When I switch to the dedicated amd gpu, it works.
What is weird is that the command claims that GLSL 3.30 was available even though the Intel HD uses 1.20, see above.

## Additional information

```
$ RUST_BACKTRACE=full /bin/lapce 
thread 'main' panicked at '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
', /github/home/.cargo/git/checkouts/piet-wgpu-913b036275d2afb6/f863b3e/src/pipeline.rs:89:13
stack backtrace:
   0:     0x55e9dd183ba1 - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e9dd183ba1 - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e9dd183ba1 - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e9dd183ba1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e9dc50d12c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55e9dd159d64 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55e9dd185ab6 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e9dd185ab6 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e9dd185ab6 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55e9dd186b47 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x55e9dd186b47 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x55e9dd186622 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  12:     0x55e9dd186596 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55e9dd186552 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x55e9dc3b0572 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x55e9dced0930 - core::panicking::panic_display::h06547b41252f6337
  16:     0x55e9dced06db - piet_wgpu::pipeline::create_program::ha9242a56ebb85a91
  17:     0x55e9dc6ac396 - <O as gtk::auto::widget::WidgetExt>::connect_realize::realize_trampoline::h208e72816736d083
  18:     0x7f5330032d2f - g_closure_invoke
  19:     0x7f533004eb76 - <unknown>
  20:     0x7f5330050554 - g_signal_emit_valist
  21:     0x7f53300507a3 - g_signal_emit
  22:     0x7f532fb92967 - gtk_widget_realize
  23:     0x55e9dce48c2a - druid::win_handler::AppState<T>::build_native_window::h860832897dbf1d78
  24:     0x55e9dce3c75a - lapce_ui::app::launch::hd15c8707b5c5e2ba
  25:     0x55e9dc44fb83 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc34edafa94416cdb
  26:     0x55e9dc44fef6 - main
  27:     0x7f532f093d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  28:     0x7f532f093e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  29:     0x55e9dc44fa4a - _start
  30:                0x0 - <unknown>
```

**Comment by oltodosel** [comment]
I get the same error on Intel i3 550 with integrated graphics.

**Comment by kydner** [comment]
get same error, on intel i3-380M

**Comment by ghishadow** [comment]
Lapce need minimum OpenGL 3.3 due to dual source blending which is used for subpixel text rendering which was added to the OpenGL 3.3 specification I think, maybe try running `LIBGL_ALWAYS_SOFTWARE=1 lapce` if you are on Linux as mentioned in https://github.com/lapce/lapce/issues/1108

**Comment by L3P3** [comment]
> Lapce need minimum OpenGL 3.3 due to dual source blending which is used for subpixel text rendering which was added to the OpenGL 3.3 specification I think, maybe try running `LIBGL_ALWAYS_SOFTWARE=1 lapce` if you are on Linux as mentioned in #1108

Or at least use that command in case your only gpu is not supported.

**Comment by panekj** [comment]
Closing in favour of #1108
