### ISSUE TITLE
latest Linux release (0.0.10) is just a blank window on Fedora 35

### ISSUE THREAD

**Issue by SingingBush** [lapce/lapce#120]
Downloaded 0.0.10 from https://github.com/lapce/lapce/releases/download/v0.0.10/Lapce-linux.tar.gz on to my workstation.

Fedora 35
AMD Ryzen 5 3600
AMD Radeon RX 570

but when run it's just an empty window:

![image](https://user-images.githubusercontent.com/870567/158775273-3cbe79c4-ac26-43f5-9086-3dfc59d2a649.png)

I ran it from terminal to see if there was an logging on standard out but nothing there.

**Comment by dzhou121** [comment]
Can you please try WGPU_BACKEND=gl ./lapce

**Comment by SingingBush** [comment]
Just to be sure I also built from source and tried both

```
./target/release/lapce
```

```
WGPU_BACKEND=gl ./target/release/lapce
```

the outcome is the same

**Comment by SingingBush** [comment]
just noticed the existence of `~/.config/lapce/lapce.log` in related #98 issue. My log has the following:

```
[2022-03-17][08:59:35][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
[2022-03-17][09:00:27][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
[2022-03-17][09:05:59][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
[2022-03-17][09:18:40][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
[2022-03-17][09:19:23][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
```

**Comment by dzhou121** [comment]
Can you please pull the latest master and try it again. WGPU_BACKEND support wasn't put in.

**Comment by danielburnley** [comment]
```[2022-03-17][10:16:31][piet_wgpu][INFO] AdapterInfo { name: "AMD Radeon RX 580 2048SP (POLARIS10, DRM 3.35.0, 5.4.0-100-generic, LLVM 12.0.0)", vendor: 4098, device: 0, device_type: DiscreteGpu, backend: Gl }```

I had the same issue, tried with the above on the latest master branch and this was the entry in the log, with the full backtrace being

```
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/xx/.asdf/installs/rust/1.59.0/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x5565cc18d4fc - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5565cc18d4fc - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5565cc18d4fc - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5565cc18d4fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5565cc1b979c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5565cc183ae3 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x5565cc190002 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5565cc190002 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5565cc190002 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x5565cc18fbe5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x5565cc190653 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x5565cc190370 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x5565cc18d9a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5565cc1900a9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x5565cab1a311 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x5565cbecad39 - wgpu::backend::direct::Context::handle_error_fatal::hb5dab7df19ac64b0
  16:     0x5565cbecb742 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::hcb9d6156db1333de
  17:     0x5565cbdcd015 - piet_wgpu::WgpuRenderer::set_size::h58a30e56e5d61b06
  18:     0x5565cad547b0 - druid::window::Window<T>::new::h532543f719e82fba
  19:     0x5565cacdfd02 - druid::win_handler::AppState<T>::build_native_window::hdbfe6de93e4e8b7a
  20:     0x5565cab48a95 - druid::app::AppLauncher<T>::launch::h3354e4b3f275814e
  21:     0x5565cab23a61 - lapce_ui::app::lanuch::h39b9800466e0d636
  22:     0x5565cab1ab73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4dad58669905a304
  23:     0x5565cab1aba9 - std::rt::lang_start::{{closure}}::h551fd6a95f18f51e
  24:     0x5565cc18cbb0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  25:     0x5565cc18cbb0 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  26:     0x5565cc18cbb0 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27:     0x5565cc18cbb0 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28:     0x5565cc18cbb0 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  29:     0x5565cc18cbb0 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  30:     0x5565cc18cbb0 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  31:     0x5565cc18cbb0 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  32:     0x5565cc18cbb0 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  33:     0x5565cab1abe2 - main
  34:     0x7f6cdfa170b3 - __libc_start_main
  35:     0x5565cab1aaae - _start
  36:                0x0 - <unknown>
```

**Comment by SingingBush** [comment]
I've pulled the latest changes and recompiled. I can confirm that `WGPU_BACKEND=gl ./target/release/lapce` now works as expected. Note that running the binary with Vulkan is still a problem. It's also worth noting that my system uses Wayland.

**Comment by itspngu** [comment]
I'm also on Fedora 35, also using Wayland (with a `wlroots` based compositor, `sway`), also getting the error-less white window on launch and also get what appears to be a working window (though with blurry text) using `WGPU_BACKEND=gl`.

![image](https://user-images.githubusercontent.com/34752364/159114415-d1614eb3-ea5b-4fa8-b640-fab92d104195.png)

Adding on to this, when moving my cursor (that for some reason switches direction from LTR to RTL in the lapce window) to certain parts of the blank window that contain clickable elements, it turns into a pointer. So it seems the UI or part of it is actually rendered, but everything's blank. Can't screenshot this obviously but maybe @SingingBush can confirm.

Release and debug builds exhibit the same behaviour, not printing anything to TTY when launched, and the log file(s) only contain these 2 lines (corresponding to launches with and without `WGPU_BACKEND=gl`, respectively):

```
[2022-03-19][08:48:23][piet_wgpu][INFO] AdapterInfo { name: "AMD Radeon RX 580 Series (POLARIS10, DRM 3.44.0, 5.16.14-200.fc35.x86_64, LLVM 13.0.0)", vendor: 4098, device: 0, device_type: DiscreteGpu, backend: Gl }
[2022-03-19][08:45:01][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
```

Furthermore, running the `wgpu` examples as suggested in [this comment](https://github.com/lapce/lapce/issues/53#issuecomment-1059847774) works fine.

Lastly, my system info:

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-ia32:cxx-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 35 (Thirty Five)
Release:	35
Codename:	ThirtyFive
```

```
$ uname -a
Linux desk.local 5.16.14-200.fc35.x86_64 #1 SMP PREEMPT Fri Mar 11 20:31:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ neofetch --off
pngu@desk.local
---------------
OS: Fedora release 35 (Thirty Five) x86_64
Host: X570 AORUS PRO -CF
Kernel: 5.16.14-200.fc35.x86_64
Uptime: 17 hours, 43 mins
Packages: 3382 (rpm), 23 (flatpak)
Shell: bash 5.1.8
Resolution: 1920x1080
WM: sway
Theme: Arc-Dark-solid [GTK2/3]
Icons: Material-Originals [GTK2/3]
Terminal: alacritty
Terminal Font: JetBrainsMono NF
CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory: 3536MiB / 32076MiB
```

**Comment by derekdreery** [comment]
I've hit this problem as well. My best guess is that it's an issue with drawing to the right buffer. I'm also using wayland + sway + vulkan backend. See https://wayland-book.com/surfaces/dmabuf.html for how wayland can share resource handles on the GPU without round-tripping through the CPU.

A good next step would be to see if you get the same with the wgpu examples. I will try to do this if I get time.

**Comment by rleh** [comment]
I can confirm the issues on my Fedora 35 system with Wayland, KDE/Plasma and a Radeon RX570 GPU.

Using `WGPU_BACKEND=vulkan` (default if not explicit specified) i get a blank window and no text at all on stdout and this line in `~/.config/lapce/lapce.log`:
```
[2022-03-21][xx:xx:xx][piet_wgpu][INFO] AdapterInfo { name: "AMD RADV POLARIS10", vendor: 4098, device: 26591, device_type: DiscreteGpu, backend: Vulkan }
```

With `WGPU_BACKEND=vulkan` (and `RUST_BACKTRACE=full`) lapce panics and prints the following backtraces:

<details>
<summary>on version 0.0.11</summary>

```
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x55aba1c7a50c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55aba1c7a50c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55aba1c7a50c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55aba1c7a50c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55aba1ca67ac - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x55aba1c70af3 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x55aba1c7d012 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55aba1c7d012 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55aba1c7d012 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x55aba1c7cbf5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x55aba1c7d663 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x55aba1c7d380 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x55aba1c7a9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55aba1c7d0b9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x55aba0607311 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x55aba19b7d49 - wgpu::backend::direct::Context::handle_error_fatal::hb5dab7df19ac64b0
  16:     0x55aba19b8752 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::hcb9d6156db1333de
  17:     0x55aba18ba025 - piet_wgpu::WgpuRenderer::set_size::h58a30e56e5d61b06
  18:     0x55aba08417b0 - druid::window::Window<T>::new::h532543f719e82fba
  19:     0x55aba07ccd02 - druid::win_handler::AppState<T>::build_native_window::hdbfe6de93e4e8b7a
  20:     0x55aba0635a95 - druid::app::AppLauncher<T>::launch::h3354e4b3f275814e
  21:     0x55aba0610a61 - lapce_ui::app::lanuch::h39b9800466e0d636
  22:     0x55aba0607b73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4dad58669905a304
  23:     0x55aba0607ba9 - std::rt::lang_start::{{closure}}::h551fd6a95f18f51e
  24:     0x55aba1c79bc0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  25:     0x55aba1c79bc0 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  26:     0x55aba1c79bc0 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27:     0x55aba1c79bc0 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28:     0x55aba1c79bc0 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  29:     0x55aba1c79bc0 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  30:     0x55aba1c79bc0 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  31:     0x55aba1c79bc0 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  32:     0x55aba1c79bc0 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  33:     0x55aba0607be2 - main
  34:     0x7fc9ed622560 - __libc_start_call_main
  35:     0x7fc9ed62260c - __libc_start_main_alias_1
  36:     0x55aba0607aae - _start
  37:                0x0 - <unknown>
```

</details>

<details>
<summary>compiled from source (22d5785)</summary>

```
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x55d7e84ab8cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h511750d71e2c0726
   1:     0x55d7e84d4e1c - core::fmt::write::h39e3e3387706d5a9
   2:     0x55d7e84a2b55 - std::io::Write::write_fmt::h9b0bef2cd2485422
   3:     0x55d7e84ad580 - std::panicking::default_hook::{{closure}}::h899f08e74964567e
   4:     0x55d7e84ad139 - std::panicking::default_hook::hfd5a26893aac78c1
   5:     0x55d7e84adbb6 - std::panicking::rust_panic_with_hook::h938ccbad74098a37
   6:     0x55d7e84ad910 - std::panicking::begin_panic_handler::{{closure}}::h7c157ac772e64aa2
   7:     0x55d7e84abd64 - std::sys_common::backtrace::__rust_end_short_backtrace::h077b99507b33fcce
   8:     0x55d7e84ad679 - rust_begin_unwind
   9:     0x55d7e6e2bc61 - core::panicking::panic_fmt::hdcdf905b6de1d69c
  10:     0x55d7e81dcfc9 - wgpu::backend::direct::Context::handle_error_fatal::he6c5680cb604c9b6
  11:     0x55d7e81dd8c2 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::he54a51c8645222a0
  12:     0x55d7e80d9235 - piet_wgpu::WgpuRenderer::set_size::h495e7b712bb1bc50
  13:     0x55d7e7045e75 - druid::window::Window<T>::new::h542e40e9af3e9800
  14:     0x55d7e6fdd12c - druid::win_handler::AppState<T>::build_native_window::h8d6b301951fa9e01
  15:     0x55d7e6e60093 - druid::app::AppLauncher<T>::launch::he9511c06faae0d19
  16:     0x55d7e6e463d0 - lapce_ui::app::lanuch::h9bf93d5739831e80
  17:     0x55d7e6e2c533 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha62f389288713819
  18:     0x55d7e6e2c509 - std::rt::lang_start::{{closure}}::h8df0d2108a34adc3
  19:     0x55d7e84ab0ce - std::rt::lang_start_internal::h3f946297745f7d68
  20:     0x55d7e6e2c4f2 - main
  21:     0x7f62435a8560 - __libc_start_call_main
  22:     0x7f62435a860c - __libc_start_main_alias_1
  23:     0x55d7e6e2c3f5 - _start
  24:                0x0 - <unknown>
```

</details>

**Update:** Interestingly on my second computer, a very similar setup with Fedora 35 with KDE/Plasma, but with a _Intel HD Graphics 550 (BDW GT2)_ integrated GPU the problem does not occur.

**Comment by derekdreery** [comment]
I'm also using a Radeon graphics card. Could it be specific to the Radeon Vulkan implementation? I can also run all the wgpu examples fine.

**Comment by rleh** [comment]
Any ideas, tips, suggestions on how I can further help here to find and fix the error?

**Comment by dzhou121** [comment]
Probably try to change ```DeviceDescriptor``` here

https://github.com/lapce/piet-wgpu/blob/master/src/lib.rs#L66

To something like 
```
wgpu::DeviceDescriptor {
    features: wgpu::Features::empty(),
    limits: wgpu::Limits::downlevel_defaults(),
    label: None,
}
```

**Comment by sebastian-de** [comment]
I'm currently testing lapce 0.0.12 on Fedora 36 with KDE Plasma Wayland. I also have a AMD GPU (Cezanne/Renoir laptop graphics).
Starting without env variables seems to choose the GL backend and panics instantly (same with `WGPU_BACKEND=gl`).
Running with `WGPU_BACKEND=vulkan` works fine here.

**Comment by LukasDoesDev** [comment]
Running on `Arch Linux 5.17.1-arch1-1` with the `amdgpu` driver and the `AMD ATI Radeon HD 7770` card. I use basic Xorg with the i3 window manager.
Running with the environment variable `WGPU_BACKEND` set to `gl` works fine but without it and setting it to `vulkan` results in a white screen and the following warning message I get when trying to play games:
```
WARNING: radv is not a conformant Vulkan implementation, testing use only.
```

**Comment by pollend** [comment]
I was looking at this in renderdoc and I do see output from the swapchain. there is a clear on commands 24-25 seems like some kind of order problem. shrinking the window seems to re-order thing in a way where its visible again. 

![image](https://user-images.githubusercontent.com/854359/163310739-f9c203bb-1a05-4b8e-adf9-7ae94bd25580.png)


![image](https://user-images.githubusercontent.com/854359/163310560-09c445fd-7dc4-46e0-9580-b0ab35cb9245.png)

There is something at

**Comment by SingingBush** [comment]
built from master branch just now an can confirm that running `WGPU_BACKEND=vulkan ./lapce` no longer results in a blank window. However I am seeing an issue with both _vulkan_ and _gl_ backend with transparency.

Where the borders are between the sections of the UI I can see through to the application behind Lapce:
![image](https://user-images.githubusercontent.com/870567/164705890-2a5e0334-92ff-4b36-8067-11942fd98c1c.png)

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by murlakatamenka** [comment]
@bugadani I had [white screen of death](https://www.reddit.com/r/rust/comments/t550wy/lapce_open_source_code_editor_inspired_by_xieditor/hz3spok/) before, but Lapce 0.1.0 and 0.1.1 are finally working for me!

Setup details: Arch Linux, Linux XanMod 5.17.9 kernel (was on this kernel back then too), R9 290 via amdgpu, wayland

**Comment by panekj** [comment]
Fixed (we don't use wgpu anymore)
