### ISSUE TITLE
Completion Crash

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#1202]
**Version**: 0.2  

Log:  

![image](https://user-images.githubusercontent.com/13157904/190167890-b46dc86d-7b38-41c3-b550-9bc9767a909b.png)

The issue is presumably in completion, with the index being bad and so crashing since it tries going out of bounds. We are probably not clearing the index properly somewhere? It would probably be for the best to make the function referenced ( https://github.com/lapce/lapce/blob/master/lapce-data/src/completion.rs#L326 ) just return an `Option<&_>` to avoid any risk of crashing at all.

**Comment by lena64t** [comment]
The same problem, but with backtrace:

Lapce version: 0.2.0 - a41bf067659e36ac73e990c736f53d69c7bf88fb (current master)
Rustc version: 1.65.0-nightly (17cbdfd07 2022-09-13)
OS: Manjaro 22.0.0 (Linux 5.19.7-1-MANJARO) w/ KDE

Backtrace:
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 11', lapce-data/src/completion.rs:326:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/17cbdfd07178349d0a3cecb8e7dde8f915666ced/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/17cbdfd07178349d0a3cecb8e7dde8f915666ced/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/17cbdfd07178349d0a3cecb8e7dde8f915666ced/library/core/src/panicking.rs:84:5
   3: lapce_data::completion::CompletionData::current_item
   4: lapce_ui::completion::CompletionContainer::update_documentation
   5: <lapce_ui::completion::CompletionContainer as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::update
   6: druid::core::WidgetPod<T,W>::update
   7: <lapce_ui::tab::LapceTab as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::update
   8: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::update
   9: druid::core::WidgetPod<T,W>::update
  10: <lapce_ui::window::LapceWindow as druid::widget::widget::Widget<lapce_data::data::LapceWindowData>>::update
  11: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::update
  12: druid::core::WidgetPod<T,W>::update
  13: druid::window::Window<T>::update
  14: druid::win_handler::InnerAppState<T>::do_update
  15: druid::win_handler::AppState<T>::do_window_event
  16: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::key_down
  17: druid_shell::text::simulate_input
  18: druid_shell::backend::gtk::window::WindowState::with_handler
  19: <O as gtk::auto::widget::WidgetExt>::connect_key_press_event::key_press_event_trampoline
  20: <unknown>
  21: g_closure_invoke
  22: <unknown>
  23: g_signal_emit_valist
  24: g_signal_emit
  25: <unknown>
  26: gtk_window_propagate_key_event
  27: <unknown>
  28: <unknown>
  29: g_signal_emit_valist
  30: g_signal_emit
  31: <unknown>
  32: <unknown>
  33: gtk_main_do_event
  34: <unknown>
  35: <unknown>
  36: g_main_context_dispatch
  37: <unknown>
  38: g_main_context_iteration
  39: g_application_run
  40: <O as gio::application::ApplicationExtManual>::run
  41: druid_shell::backend::gtk::application::Application::run
  42: druid_shell::application::Application::run
  43: druid::app::AppLauncher<T>::launch
  44: lapce_ui::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[1]  + 7945 exit 101   RUST_BACKTRACE=1 lapce .
```
