### ISSUE TITLE
App crashes immediately on Linux (Ubuntu)

### ISSUE THREAD

**Issue by blasrodri** [lapce/lapce#127]
HI! Reporting a crash I got right away after I launched `lapce` for the first time.
(after running this command, I pressed the key combination to maximize the window in Ubuntu) and it crashed.

I'm running:
```
Linux f1 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
f1@f1:~/Downloads/Lapce$ ./lapce 
libEGL warning: DRI2: failed to authenticate
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 1039 requests (1039 known processed) with 0 events remaining.
```

**Comment by bugadani** [comment]
Hi and thanks for reporting this issue!

Could you please confirm that Lapce work correctly until you maximize the window, or if it crashes shortly after startup anyway?

**Comment by blasrodri** [comment]
I've switched to Arch and I don't experience the issue here. Sorry for not being able to give you more input. Feel free to close it.

**Comment by bugadani** [comment]
No worries! We can leave this open in case someone else experiences the crash.

**Comment by tacerus** [comment]
Hi, 

I encounter a similar issue on openSUSE, using the tarball release. The program does not launch at all. Is it related, or should I open a new issue?

```
$ env RUST_BACKTRACE=full /opt/Lapce/lapce
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x55d6b61c1f5c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d6b61c1f5c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d6b61c1f5c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d6b61c1f5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d6b61ee71c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x55d6b61b7a53 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x55d6b61c4a62 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d6b61c4a62 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d6b61c4a62 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x55d6b61c4645 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x55d6b61c50b3 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x55d6b61c4dd0 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x55d6b61c2404 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55d6b61c4b09 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x55d6b4bf64a1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x55d6b5efe829 - wgpu::backend::direct::Context::handle_error_fatal::h64093037c424dcf2
  16:     0x55d6b5eff3d2 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::h9ba88c9b94955646
  17:     0x55d6b5e00c35 - piet_wgpu::WgpuRenderer::set_size::h28b8a607a924b60c
  18:     0x55d6b4e458b0 - druid::window::Window<T>::new::h2db9a7877d26d6e6
  19:     0x55d6b4d38556 - druid::win_handler::AppState<T>::build_native_window::h603723e718219ef8
  20:     0x55d6b4c09485 - lapce_ui::app::lanuch::hcbe11df89c48fc59
  21:     0x55d6b4bf6d43 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd458a4cc88aa7051
  22:     0x55d6b4bf6d79 - std::rt::lang_start::{{closure}}::h3dc07a670cf4b232
  23:     0x55d6b61c1610 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  24:     0x55d6b61c1610 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  25:     0x55d6b61c1610 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  26:     0x55d6b61c1610 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  27:     0x55d6b61c1610 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  28:     0x55d6b61c1610 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  29:     0x55d6b61c1610 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  30:     0x55d6b61c1610 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  31:     0x55d6b61c1610 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  32:     0x55d6b4bf6d32 - main
  33:     0x7f881cb25630 - __libc_start_call_main
  34:     0x7f881cb256f0 - __libc_start_main_alias_1
  35:     0x55d6b4bf6c3e - _start
  36:                0x0 - <unknown>
```

**Comment by bugadani** [comment]
@tacerus Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by bugadani** [comment]
Glad to hear, thanks for the feedback! :)
