### ISSUE TITLE
fails to start: 'Error in Surface::configure: Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.

### ISSUE THREAD

**Issue by matthiaskrgr** [lapce/lapce#13]
WM is i3, maybe that's relevant
backtrace:
````

start to watch path "/home/matthias/.config/lapce/settings.toml"
2021-12-14T10:28:29.204677Z DEBUG druid::localization: available locales [], current en-US
2021-12-14T10:28:29.204712Z DEBUG druid::localization: resolved: [en-US]
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

primitives buffer size 80000
size is (0×0)
plugin reload from paths
thread 'main' panicked at 'Error in Surface::configure: Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.', /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:204:9
stack backtrace:
proxy mainfiest paths []
   0:     0x55b36a5b572c - std::backtrace_rs::backtrace::libunwind::trace::hf7449935ead7573e
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b36a5b572c - std::backtrace_rs::backtrace::trace_unsynchronized::h221aa2d88d72372a
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b36a5b572c - std::sys_common::backtrace::_print_fmt::h1c77e8983e1df895
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b36a5b572c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4ec41a9a6b0d22c
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b36a5de16c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/core/src/fmt/mod.rs:1149:17
   5:     0x55b36a5b0565 - std::io::Write::write_fmt::haf74340a8cbeaa88
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/io/mod.rs:1660:15
   6:     0x55b36a5b7470 - std::sys_common::backtrace::_print::h2d15cd157796a64a
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b36a5b7470 - std::sys_common::backtrace::print::h52d286d22e2398eb
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b36a5b7470 - std::panicking::default_hook::{{closure}}::h6da08fba6306daf2
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:211:50
   9:     0x55b36a5b701b - std::panicking::default_hook::h266f67a22e76b11a
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:228:9
  10:     0x55b36a5b7c54 - std::panicking::rust_panic_with_hook::he55698a957f4fb6d
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:606:17
  11:     0x55b36a5b7700 - std::panicking::begin_panic_handler::{{closure}}::h01f453c3ac181895
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:502:13
  12:     0x55b36a5b5bd4 - std::sys_common::backtrace::__rust_end_short_backtrace::h675d77c6e5a3926d
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55b36a5b7669 - rust_begin_unwind
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:498:5
  14:     0x55b36a5db751 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/core/src/panicking.rs:107:14
  15:     0x55b36a2f63e9 - wgpu::backend::direct::Context::handle_error_fatal::hf02f94e005734625
  16:     0x55b36a2f6c32 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::h1e26a3d305121020
  17:     0x55b36a1c3621 - piet_wgpu::WgpuRenderer::set_size::h39d61a07a27b7409
  18:     0x55b369c57da6 - druid::window::Window<T>::event::hbffdae07b8b371be
  19:     0x55b369aeb670 - druid::win_handler::InnerAppState<T>::do_window_event::h5b4905f76e2f8f9c
  20:     0x55b369ae6f8e - druid::win_handler::AppState<T>::do_window_event::hd07e04d9f73dd55b
  21:     0x55b369ae927e - druid::win_handler::AppState<T>::do_winit_window_event::h31234667683be2d5
  22:     0x55b369c97401 - druid::app::AppLauncher<T>::launch::{{closure}}::h1b95f4ce225a17cb
  23:     0x55b369c98b44 - winit::platform_impl::platform::sticky_exit_callback::hda7583c4bb2e4c40
  24:     0x55b369b0f357 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::hfeb7524d1a0e910d
  25:     0x55b369ceb564 - winit::platform_impl::platform::x11::EventLoop<T>::run::h4f457f983d6cede1
  26:     0x55b369c98a04 - winit::platform_impl::platform::EventLoop<T>::run::h6052ff6f68dc10f4
  27:     0x55b369c5a02e - winit::event_loop::EventLoop<T>::run::h75c8b6279e5a069b
  28:     0x55b369c55c0b - druid::app::AppLauncher<T>::launch::h033724c5b00f19c8
  29:     0x55b369af0422 - lapce_core::app::lanuch::hefb9cbf4ef913ee8
  30:     0x55b369aba2a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7ef695c90683f866
  31:     0x55b369aba239 - std::rt::lang_start::{{closure}}::h7ee1b3cb983f9dac
  32:     0x55b36a5b4f71 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3ab949a23c24b3b3
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/core/src/ops/function.rs:259:13
  33:     0x55b36a5b4f71 - std::panicking::try::do_call::hd77545f815897665
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:406:40
  34:     0x55b36a5b4f71 - std::panicking::try::h7ce07831cfe77010
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:370:19
  35:     0x55b36a5b4f71 - std::panic::catch_unwind::h3a6382eb739fc3cb
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panic.rs:133:14
  36:     0x55b36a5b4f71 - std::rt::lang_start_internal::{{closure}}::ha0ce13fbefa6ed19
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/rt.rs:128:48
  37:     0x55b36a5b4f71 - std::panicking::try::do_call::hbacbc27e75105135
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:406:40
  38:     0x55b36a5b4f71 - std::panicking::try::he42832d690a14084
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panicking.rs:370:19
  39:     0x55b36a5b4f71 - std::panic::catch_unwind::h868b7b91fa924314
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/panic.rs:133:14
  40:     0x55b36a5b4f71 - std::rt::lang_start_internal::h7797a51a89d842a3
                               at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/library/std/src/rt.rs:128:20
  41:     0x55b369aba292 - main
  42:     0x7fa985f3eb25 - __libc_start_main
  43:     0x55b369aba15e - _start
  44:                0x0 - <unknown>
palette update process stopped


````

**Comment by matthiaskrgr** [comment]
Looks like it's fixed in   93737031e7ce6dfafefd60df3503c039c2df90eb :)
