### ISSUE TITLE
Minimising the window crashes the app

### ISSUE THREAD

**Issue by dannyrevenant** [lapce/lapce#15]
System: Windows 10

```
thread 'main' panicked at 'Error in Surface::configure: Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.', C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.0\src\backend\direct.rs:204:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\/library\core\src\panicking.rs:107
   2: wgpu::backend::direct::Context::handle_error_fatal<enum$<wgpu_core::present::ConfigureSurfaceError> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.0\src\backend\direct.rs:204
   3: wgpu::backend::direct::impl$3::surface_configure
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.0\src\backend\direct.rs:910
   4: wgpu::Surface::configure
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.0\src\lib.rs:3184
   5: piet_wgpu::WgpuRenderer::set_size
             at C:\Users\__\.cargo\git\checkouts\piet-wgpu-913b036275d2afb6\278cdfd\src\lib.rs:120
   6: druid::window::Window<lapce_core::data::LapceData>::event<lapce_core::data::LapceData>
             at C:\Users\__\.cargo\git\checkouts\druid-f6980810fb848923\c42de0b\druid\src\window.rs:267
   7: druid::win_handler::InnerAppState<lapce_core::data::LapceData>::do_window_event<lapce_core::data::LapceData>
             at C:\Users\__\.cargo\git\checkouts\druid-f6980810fb848923\c42de0b\druid\src\win_handler.rs:432   8: druid::win_handler::AppState<lapce_core::data::LapceData>::do_window_event<lapce_core::data::LapceData>
             at C:\Users\__\.cargo\git\checkouts\druid-f6980810fb848923\c42de0b\druid\src\win_handler.rs:680   9: druid::win_handler::AppState<lapce_core::data::LapceData>::do_winit_window_event<lapce_core::data::LapceData>
             at C:\Users\__\.cargo\git\checkouts\druid-f6980810fb848923\c42de0b\druid\src\win_handler.rs:669  10: druid::app::impl$1::launch::closure$1<lapce_core::data::LapceData>
             at C:\Users\__\.cargo\git\checkouts\druid-f6980810fb848923\c42de0b\druid\src\app.rs:334
  11: winit::platform_impl::platform::event_loop::impl$2::run_return::closure$0<enum$<druid_shell::window::WinitEvent>,druid::app::impl$1::launch::closure$1>
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:206
  12: alloc::boxed::impl$45::call_mut<tuple$<enum$<winit::event::Event<enum$<druid_shell::window::WinitEvent> > >,ref_mut$<enum$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum$<winit::event::Event<enum$<druid_shell::window::Wini
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\alloc\src\boxed.rs:1818
  13: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:245
  14: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\panic\unwind_safe.rs:271
  15: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>,tuple$<> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:406
  16: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked::closure$1::closure$0>,tuple$<> >
  17: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:370
  18: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>,tuple$<> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panic.rs:133
  19: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::catch_unwind<enum$<druid_shell::window::WinitEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::clos
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::call_event_handler<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:239
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::send_event<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:220
  22: winit::platform_impl::platform::event_loop::SubclassInput<enum$<druid_shell::window::WinitEvent> >::send_event<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:96
  23: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:991
  24: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0,tuple$<> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\ops\function.rs:227
  25: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\panic\unwind_safe.rs:271
  26: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>,isize>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:406
  27: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked::closure$1::closure$0>,tuple$<> >
  28: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:370
  29: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>,isize>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panic.rs:133
  30: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::catch_unwind<enum$<druid_shell::window::WinitEvent>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  31: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  32: winit::platform_impl::platform::event_loop::public_window_callback<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  33: DefSubclassProc
  34: DefSubclassProc
  35: CallWindowProcW
  36: SendMessageW
  37: GetWindowTextW
  38: IsIconic
  39: IsCompositionActive
  40: IsCompositionActive
  41: GetWindowTextW
  42: CallWindowProcW
  43: CallWindowProcW
  44: DefSubclassProc
  45: DefSubclassProc
  46: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:965
  47: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0,tuple$<> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\ops\function.rs:227
  48: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\panic\unwind_safe.rs:271
  49: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>,isize>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:406
  50: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked::closure$1::closure$0>,tuple$<> >
  51: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:370
  52: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>,isize>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panic.rs:133
  53: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::catch_unwind<enum$<druid_shell::window::WinitEvent>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  54: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  55: winit::platform_impl::platform::event_loop::public_window_callback<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  56: DefSubclassProc
  57: DefSubclassProc
  58: CallWindowProcW
  59: DispatchMessageW
  60: LookupIconIdFromDirectoryEx
  61: KiUserCallbackDispatcher
  62: NtUserMessageCall
  63: GetWindowTextW
  64: IsIconic
  65: GetUserColorPreference
  66: Ordinal96
  67: IsCompositionActive
  68: IsCompositionActive
  69: GetWindowTextW
  70: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1047
  71: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0,tuple$<> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\ops\function.rs:227
  72: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\core\src\panic\unwind_safe.rs:271
  73: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>,isize>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:406
  74: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked::closure$1::closure$0>,tuple$<> >
  75: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0> >
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panicking.rs:370
  76: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>,isize>
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\library\std\src\panic.rs:133
  77: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::catch_unwind<enum$<druid_shell::window::WinitEvent>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0>
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  78: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  79: winit::platform_impl::platform::event_loop::public_window_callback<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\__\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  80: DefSubclassProc
  81: DefSubclassProc
  82: CallWindowProcW
  83: DispatchMessageW
  84: SendMessageTimeoutW
  85: KiUserCallbackDispatcher
  86: NtUserMessageCall
  87: GetWindowTextW
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
buffer update process stopped
```

**Comment by dzhou121** [comment]
Can you try to re-download the v0.0.1 release? 

https://github.com/lapce/lapce/releases/tag/v0.0.1

**Comment by bugadani** [comment]
Hi @dannyrevenant! Thank you for reporting this issue!

As I can't reproduce this on Windows 11, can you please verify if this has been fixed for you? Thank you!
