### ISSUE TITLE
Version 0.0.11 does not launch on Debian with Wayland

### ISSUE THREAD

**Issue by franckbret** [lapce/lapce#166]
Os: Debian GNU/Linux 11 (bullseye)
Processor: AMD® Ryzen 7 pro 4750u with radeon graphics × 16 
Graphics: AMD® Renoir
Gnome: 3.38.5
Window: Wayland 

Traceback : 
```
franck@debian-franck:~/workspace/sources/Lapce$ RUST_BACKTRACE=full ./lapce
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x5653ea71d50c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5653ea71d50c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5653ea71d50c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5653ea71d50c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5653ea7497ac - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5653ea713af3 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x5653ea720012 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5653ea720012 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5653ea720012 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x5653ea71fbf5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x5653ea720663 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x5653ea720380 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x5653ea71d9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5653ea7200b9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x5653e90aa311 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x5653ea45ad49 - wgpu::backend::direct::Context::handle_error_fatal::hb5dab7df19ac64b0
  16:     0x5653ea45b752 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::hcb9d6156db1333de
  17:     0x5653ea35d025 - piet_wgpu::WgpuRenderer::set_size::h58a30e56e5d61b06
  18:     0x5653e92e47b0 - druid::window::Window<T>::new::h532543f719e82fba
  19:     0x5653e926fd02 - druid::win_handler::AppState<T>::build_native_window::hdbfe6de93e4e8b7a
  20:     0x5653e90d8a95 - druid::app::AppLauncher<T>::launch::h3354e4b3f275814e
  21:     0x5653e90b3a61 - lapce_ui::app::lanuch::h39b9800466e0d636
  22:     0x5653e90aab73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4dad58669905a304
  23:     0x5653e90aaba9 - std::rt::lang_start::{{closure}}::h551fd6a95f18f51e
  24:     0x5653ea71cbc0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  25:     0x5653ea71cbc0 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  26:     0x5653ea71cbc0 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27:     0x5653ea71cbc0 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28:     0x5653ea71cbc0 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  29:     0x5653ea71cbc0 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  30:     0x5653ea71cbc0 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  31:     0x5653ea71cbc0 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  32:     0x5653ea71cbc0 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  33:     0x5653e90aabe2 - main
  34:     0x7fe096abcd0a - __libc_start_main
  35:     0x5653e90aaaae - _start
  36:                0x0 - <unknown>

```

**Comment by dypa** [comment]
@franckbret gfx-rs/wgpu supports only Vulkan API, can you install package `mesa-vulkan-drivers` (`sudo apt install mesa-vulkan-drivers`) and check again?

@bugadani can you add for linux information users about this table https://github.com/gfx-rs/wgpu#supported-platforms?

**Comment by bugadani** [comment]
@dypa thanks for the link. We might be transitioning away from wgpu in the near future, so I think we'll include that information once we decide what the long term rendering technology will be.

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?
