### ISSUE TITLE
Does not start under qemu-user

### ISSUE THREAD

**Issue by L3P3** [lapce/lapce#1823]
## Lapce Version

0.2.5

## System information

Debian bookworm/sid
Mate desktop
Qemu-User (processor polyfill)

## Describe the bug
When starting lapce, there is no window, but also no kind of error message at all. It just silently quits after some seconds.

## Additional information

I am using Qemu-User which converts missing amd64 commands. It is quite stable and other apps work just fine this way.

https://user-images.githubusercontent.com/4629449/208249605-c6f120c1-58b9-4a9b-85d9-89e75b8b8f54.mp4

**Comment by panekj** [comment]
It requires OpenGL

**Comment by L3P3** [comment]
Nope, I tried using the flag to force virtual gpu, but it still does the same.

**Comment by panekj** [comment]
`RUST_LOG=off,lapce_ui=debug lapce -w --new`

**Comment by L3P3** [comment]
```
l3p3@l3p3-rkk:~$ RUST_LOG=off,lapce_ui=debug lapce -w --new
Parsing RUST_LOG
level='off' for all modules
module='lapce_ui', level='debug'
Gtk-Message: 16:48:06.508: Failed to load module "canberra-gtk-module"
l3p3@l3p3-rkk:~$
```

**Comment by L3P3** [comment]
```
$ RUST_LOG=debug lapce -wn
Parsing RUST_LOG
level='debug' for all modules
[2022-12-17][16:49:55][sled::pagecache::snapshot][DEBUG] no previous snapshot found
[2022-12-17][16:49:55][sled::pagecache::iterator][DEBUG] ordering before clearing tears: {}, max_header_stable_lsn: 0
[2022-12-17][16:49:55][sled::pagecache::iterator][DEBUG] in clean_tail_tears, found missing item in tail: None and we'll scan segments {} above lowest lsn 0
[2022-12-17][16:49:55][sled::pagecache::iterator][DEBUG] unable to load new segment: Io(Custom { kind: Other, error: "no segments remaining to iterate over" })
[2022-12-17][16:49:55][sled::pagecache::iterator][DEBUG] filtering out segments after detected tear at (lsn, lid) -1
[2022-12-17][16:49:55][sled::pagecache::iterator][DEBUG] unable to load new segment: Io(Custom { kind: Other, error: "no segments remaining to iterate over" })
[2022-12-17][16:49:55][sled::pagecache::segment][DEBUG] SA starting with tip 0 stable -1 free {}
[2022-12-17][16:49:55][sled::pagecache::iobuf][DEBUG] starting log for a totally fresh system
[2022-12-17][16:49:55][sled::pagecache::segment][DEBUG] segment accountant returning offset: 0 for lsn 0 on deck: {}
[2022-12-17][16:49:55][sled::pagecache::iobuf][DEBUG] starting IoBufs with next_lsn: 0 next_lid: 0
[2022-12-17][16:49:55][sled::pagecache::iobuf][DEBUG] storing lsn 0 in beginning of buffer
[2022-12-17][16:49:55][sled::pagecache][DEBUG] load_snapshot loading pages from 0..0
[2022-12-17][16:49:55][sled::meta][DEBUG] allocated pid 3 for root of new_tree [95, 95, 115, 108, 101, 100, 95, 95, 100, 101, 102, 97, 117, 108, 116]
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: g f
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: o
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: /
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: :
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+g
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: g g
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: h
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: j
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: k
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: l
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: a
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+a
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: i
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: u
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+r
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+i
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+o
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+n
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: g d
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: g h
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: p
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+p
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+j
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: y
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: x
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+p
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: s
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: c
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+s
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: c c
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: c w
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: c e
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+i
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: o
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: 0
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ^
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: $
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: w
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: e
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: b
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+o
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+e
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+y
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+u
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+d
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: z z
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: z t
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: z b
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: d
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: f
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+f
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ;
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: d
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: >
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: <
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: y
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: *
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: n
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+n
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: %
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ] )
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: [ (
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ] }
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: [ {
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: v
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+v
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+v
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w l
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w h
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w j
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w k
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w s
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w v
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w c
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w x
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: space
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: >
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: <
[2022-12-17][16:49:57][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+c
[2022-12-17][16:49:57][lapce_data::keypress][ERROR] Failed to load from "/home/l3p3/.config/lapce-stable/keymaps.toml": no keymaps
Gtk-Message: 16:50:00.392: Failed to load module "canberra-gtk-module"
[2022-12-17][16:50:01][reqwest::connect][DEBUG] starting new connection: https://plugins.lapce.dev/
[2022-12-17][16:50:01][reqwest::connect][DEBUG] starting new connection: https://api.github.com/
[2022-12-17][16:50:01][hyper::client::connect::dns][DEBUG] resolving host="api.github.com"
[2022-12-17][16:50:01][hyper::client::connect::dns][DEBUG] resolving host="plugins.lapce.dev"
[2022-12-17][16:50:01][hyper::client::connect::http][DEBUG] connecting to 140.82.121.6:443
[2022-12-17][16:50:01][hyper::client::connect::http][DEBUG] connected to 140.82.121.6:443
[2022-12-17][16:50:01][hyper::client::connect::http][DEBUG] connecting to 104.26.5.224:443
[2022-12-17][16:50:01][hyper::client::connect::http][DEBUG] connected to 104.26.5.224:443
[2022-12-17][16:50:04][hyper::proto::h1::io][DEBUG] flushed 82 bytes
[2022-12-17][16:50:04][hyper::proto::h1::io][DEBUG] flushed 105 bytes
[2022-12-17][16:50:04][hyper::proto::h1::io][DEBUG] parsed 11 headers
[2022-12-17][16:50:04][hyper::proto::h1::conn][DEBUG] incoming body is chunked encoding
[2022-12-17][16:50:04][hyper::proto::h1::io][DEBUG] parsed 25 headers
[2022-12-17][16:50:04][hyper::proto::h1::conn][DEBUG] incoming body is chunked encoding
[2022-12-17][16:50:04][hyper::proto::h1::decode][DEBUG] incoming chunked header: 0x4545 (17733 bytes)
[2022-12-17][16:50:04][hyper::proto::h1::decode][DEBUG] incoming chunked header: 0xC12 (3090 bytes)
[2022-12-17][16:50:04][hyper::proto::h1::conn][DEBUG] incoming body completed
[2022-12-17][16:50:04][hyper::proto::h1::conn][DEBUG] incoming body completed
[2022-12-17][16:50:04][hyper::client::pool][DEBUG] pooling idle connection for ("https", plugins.lapce.dev)
[2022-12-17][16:50:04][hyper::client::pool][DEBUG] pooling idle connection for ("https", api.github.com)
[2022-12-17][16:50:07][reqwest::connect][DEBUG] starting new connection: https://plugins.lapce.dev/
[2022-12-17][16:50:07][hyper::client::connect::dns][DEBUG] resolving host="plugins.lapce.dev"
[2022-12-17][16:50:07][hyper::client::connect::http][DEBUG] connecting to 172.67.71.165:443
[2022-12-17][16:50:07][hyper::client::connect::http][DEBUG] connected to 172.67.71.165:443
[2022-12-17][16:50:08][hyper::proto::h1::io][DEBUG] flushed 112 bytes
[2022-12-17][16:50:08][hyper::proto::h1::io][DEBUG] parsed 11 headers
[2022-12-17][16:50:08][hyper::proto::h1::conn][DEBUG] incoming body is chunked encoding
[2022-12-17][16:50:08][hyper::proto::h1::decode][DEBUG] incoming chunked header: 0x13 (19 bytes)
[2022-12-17][16:50:08][hyper::proto::h1::conn][DEBUG] incoming body completed
[2022-12-17][16:50:08][hyper::client::pool][DEBUG] pooling idle connection for ("https", plugins.lapce.dev)
[2022-12-17][16:50:10][druid::localization][DEBUG] available locales [], current de-DE
[2022-12-17][16:50:10][druid::localization][DEBUG] resolved: [en-US]
[2022-12-17][16:50:13][panic][ERROR] thread 'main' panicked at 'called glGetString but it was not loaded.': /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.11.2/src/gl46.rs:4232
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   7: glow::gl46::go_panic_because_fn_not_loaded
   8: <O as gtk::auto::widget::WidgetExt>::connect_realize::realize_trampoline
   9: g_closure_invoke
  10: <unknown>
  11: g_signal_emit_valist
  12: g_signal_emit
  13: gtk_widget_realize
  14: druid::win_handler::AppState<T>::build_native_window
  15: lapce_ui::app::launch
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: main
  18: <unknown>
  19: __libc_start_main
  20: _start
```

**Comment by L3P3** [comment]
As this probably is an issue from the glow lib, I try posting my problem there. :grin:

**Comment by L3P3** [comment]
From my research, I assume that the issue here is that libgl was not loaded. Which is weird since there should have been an error message about this.

**Comment by L3P3** [comment]
Could you give me a hint on how I can see which libraries are loaded by lapce? It looks like libgl.so is not loaded or its loading the wrong version of it that lacks some methods. :thinking:

**Comment by panekj** [comment]
`ldd ./lapce`

**Comment by L3P3** [comment]
Quite many. :open_mouth:

```
$ ldd /usr/bin/lapce
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x0000000047772000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x0000000047793000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00000000479ad000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00000000479f5000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00000000479fa000)
	libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x0000000047a59000)
	libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x0000000048278000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x0000000048385000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00000000483b3000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x0000000048591000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00000000486c8000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00000000486e8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00000000486ed000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00000000486f4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00000000486f9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00000000487d8000)
	/lib64/ld-linux-x86-64.so.2 (0x0000000040000000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00000000489b9000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x0000000048a83000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x0000000048aae000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x0000000048aba000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x0000000048ac6000)
	libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x0000000048acc000)
	libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x0000000048add000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x0000000048b45000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x0000000048c4b000)
	libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x0000000048d71000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x0000000048d8a000)
	libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x0000000048da6000)
	libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x0000000048db1000)
	libepoxy.so.0 => /lib/x86_64-linux-gnu/libepoxy.so.0 (0x0000000048dda000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x0000000048f09000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x0000000048f1f000)
	libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x0000000049061000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x000000004909d000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00000000490a5000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00000000490eb000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00000000490ff000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x0000000049104000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x0000000049119000)
	libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x0000000049126000)
	libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x000000004912b000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x0000000049130000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x000000004913f000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x0000000049144000)
	libjpeg.so.62 => /lib/x86_64-linux-gnu/libjpeg.so.62 (0x000000004917a000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x000000004920d000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x0000000049270000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00000000492a0000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x000000004933a000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x0000000049347000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x0000000049352000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x000000004937e000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x000000004942b000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x0000000049430000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x000000004945a000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x0000000049468000)
	libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x0000000049475000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00000000494b2000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x0000000049508000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x000000004955f000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x0000000049582000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x000000004958c000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x0000000049600000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x0000000049999000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x0000000049a68000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x0000000049a7e000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x0000000049a89000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x0000000049bd2000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x0000000049bfa000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x0000000049cb3000)
	libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x0000000049cd9000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x0000000049ce6000)
```

**Comment by L3P3** [comment]
I cannot find libgl there. :confused:

**Comment by panekj** [comment]
Lapce requires specific GUI libraries which may not be feasible to run in qemu
