### ISSUE TITLE
Can't open binary (Debian linux on ChromeOS)

### ISSUE THREAD

**Issue by Explosion-Scratch** [lapce/lapce#201]
Downloading the latest binary as such:
```
aria2c -s 16 -x 16 https://github.com/lapce/lapce/releases/download/v0.0.11/Lapce-linux.tar.gz
# Renaming it
mv *.tar.gz lapce.gz
# Extracting
tar -zxvf *.gz
# Running (the file exists, it extracted to "/mnt/chromeos/MyFiles/Downloads/Lapsce"
Lapsce/lapce
```

Which gives this error:
```
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I then retried with sudo and then set the env variable before running:
```
MyFiles/Downloads/Lapce [⏱ 2s]
⬢ [Systemd] ❯ RUST_BACKTRACE=full, ./lapce
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: wgpu::backend::direct::Context::handle_error_fatal
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
   4: piet_wgpu::WgpuRenderer::set_size
   5: druid::window::Window<T>::new
   6: druid::win_handler::AppState<T>::build_native_window
   7: druid::app::AppLauncher<T>::launch
   8: lapce_ui::app::lanuch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bugadani** [comment]
Could you please provide what hardware and OS you are using? Some users are experiencing this issue and finding the common link would be helpful.

**Comment by Explosion-Scratch** [comment]
Running `screenfetch`:
```
         _,met$$$$$gg.           penguin@penguin
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.10.92-14532-g179c52887ab5
   ,$$P'              `$$$.      Uptime: 1d 2h 37m
  ',$$P       ,ggs.     `$$b:    Packages: 923
  `d$$'     ,$P"'   .    $$$     Shell: bash 5.1.4
   $$P      d$'     ,    $$P     Resolution: 1920x1080
   $$:      $$.   -    ,d$$'     WM: Sommelier
   $$\;      Y$b._   _,d$P'      GTK Theme: CrosAdapta [GTK2/3]
   Y$$.    `.`"Y$$$$P"'          Font: Roboto 11
   `$$b      "-.__               Disk: 11G / 24G (50%)
    `Y$$                         CPU: 06/7a @ 2x 1.094GHz
     `Y$$.                       RAM: 4MiB / 2775MiB
       `$$b.                    
         `Y$$b.                 
            `"Y$b._             
                `""""           
                                
```

**Comment by mateus-md** [comment]
Same issue here. Both release and debug builds. My system:
```
                             mmd@mmd-pxdev-22
                             OS: Pop 21.10 impish
                             Kernel: x86_64 Linux 5.16.11-76051611-generic
         #####               Uptime: 1h 44m
        #######              Packages: Unknown
        ##O#O##              Shell: bash
        #######              Resolution: 1360x768
      ###########            DE: GNOME 40.0
     #############           WM: Mutter
    ###############          WM Theme: Pop
    ################         GTK Theme: Pop-dark [GTK2/3]
   #################         Icon Theme: Pop
 #####################       Font: Fira Sans Semi-Light 10
 #####################       Disk: 276G / 914G (32%)
   #################         CPU: AMD Ryzen 3 2200G with Radeon Vega Graphics @ 4x 3,5GHz
                             GPU: AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.44.0, 5.16.11-76051611-generic, LLVM 12.0.1)
                             RAM: 3065MiB / 6933MiB
```

**Comment by Explosion-Scratch** [comment]
Still happening `v0.0.12`, same operating system and steps

**Comment by ghishadow** [comment]
is `mesa-vulkan-drivers` installed ? what is output of `ls /usr/share/vulkan/icd.d/`? this will improve with new opengl renderer i think 🤔

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by Explosion-Scratch** [comment]
> Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

Not trying this again I uninstalled my linux VM

**Comment by bugadani** [comment]
Fair enough, thanks :) In this case I'll close this issue, and hope it will not pop up again.

**Comment by Explosion-Scratch** [comment]
No problemo, thanks for understanding 🤠
