### ISSUE TITLE
v0.2.7 crash on Linux

### ISSUE THREAD

**Issue by altair-albert** [lapce/lapce#2271]
## Lapce Version
0.2.7
## System information
Description:    Manjaro Linux
Release:        22.0.5

## Describe the bug
when click mouse right button in editor which opened  any file.  the main process will crash.

## Additional information
```syslog
[2023-03-22][09:36:30][lapce_data::proxy][ERROR] lsp server stderr: I[09:36:30.185] <-- textDocument/codeAction(3)
[2023-03-22][09:36:30][lapce_data::proxy][ERROR] lsp server stderr: I[09:36:30.185] --> reply:textDocument/codeAction(3) 0 ms
[2023-03-22][09:36:30][lapce_data::proxy][ERROR] lsp server stderr: I[09:36:30.375] <-- textDocument/hover(4)
[2023-03-22][09:36:30][lapce_data::proxy][ERROR] lsp server stderr: I[09:36:30.391] --> reply:textDocument/hover(4) 15 ms
[2023-03-22][09:36:32][lapce_data::proxy][ERROR] lsp server stderr: I[09:36:32.125] <-- textDocument/codeAction(5)
[2023-03-22][09:36:32][lapce_data::proxy][ERROR] lsp server stderr: I[09:36:32.126] --> reply:textDocument/codeAction(5) 0 ms
[2023-03-22][09:36:32][druid_shell::hotkey][WARN] warning: HotKey HotKey { mods: CtrlShift, key: Character("c") } includes shift, but text is lowercase. Text is matched literally; this m
[2023-03-22][09:36:32][druid_shell::hotkey][WARN] warning: HotKey HotKey { mods: CtrlShift, key: Character("v") } includes shift, but text is lowercase. Text is matched literally; this m
[2023-03-22][09:36:32][panic][ERROR] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': /github/home/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   7: core::panicking::panic
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
   8: druid_shell::backend::gtk::menu::register_accelerator
   9: druid_shell::backend::gtk::menu::Menu::into_gtk_menu
  10: druid_shell::backend::gtk::window::WindowState::run_deferred
  11: <O as gtk::auto::widget::WidgetExt>::connect_button_press_event::button_press_event_trampoline
  12: <unknown>
  13: g_closure_invoke
  14: <unknown>
  15: g_signal_emit_valist
  16: g_signal_emit
  17: <unknown>
  18: <unknown>
  19: gtk_main_do_event
  20: <unknown>
```

**Comment by hbina** [comment]
Did the stacktrace got cut off?

```
[2023-03-22][09:36:32][panic][ERROR] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': /github/home/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell....?
```

Can you upload the log if possible?

**Comment by altair-albert** [comment]
sorry,  this is log file. 
[20230322-093627.log](https://github.com/lapce/lapce/files/11037282/20230322-093627.log)

**Comment by panekj** [comment]
Closing since we don't use Druid anymore
