### ISSUE TITLE
File content is not visible

### ISSUE THREAD

**Issue by victorcrimea** [lapce/lapce#2342]
## Lapce Version

v0.2.7 commit 3767221f7d049102f54c86700f862def73f9eebf

## System information

Ubuntu 22.04, Gnome 42.5

## Describe the bug
Lapce suddenly stopped showing content of files. Any file opened looks like it is empty. Sometimes event a tab name is empty(no filename).

## Additional information

<details><summary>Console log:</summary>
<p>

[2023-04-14][20:43:26][panic][ERROR] thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()': lapce-proxy/src/plugin/mod.rs:919
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   7: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   8: lapce_proxy::plugin::PluginCatalogRpcHandler::did_open_document
   9: <lapce_proxy::dispatch::Dispatcher as lapce_rpc::proxy::ProxyHandler>::handle_request
  10: lapce_rpc::proxy::ProxyRpcHandler::mainloop
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  14: start_thread
             at ./nptl/./nptl/pthread_create.c:442:8
  15: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

</p>
</details> 

![изображение](https://user-images.githubusercontent.com/5902480/232085801-1df86023-8e51-4454-bb61-6f0d789f68bc.png)

**Comment by victorcrimea** [comment]
Issue was found on release build. Just checked that this issue cannot be reproduced on debug build. Let me know if i can provide anything else to help debugging.
