### ISSUE TITLE
Can't run lapce in debug mode using latest rustc release -- 1.70

### ISSUE THREAD

**Issue by akhildevelops** [lapce/lapce#2463]
## Lapce Version
`v0.2.8`

## System information

Manjaro
rustc : 1.70.0

## Describe the bug
Error while running `cargo run --profile fastdev --bin lapce -- -w`

## Additional information
``` shell
[2023-06-16][18:59:33][lapce_data::keypress][ERROR] Failed to load from "/home/akhil/.config/lapce-debug/keymaps.toml": no keymaps
[2023-06-16][18:59:35][panic][ERROR] thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x2 but is 0x7fe0544f38cb': /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:452
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: core::panicking::panic_misaligned_pointer_dereference
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:174:5
   8: <u16 as swash::internal::parse::FromBeData>::from_be_data_unchecked
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:452:13
      swash::internal::parse::FromBeData::from_be_data
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:424:27
      swash::internal::parse::Bytes::read
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:55:9
      <swash::string::Chars as core::iter::traits::iterator::Iterator>::next
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/string.rs:319:29
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:2481:29
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:857:9
  11: <alloc::string::String as core::iter::traits::collect::Extend<char>>::extend
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:2086:9
  12: fount::scan::FontScanner::scan_font
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:63:13
  13: fount::scan::FontScanner::scan
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:35:21
  14: fount::scan::<impl fount::data::CollectionData>::add_fonts
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:124:9
  15: fount::scan::scan_path
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:216:9
  16: fount::data::CollectionData::family_id
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/data.rs:118:29
  17: fount::data::CollectionData::find_family
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/data.rs:183:31
  18: fount::data::CollectionData::setup_default
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/data.rs:195:18
  19: fount::library::LibraryBuilder::build
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/library.rs:54:9
  20: <fount::library::Library as core::default::Default>::default
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/library.rs:35:9
  21: parley::font::FontCache::new
             at /home/akhil/.cargo/git/checkouts/parley-eb2adff70a5b8ee8/c37477b/src/font.rs:84:47
  22: parley::font::FontContext::new
             at /home/akhil/.cargo/git/checkouts/parley-eb2adff70a5b8ee8/c37477b/src/font.rs:47:20
  23: piet_wgpu::text_layout::WgpuText::new
             at /home/akhil/.cargo/git/checkouts/piet-wgpu-913b036275d2afb6/2024fe8/src/text_layout.rs:53:39
  24: piet_wgpu::WgpuRenderer::new
             at /home/akhil/.cargo/git/checkouts/piet-wgpu-913b036275d2afb6/2024fe8/src/lib.rs:58:20
  25: druid_shell::backend::gtk::window::WindowBuilder::build::{{closure}}
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell/src/backend/gtk/window.rs:477:32
  26: <O as gtk::auto::widget::WidgetExt>::connect_realize::realize_trampoline
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.14.3/src/auto/widget.rs:4652:13
  27: g_closure_invoke
  28: <unknown>
  29: g_signal_emit_valist
  30: g_signal_emit
  31: gtk_widget_realize
  32: <O as gtk::auto::widget::WidgetExt>::realize
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.14.3/src/auto/widget.rs:2467:13
  33: druid_shell::backend::gtk::window::WindowBuilder::build
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell/src/backend/gtk/window.rs:825:9
  34: druid_shell::window::WindowBuilder::build
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell/src/window.rs:539:9
  35: druid::win_handler::AppState<T>::build_native_window
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid/src/win_handler.rs:951:9
  36: druid::app::WindowDesc<T>::build_native
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid/src/app.rs:634:9
  37: druid::app::AppLauncher<T>::launch
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid/src/app.rs:269:26
  38: lapce_ui::app::launch
             at lapce-ui/src/app.rs:155:5
  39: lapce::main
             at lapce-ui/src/bin/lapce.rs:6:5
  40: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  41: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  42: std::rt::lang_start::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  43: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
      std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
      std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
      std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
      std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  44: std::rt::lang_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  45: main
  46: <unknown>
  47: __libc_start_main
  48: _start

[2023-06-16][18:59:35][panic][ERROR] thread 'main' panicked at 'panic in a function that cannot unwind': library/core/src/panicking.rs:126
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_nounwind_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:96:14
   7: core::panicking::panic_nounwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:126:5
   8: core::panicking::panic_cannot_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:188:5
   9: <u16 as swash::internal::parse::FromBeData>::from_be_data_unchecked
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:450:5
      swash::internal::parse::FromBeData::from_be_data
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:424:27
      swash::internal::parse::Bytes::read
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/internal/parse.rs:55:9
      <swash::string::Chars as core::iter::traits::iterator::Iterator>::next
             at /home/akhil/.cargo/git/checkouts/swash-796ac9f81c34f1f7/1d9b8c7/src/string.rs:319:29
  10: core::iter::traits::iterator::Iterator::fold
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:2481:29
  11: core::iter::traits::iterator::Iterator::for_each
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:857:9
  12: <alloc::string::String as core::iter::traits::collect::Extend<char>>::extend
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:2086:9
  13: fount::scan::FontScanner::scan_font
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:63:13
  14: fount::scan::FontScanner::scan
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:35:21
  15: fount::scan::<impl fount::data::CollectionData>::add_fonts
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:124:9
  16: fount::scan::scan_path
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/scan.rs:216:9
  17: fount::data::CollectionData::family_id
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/data.rs:118:29
  18: fount::data::CollectionData::find_family
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/data.rs:183:31
  19: fount::data::CollectionData::setup_default
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/data.rs:195:18
  20: fount::library::LibraryBuilder::build
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/library.rs:54:9
  21: <fount::library::Library as core::default::Default>::default
             at /home/akhil/.cargo/git/checkouts/fount-fbafd550d73973f6/3bfdc68/src/library.rs:35:9
  22: parley::font::FontCache::new
             at /home/akhil/.cargo/git/checkouts/parley-eb2adff70a5b8ee8/c37477b/src/font.rs:84:47
  23: parley::font::FontContext::new
             at /home/akhil/.cargo/git/checkouts/parley-eb2adff70a5b8ee8/c37477b/src/font.rs:47:20
  24: piet_wgpu::text_layout::WgpuText::new
             at /home/akhil/.cargo/git/checkouts/piet-wgpu-913b036275d2afb6/2024fe8/src/text_layout.rs:53:39
  25: piet_wgpu::WgpuRenderer::new
             at /home/akhil/.cargo/git/checkouts/piet-wgpu-913b036275d2afb6/2024fe8/src/lib.rs:58:20
  26: druid_shell::backend::gtk::window::WindowBuilder::build::{{closure}}
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell/src/backend/gtk/window.rs:477:32
  27: <O as gtk::auto::widget::WidgetExt>::connect_realize::realize_trampoline
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.14.3/src/auto/widget.rs:4652:13
  28: g_closure_invoke
  29: <unknown>
  30: g_signal_emit_valist
  31: g_signal_emit
  32: gtk_widget_realize
  33: <O as gtk::auto::widget::WidgetExt>::realize
             at /home/akhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk-0.14.3/src/auto/widget.rs:2467:13
  34: druid_shell::backend::gtk::window::WindowBuilder::build
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell/src/backend/gtk/window.rs:825:9
  35: druid_shell::window::WindowBuilder::build
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid-shell/src/window.rs:539:9
  36: druid::win_handler::AppState<T>::build_native_window
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid/src/win_handler.rs:951:9
  37: druid::app::WindowDesc<T>::build_native
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid/src/app.rs:634:9
  38: druid::app::AppLauncher<T>::launch
             at /home/akhil/.cargo/git/checkouts/druid-f6980810fb848923/0b9c00f/druid/src/app.rs:269:26
  39: lapce_ui::app::launch
             at lapce-ui/src/app.rs:155:5
  40: lapce::main
             at lapce-ui/src/bin/lapce.rs:6:5
  41: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  43: std::rt::lang_start::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  44: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
      std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
      std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
      std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
      std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
      std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
      std::rt::lang_start_internal
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  45: std::rt::lang_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  46: main
  47: <unknown>
  48: __libc_start_main
  49: _start

thread caused non-unwinding panic. aborting.
```
It works in previous release: `1.68`

**Comment by MinusGix** [comment]
This is due to a bug in Swash https://github.com/dfrg/swash/issues/34  
However, we've fixed this in latest master - but of course latest master is missing various pieces of functionality due to the UI rewrite.  
  
I believe the answer, since we've changed the UI backend and so we aren't doing new releases with the druid backend, is that you should build it using 1.69/1.68.
