### ISSUE TITLE
Nightly build crashes on start on Ubuntu 23.04

### ISSUE THREAD

**Issue by i-ky** [lapce/lapce#2552]
## Lapce Version

```
$ ./lapce --version
Lapce nightly-ad9a8e1
```

## System information

Ubuntu 23.04

## Describe the bug

Crash on start:
```
$ RUST_BACKTRACE=full ./lapce --wait
2023-08-17T11:30:04.255756Z ERROR lapce_app::keypress: Failed to load from "/home/i-ky/.config/lapce-nightly/keymaps.toml": no keymaps
2023-08-17T11:30:04.296314Z ERROR wgpu_core::device: surface configuration failed: incompatible window kind    
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:316:9
stack backtrace:
   0:     0x55e9624d04b1 - std::backtrace_rs::backtrace::libunwind::trace::h782cc21a5acaf6cb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e9624d04b1 - std::backtrace_rs::backtrace::trace_unsynchronized::hc579eb24ab204515
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e9624d04b1 - std::sys_common::backtrace::_print_fmt::h7223525cfdbacda2
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55e9624d04b1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e96117aeff - core::fmt::rt::Argument::fmt::hb4f4a02b9bd9dd49
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/rt.rs:138:9
   5:     0x55e96117aeff - core::fmt::write::h6d54cd7c9e155ec5
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/fmt/mod.rs:1094:21
   6:     0x55e9624a3c46 - std::io::Write::write_fmt::h6a453a71c692f63b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/io/mod.rs:1713:15
   7:     0x55e9624d351f - std::sys_common::backtrace::_print::h1cbaa8b42678f928
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55e9624d351f - std::sys_common::backtrace::print::h4ddf81241a51b337
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55e9624d2cb0 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:269:22
  10:     0x55e9624d3daa - std::panicking::default_hook::h21f14afd59f7aef9
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:288:9
  11:     0x55e9624d3daa - std::panicking::rust_panic_with_hook::h45f66047b14c555c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:705:13
  12:     0x55e9624d37b2 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
  13:     0x55e9624d3716 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55e9624d3701 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
  15:     0x55e9610079f2 - core::panicking::panic_fmt::h54ec9d0e3180a83d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
  16:     0x55e962922548 - wgpu::backend::direct::Context::handle_error_fatal::hfbd54cfc88089b26
  17:     0x55e9629c8ef9 - <T as wgpu::context::DynContext>::surface_configure::hb84a7377c066b08e
  18:     0x55e962a28811 - wgpu::Surface::configure::hc8c2761e80be2a59
  19:     0x55e96134d2e0 - floem::renderer::Renderer::new::ha5b5c2821db3bc69
  20:     0x55e96158af2d - <floem::app_handle::AppHandle<V> as glazier::window::WinHandler>::connect::h1e01f36fdd5436e2
  21:     0x55e96144d92d - glazier::backend::x11::window::Window::connect::h4ade9c68a6fa70bf
  22:     0x55e96144bf5a - glazier::backend::x11::window::WindowBuilder::build::hae037475bc9c816b
  23:     0x55e961e88218 - lapce_app::app::AppData::create_windows::hb36d4c29f564baab
  24:     0x55e961e79a6c - lapce_app::app::launch::h6fbcd5b1239a1138
  25:     0x55e9610bb7d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcdebdad1188d7d8a
  26:     0x55e9610bbc49 - main
  27:     0x7f9b31623a90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  28:     0x7f9b31623b49 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  29:     0x55e9610bb37a - _start
  30:                0x0 - <unknown>
```

## Additional information

Version 0.2.8 launches fine.

**Comment by theotheroracle** [comment]
i think i get the same error, but it doesn't happen on start, it happens sometimes when i'm auto-completing something
```
[2023-08-26][13:21:28][wasi_experimental_http_wasmtime][DEBUG] got HTTP response, writing back to memory status=404 resp_headers={"server": "GitHub.com", "date": "Sat, 26 Aug 2023 13:21:29 GMT", "content-type": "text/plain; charset=utf-8", "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With", "cache-control": "no-cache", "strict-transport-security": "max-age=31536000; includeSubdomains; preload", "x-frame-options": "deny", "x-content-type-options": "nosniff", "x-xss-protection": "0", "referrer-policy": "no-referrer-when-downgrade", "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'", "content-length": "9", "x-github-request-id": "BE52:1531:17DB8A3:2090D20:64E9FC59"} body_len=9
[2023-08-26][13:21:28][lapce_data::keypress][ERROR] Failed to load from "/home/hive/.config/lapce-nightly/keymaps.toml": no keymaps
[2023-08-26][13:21:29][lapce_data::keypress][ERROR] Failed to load from "/home/hive/.config/lapce-nightly/keymaps.toml": no keymaps
[2023-08-26][13:25:12][panic][ERROR] thread 'main' panicked at 'byte index 14 is not a char boundary; it is inside '…' (bytes 12..15) of `run_dispose(…) (alias g_object_run_dispose) (as ObjectExt)`': /build/cargo-vendor-dir/parley-0.1.0/src/context.rs:160
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::str::slice_error_fail_rt
   8: core::str::slice_error_fail
   9: parley::context::RangedBuilder<B,T>::build
  10: <piet_wgpu::text_layout::WgpuTextLayoutBuilder as piet::text::TextLayoutBuilder>::build
  11: lapce_ui::completion::<impl lapce_ui::list::ListPaint<D> for lapce_data::completion::ScoredCompletionItem>::paint
  12: <lapce_ui::list::ListContent<T,D> as druid::widget::widget::Widget<lapce_data::list::ListData<T,D>>>::paint
  13: druid::core::WidgetPod<T,W>::paint_raw
  14: druid::contexts::PaintCtx::with_save
  15: druid::core::WidgetPod<T,W>::paint_raw
  16: druid::contexts::PaintCtx::with_save
  17: druid::core::WidgetPod<T,W>::paint_impl
  18: druid::core::WidgetPod<T,W>::paint_raw
  19: druid::contexts::PaintCtx::with_save
  20: druid::core::WidgetPod<T,W>::paint_impl
  21: <lapce_ui::completion::CompletionContainer as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint
  22: druid::core::WidgetPod<T,W>::paint_raw
  23: druid::contexts::PaintCtx::with_save
  24: druid::core::WidgetPod<T,W>::paint_impl
  25: <lapce_ui::tab::LapceTab as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint
  26: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint
  27: druid::core::WidgetPod<T,W>::paint_raw
  28: druid::contexts::PaintCtx::with_save
  29: druid::core::WidgetPod<T,W>::paint_impl
  30: <lapce_ui::window::LapceWindow as druid::widget::widget::Widget<lapce_data::data::LapceWindowData>>::paint
  31: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint
  32: druid::core::WidgetPod<T,W>::paint_raw
  33: druid::contexts::PaintCtx::with_child_ctx
  34: tracing::span::Span::in_scope
  35: druid::window::Window<T>::do_paint
  36: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::paint
  37: druid_shell::backend::gtk::window::WindowState::with_handler_and_dont_check_the_other_borrows
  38: <O as gtk::auto::gl_area::GLAreaExt>::connect_render::render_trampoline
  39: _gtk_marshal_BOOLEAN__OBJECTv
  40: _g_closure_invoke_va
  41: g_signal_emit_valist
  42: g_signal_emit
  43: gtk_gl_area_draw
  44: gtk_widget_draw_internal
  45: gtk_container_propagate_draw
  46: gtk_container_draw
  47: gtk_box_draw_contents
  48: gtk_css_custom_gadget_draw
  49: gtk_css_gadget_draw
  50: gtk_box_draw
  51: gtk_widget_draw_internal
  52: gtk_container_propagate_draw
  53: gtk_container_draw
  54: gtk_widget_draw_internal
  55: gtk_widget_render
  56: gtk_main_do_event
  57: _gdk_event_emit
  58: _gdk_window_process_updates_recurse_helper
  59: gdk_window_process_updates_internal
  60: gdk_window_process_updates_with_mode
  61: _g_closure_invoke_va
  62: g_signal_emit_valist
  63: g_signal_emit
  64: gdk_frame_clock_paint_idle
  65: gdk_threads_dispatch
  66: g_timeout_dispatch
  67: g_main_context_dispatch
  68: g_main_context_iterate.constprop.0
  69: g_main_context_iteration
  70: g_application_run
  71: <O as gio::application::ApplicationExtManual>::run
  72: druid_shell::backend::gtk::application::Application::run
  73: druid_shell::application::Application::run
  74: druid::app::AppLauncher<T>::launch
  75: lapce_ui::app::launch
  76: std::sys_common::backtrace::__rust_begin_short_backtrace
  77: std::rt::lang_start::{{closure}}
  78: std::rt::lang_start_internal
  79: main
  80: __libc_start_call_main
  81: __libc_start_main@@GLIBC_2.34
  82: _start
```
i'm on 0.2.8

**Comment by i-ky** [comment]
@theotheroracle, your issue seems different. Backtraces are very different. The fact that we both have "Failed to load from ..." errors does not mean anything, these errors seem non-fatal (your log goes on for four minutes after them). I would encourage you to file your issue separately.

**Comment by lilium724** [comment]
The nightly version currently doesn't support Wayland, which is ubuntu's default window system (see #2417 )
You can see in your backtrace it tries to use x11, which is probably why you're getting this incompatible window kind error
Support for Wayland has been added as an experimental feature (#2562), but for now it only seems to work in debug mode.

**Comment by i-ky** [comment]
@lilium724, thank you for the comment! I am going to close this issue as it is basically a duplicate of #2417.
