### ISSUE TITLE
Crash under Wayland

### ISSUE THREAD

**Issue by FairyTail2000** [lapce/lapce#2745]
## System information

- Manjaro / KDE / Wayland
- Linux rafael-captiva 6.1.55-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:13:56 UTC 2023 x86_64 GNU/Linux

## Describe the bug
LAPCE is not launching

## Additional information

- No Message when running without -w
- `RUST_BACKTRACE=full lapce -w`
- Backtrace:

> thread 'main' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.18.0/src/backend/direct.rs:778:18:
Error in Surface::configure: Validation Error

> Caused by:
    Parent device is lost

> stack backtrace:
   0:     0x55946cb94cef - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55946cb94cef - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55946cb94cef - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55946cb94cef - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55946b45bb0c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55946b45bb0c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55946cb5efcd - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55946cb973ae - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55946cb973ae - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55946cb96f93 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55946cb97fb3 - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x55946cb97fb3 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x55946cb97a82 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x55946cb979e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55946cb979d1 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x55946b287772 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x55946d0c69d2 - wgpu::backend::direct::Context::handle_error_fatal::h52a64206cecabd11
  17:     0x55946d179ff8 - <T as wgpu::context::DynContext>::surface_configure::hd021920a6aac8ef7
  18:     0x55946d1d4b91 - wgpu::Surface::configure::he9a5bba47b631956
  19:     0x55946b6ae972 - floem::window_handle::WindowHandle::new::h5284a4c0f129773c
  20:     0x55946b697eab - floem::app_handle::ApplicationHandle::new_window::h986b129b5e1acc7e
  21:     0x55946c3a6fa2 - lapce_app::app::launch::h9e09fe13007e6f4c
  22:     0x55946b36b123 - std::sys_common::backtrace::__rust_begin_short_backtrace::h64e25b46c58a96eb
  23:     0x55946b36b595 - main
  24:     0x7f62c9308cd0 - <unknown>
  25:     0x7f62c9308d8a - __libc_start_main
  26:     0x55946b36ac0a - _start
  27:                0x0 - <unknown>

I will check if problem is present under X11 and add a comment

**Comment by FairyTail2000** [comment]
Not crashing under X11

**Comment by MinusGix** [comment]
Does mimicking what #2742 does work?

**Comment by FairyTail2000** [comment]
Yes this works, however then the ui elements are switching pretty fast when changing tabs. They switch between project view and plugins for example for a second or two in quick succession
