### ISSUE TITLE
Crash scrolling/searching plugins

### ISSUE THREAD

**Issue by MFAshby** [lapce/lapce#2781]
## Lapce Version

0.3.0 _built from source_

## System information

```
martin@martin-pinebook ~/d/lapce ((v0.3.0))> uname -a
Linux martin-pinebook 6.5.3-1-MANJARO-ARM #1 SMP PREEMPT Fri Sep 15 12:28:28 UTC 2023 aarch64 GNU/Linux
```

## Describe the bug

Crash scrolling/searching plugins. Steps to reproduce: 
- Launch lapce
- Toggle plugin pane
- enter a search term e.g. 'java'

Expected behaviour: plugin list is filtered to 'java' plugin.

Actual behaviour: lapce exits immediately.

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
Ran with RUST_BACKTRACE=1 and -w flag, and got the following in the terminal:
```
martin@martin-pinebook ~/d/lapce ((v0.3.0)) [101]> RUST_BACKTRACE=1 target/release/lapce -w
2023-11-13T15:58:41.038722Z ERROR lapce_app::app: failed to fetch grammars: can't find support grammars
thread 'main' panicked at /home/martin/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4fbe6f4/tiny_skia/src/lib.rs:323:17:
unexpected image content: Color
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: floem_tiny_skia::TinySkiaRenderer::cache_glyph
   3: <floem_tiny_skia::TinySkiaRenderer as floem_renderer::Renderer>::draw_text
   4: floem::view::View::paint_main
   5: floem::view::View::paint_main
   6: floem::view::View::paint_main
   7: floem::view::View::paint_main
   8: <floem::views::scroll::Scroll<V> as floem::view::View>::paint
   9: floem::view::View::paint_main
  10: floem::view::View::paint_main
  11: floem::view::View::paint_main
  12: floem::view::View::paint_main
  13: floem::view::View::paint_main
  14: floem::view::View::paint_main
  15: floem::view::View::paint_main
  16: floem::view::View::paint_main
  17: floem::view::View::paint_main
  18: floem::view::View::paint_main
  19: floem::view::View::paint_main
  20: floem::view::View::paint_main
  21: <floem::views::stack::Stack<VT> as floem::view::View>::paint
  22: floem::view::View::paint_main
  23: floem::view::View::paint_main
  24: <floem::views::stack::Stack<VT> as floem::view::View>::paint
  25: floem::view::View::paint_main
  26: floem::window_handle::WindowHandle::paint
  27: floem::app_handle::ApplicationHandle::handle_window_event
  28: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  29: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::poll_events_with_timeout
  30: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand
  31: floem::app::Application::run
  32: lapce_app::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
- theories about what might be going wrong
I don't know enough to come up with a theory :(

- workarounds that you used
None so far

**Comment by stylefish** [comment]
with the current version on flathub i have this directly at startup, lapce directly closes after launch with this message.

**Comment by volkertb** [comment]
Just ran into the same issue with the latest nightly build for Linux on Clear Linux OS version 40580.

The application just vanished while I was scrolling through the list of available plugins.

Since I had started the application with the `-w` option, I also saw the `unexpected image content: Color` in the console when lapce crashed.
