### ISSUE TITLE
Crash after launch on Core i5-4300U (Win10)

### ISSUE THREAD

**Issue by MonkeyPilot** [lapce/lapce#2809]
## Lapce Version

0.3.0 / Nightly

## System information

Windows 10 Pro / 1909 / build 18363.592
Lenovo T440s / Intel Core i5-4300U (iGPU Haswell GT2)

## Describe the bug
Crash after launch, with an error:
```
ERROR wgpu_hal::auxil::dxgi::result Buffer creation failed: 0x887A0005
ERROR wgpu::backend::direct Handling wgpu errors as fatal by default
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.18.0\src\backend\direct.rs:3111:5:
wgpu error: Validation Error

Caused by:
    In Queue::write_buffer
    Parent device is lost
```
## Additional information
As I understand it, the Lapce is currently built with support for only DX12, which the processor i5-4300U supports only partially.
I tried switching the render to OpenGL, using a variable `WGPU_BACKEND=gl` (this could possibly solve the problem), but to no avail, Lapce is currently built only with DX12 support.

I also tried to switch the render to DX11, using `WGPU_UNSTABLE_DX11_BACKEND=1`, but the program gave such errors:
```
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.18.0\src\dx11\instance.rs:36:9:
not yet implemented
```

I really want to try your editor in action, but because of an annoying mistake, it is not yet possible. What is the difficulty of switch the render to OpenGL, slightly lowering the minimum requirements?

**Comment by MonkeyPilot** [comment]
A little wrong. DX11 support is still in the process, but OpenGL is supported and widely available on all platforms. This is not a 3D editor, but a source editor. There is no reason to set such high requirements to support the latest DX12.

**Comment by MonkeyPilot** [comment]
> DX11 is unsupported and that OpenGL (3.3+) receives only best effort support

A little wrong. DX11 support is still in the process, but OpenGL is supported and widely available on all platforms. This is not a 3D editor, but a source editor. There is no reason to set such high requirements to support the latest DX12.

**Comment by panekj** [comment]
> I am sure that the Lapce will work fine on OpenGL.

Lapce works with OpenGL fine, as long as the wgpu requirements are met.
