### ISSUE TITLE
Lapce flatpak fails on missing 'keymaps.toml' file error

### ISSUE THREAD

**Issue by aplatypus** [lapce/lapce#2837]
## Lapce Version

Lapce v0.3.1 (flatpak from flathub)

## System information

Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

## Describe the bug

* Installed latest flatpak from flathub
   'flatpak install flathub dev.lapce.lapce'
*  Run `lapce` from terminal
   `flatpak run dev.lapce.lapce`
* Nothing happened
*  Run `lapce` from terminal with wait option:
   `flatpak run dev.lapce.lapce --wait`
  * Gives some stack history (see below)
  * Failed on keymaps file:
    ` ERROR lapce_app::keypress: Failed to load from "/home/aplatypus/.var/app/dev.lapce.lapce/config/lapce-stable/keymaps.toml": no keymaps`

## Additional information

Looking in the runtime directory: 
* `~/.var/app/dev.lapce.lapce/config/lapce-stable/`
    * A keymaps file actually exists:
```
 $ ll  ~/.var/app/dev.lapce.lapce/config/lapce-stable/
total 12
-rw-r--r-- 1 aplatypus dev    0 Nov 12 02:09 keymaps.toml
drwxr-xr-x 3 aplatypus dev 4096 Dec  7 23:34 lapce.db/
-rw-r--r-- 1 aplatypus dev   0 Nov 12 02:09 settings.toml
```
   * However the file is empty -- It was probably created when `lapce` tried to opsn it.  
   * As an aside, I don't think the open should create a file if it wasn't found, _myself_.

Console output with `export RUST_BACKTRACE="full"`

```
$ flatpak run dev.lapce.lapce --wait
2023-12-07T13:32:01.275244Z ERROR lapce_app::keypress: Failed to load from "/home/platypus/.var/app/dev.lapce.lapce/config/lapce-stable/keymaps.toml": no keymaps
warning: queue 0x56366757b4b0 destroyed while proxies still attached:
  wl_registry@2 still attached
libEGL warning: egl: failed to create dri2 screen
warning: queue 0x5636680045e0 destroyed while proxies still attached:
  wl_registry@53 still attached
libEGL warning: egl: failed to create dri2 screen
warning: queue 0x563667a041a0 destroyed while proxies still attached:
  wl_registry@43 still attached
thread 'main' panicked at /run/build/lapce/cargo/vendor/wgpu-0.18.0/src/backend/direct.rs:778:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost

stack backtrace:
   0:     0x563664ce7b6f - <unknown>
   1:     0x56366377ff2c - <unknown>
   2:     0x563664cb11ad - <unknown>
   3:     0x563664cea20e - <unknown>
   4:     0x563664ce9df3 - <unknown>
   5:     0x563664ceadb9 - <unknown>
   6:     0x563664cea8ec - <unknown>
   7:     0x563664cea846 - <unknown>
   8:     0x563664cea831 - <unknown>
   9:     0x5636635b2614 - <unknown>
  10:     0x563665220392 - <unknown>
  11:     0x5636652d42de - <unknown>
  12:     0x56366532f8c1 - <unknown>
  13:     0x5636639f151d - <unknown>
  14:     0x5636639d74ac - <unknown>
  15:     0x5636644c8594 - <unknown>
  16:     0x56366368f123 - <unknown>
  17:     0x56366368f595 - <unknown>
  18:     0x7f9f7ae3b08a - <unknown>
  19:     0x7f9f7ae3b14b - __libc_start_main
  20:     0x56366368ec25 - <unknown>
  21:                0x0 - <unknown>
```

**Comment by allyring** [comment]
Having this issue with the stable Linux prebuilt binaries too. 64bit Debian 12, XFCE, running `lapce -w` gets the same "failed on keymaps file" error and the program seems to hang.

Tried adding my own 'keymaps.toml' file to the config using the defaults found in the repo ([keymaps-common](https://github.com/lapce/lapce/blob/master/defaults/keymaps-common.toml) concatenated with [keymaps-nonmacos](https://github.com/lapce/lapce/blob/master/defaults/keymaps-nonmacos.toml)), and that seems to get further; the `queries` folder got generated when i added the default (?) configs manually, but the window still hangs.

keymaps file can be found [here](https://github.com/lapce/lapce/files/13760412/keymaps.toml.txt).

**Comment by panekj** [comment]
Keymaps have nothing to do with lapce not launching, it's simply just a log.

**Comment by bone3ye** [comment]
Anyone make any headway on this? I'm having the same issue on Arch x86_64, with the package from the official repo after a system update. I believe Lapce got updated to 0.3.1 as well.

I tried adding a keymaps.toml file as @allyring did, and same result, it gets a bit further but still crashes:

```
$ lapce --version
Lapce v0.3.1

$ lapce --wait
thread 'main' panicked at /build/.cargo/git/checkouts/cosmic-text-fff8c4a78b1e732f/f7a2070/src/buffer_line.rs:192:41:
no default font found
stack backtrace:
   0:     0x55b21f27671f - <unknown>
   1:     0x55b21dcb6eac - <unknown>
   2:     0x55b21f23d03c - <unknown>
   3:     0x55b21f278eaf - <unknown>
   4:     0x55b21f278a93 - <unknown>
   5:     0x55b21f279a59 - <unknown>
   6:     0x55b21f27957c - <unknown>
   7:     0x55b21f2794d6 - <unknown>
   8:     0x55b21f2794c1 - <unknown>
   9:     0x55b21dadd634 - <unknown>
  10:     0x55b21daddc12 - <unknown>
  11:     0x55b21dcd8b07 - <unknown>
  12:     0x55b21dcd0356 - <unknown>
  13:     0x55b21dccfcca - <unknown>
  14:     0x55b21dccddb6 - <unknown>
  15:     0x55b21e85b587 - <unknown>
  16:     0x55b21dfe1175 - <unknown>
  17:     0x55b21e7cd516 - <unknown>
  18:     0x55b21e216847 - <unknown>
  19:     0x55b21ea6b919 - <unknown>
  20:     0x55b21df29290 - <unknown>
  21:     0x55b21df167c0 - <unknown>
  22:     0x55b21ea34b77 - <unknown>
  23:     0x55b21dbc07b3 - <unknown>
  24:     0x55b21dbc0c25 - <unknown>
  25:     0x7f0c16a45cd0 - <unknown>
  26:     0x7f0c16a45d8a - __libc_start_main
  27:     0x55b21dbc02a5 - <unknown>
  28:                0x0 - <unknown>


```

**Comment by volkertb** [comment]
Looks like this one is yet another duplicate of #2748.

**Comment by marcbrevoort-cyberhive** [comment]
Still occurs in 0.4.2. I seem to have a more useful backtrace:

```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.0.0/src/backend/wgpu_core.rs:786:18:
Error in Surface::configure: Validation Error

Caused by:
  Parent device is lost

stack backtrace:
   0:     0x5ec27afc7a8a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x5ec2798752cb - core::fmt::write::hc6043626647b98ea
   2:     0x5ec27af8ffd2 - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x5ec27afce2f9 - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x5ec27afcdae6 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x5ec27afcefa9 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   6:     0x5ec27afce6d2 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   7:     0x5ec27afce629 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   8:     0x5ec27afce616 - rust_begin_unwind
   9:     0x5ec279873442 - core::panicking::panic_fmt::ha02418e5cd774672
  10:     0x5ec27b4b22fc - wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_fatal::h584e6e82d79aa1d5
  11:     0x5ec27b5a9b9e - <T as wgpu::context::DynContext>::surface_configure::hd65a85644d0ea6e8
  12:     0x5ec27b61ad11 - wgpu::Surface::configure::hb248a553f38109ac
  13:     0x5ec279af1729 - floem::context::PaintState::new::h79ca7e860fdb6547
  14:     0x5ec279ada38f - floem::app_handle::ApplicationHandle::new_window::hf222d161b8ba5706
  15:     0x5ec27a7527ff - lapce_app::app::launch::h43f3880ea0f00c1c
  16:     0x5ec2797a0523 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb33c2da7fda02e4a
  17:     0x5ec2797a0901 - main
  18:     0x71fec6e29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19:     0x71fec6e29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  20:     0x5ec2797a002e - _start
  21:                0x0 - <unknown>
```
