### ISSUE TITLE
self must cover all 0-regions of other (complete stack trace)

### ISSUE THREAD

**Issue by planetoryd** [lapce/lapce#2876]
1d585b2bb5b149d1fbc9adc575316f74fe2252fc

I used the typst lsp plugin. 
[Kooha-2024-01-02-02-00-24.webm](https://github.com/lapce/lapce/assets/68096727/3a9c74fd-d85e-4234-b8c6-d6b3c694b834)

```rust
➜  notes git:(master) ✗ RUST_LOG=debug RUST_BACKTRACE=full lapce -w .
2024-01-01T17:24:55.290633Z ERROR lapce_app::keypress: Failed to load from "/home/phy/.config/lapce-debug/keymaps.toml": no keymaps
don't handle register capability for workspace/didChangeWatchedFiles
thread 'main' panicked at /home/phy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapce-xi-rope-0.3.2/src/multiset.rs:237:30:
self must cover all 0-regions of other
stack backtrace:
   0:     0x5612d8d0de9c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5612d8d0de9c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5612d8d0de9c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5612d8d0de9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5612d8d41ce0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x5612d8d41ce0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x5612d8d08e3f - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x5612d8d0dc84 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5612d8d0dc84 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5612d8d0f647 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x5612d8d0f3af - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x5612d8d0fac8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x5612d8d0f9ae - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x5612d8d0e366 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5612d8d0f712 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x5612d1f2eea5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x5612d1f2ee63 - core::panicking::panic_display::h68e6012a1c287ca5
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:178:5
  17:     0x5612d1f2ee63 - core::panicking::panic_str::h1ca8e3b0d2d70f80
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:152:5
  18:     0x5612d1f2ee63 - core::option::expect_failed::h1ae4bac6b7606972
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:1985:5
  19:     0x5612d6755b72 - core::option::Option<T>::expect::he186a7f01a7e6707
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:894:21
  20:     0x5612d6766987 - lapce_xi_rope::multiset::Subset::transform::h937ebf5cf174e876
                               at /home/phy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapce-xi-rope-0.3.2/src/multiset.rs:235:35
  21:     0x5612d6766b1c - lapce_xi_rope::multiset::Subset::transform_expand::h9ff3cfc428506713
                               at /home/phy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapce-xi-rope-0.3.2/src/multiset.rs:262:9
  22:     0x5612d639cf36 - lapce_core::buffer::Buffer::generate_edits::hdd1456627c340cdc
                               at /e/space/lapce/lapce-core/src/buffer/mod.rs:398:23
  23:     0x5612d639d3d0 - lapce_core::buffer::Buffer::mk_new_rev::he9e71ea2a9385a2d
                               at /e/space/lapce/lapce-core/src/buffer/mod.rs:431:21
  24:     0x5612d639c335 - lapce_core::buffer::Buffer::add_delta::h556384542bb3945c
                               at /e/space/lapce/lapce-core/src/buffer/mod.rs:328:13
  25:     0x5612d63ebcd2 - lapce_core::buffer::Buffer::edit::h164de05a153d363b
                               at /e/space/lapce/lapce-core/src/buffer/mod.rs:317:9
  26:     0x5612d63d08fc - lapce_core::editor::Editor::insert_new_line::hb6df9a8310697e41
                               at /e/space/lapce/lapce-core/src/editor.rs:403:13
  27:     0x5612d36c3989 - lapce_core::editor::Editor::do_edit::hbee93997a5982271
                               at /e/space/lapce/lapce-core/src/editor.rs:883:21
  28:     0x5612d27387fe - lapce_app::doc::Document<B>::do_edit::{{closure}}::h47c630bf484d0271
                               at /e/space/lapce/lapce-app/src/doc.rs:1890:17
  29:     0x5612d34d91ac - core::option::Option<T>::map::ha287e563d535ae84
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:1072:29
  30:     0x5612d2316221 - floem_reactive::signal::signal_update_value::hf6803fd3bdbb2efd
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/reactive/src/signal.rs:402:9
  31:     0x5612d227bf61 - floem_reactive::signal::RwSignal<T>::try_update::h2a96eb7ff13c70a2
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/reactive/src/signal.rs:68:9
  32:     0x5612d27385fa - lapce_app::doc::Document<B>::do_edit::hb73a5953ec0197e1
                               at /e/space/lapce/lapce-app/src/doc.rs:1887:22
  33:     0x5612d238d11c - lapce_app::editor::EditorData::run_edit_command::{{closure}}::hd8841c452e9b1db8
                               at /e/space/lapce/lapce-app/src/editor.rs:360:22
  34:     0x5612d2b50c1d - floem_reactive::effect::batch::hfc34d124d1ff2bb5
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/reactive/src/effect.rs:134:18
  35:     0x5612d243b45f - lapce_app::editor::EditorData::run_edit_command::hfcad8cdfbcda57fa
                               at /e/space/lapce/lapce-app/src/editor.rs:360:13
  36:     0x5612d2448e7f - <lapce_app::editor::EditorData as lapce_app::keypress::KeyPressFocus>::run_command::hafa902c6a5a15ac0
                               at /e/space/lapce/lapce-app/src/editor.rs:2568:55
  37:     0x5612d375bff8 - lapce_app::keypress::KeyPressData::run_command::h24af63384eebba30
                               at /e/space/lapce/lapce-app/src/keypress.rs:175:13
  38:     0x5612d376da54 - lapce_app::keypress::KeyPressData::key_down::hf48fade13c8a9781
                               at /e/space/lapce/lapce-app/src/keypress.rs:229:24
  39:     0x5612d319ff6e - lapce_app::main_split::MainSplitData::key_down::h014c5f42c49febe0
                               at /e/space/lapce/lapce-app/src/main_split.rs:347:33
  40:     0x5612d303cd80 - lapce_app::window_tab::WindowTabData::key_down::ha47a3d786d62bd94
                               at /e/space/lapce/lapce-app/src/window_tab.rs:1852:17
  41:     0x5612d3675f6c - lapce_app::window::WindowData::key_down::he046ec7ca41c426b
                               at /e/space/lapce/lapce-app/src/window.rs:319:13
  42:     0x5612d216baba - lapce_app::app::AppData::app_view::{{closure}}::h408b2aebccb2c1d2
                               at /e/space/lapce/lapce-app/src/app.rs:525:24
  43:     0x5612d6b823f3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h84e71b41c7adaf64
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
  44:     0x5612d6afc79d - floem::context::EventCx::unconditional_view_event::hfe9e30f042cdf4fb
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/context.rs:1072:34
  45:     0x5612d6afa5e2 - floem::context::EventCx::unconditional_view_event::hfe9e30f042cdf4fb
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/context.rs:816:28
  46:     0x5612d6afa5e2 - floem::context::EventCx::unconditional_view_event::hfe9e30f042cdf4fb
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/context.rs:816:28
  47:     0x5612d6afa5e2 - floem::context::EventCx::unconditional_view_event::hfe9e30f042cdf4fb
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/context.rs:816:28
  48:     0x5612d6c3fdd2 - floem::window_handle::WindowHandle::event::he277ce7abcd6a57c
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/window_handle.rs:187:38
  49:     0x5612d6c416f2 - floem::window_handle::WindowHandle::key_event::hb3c91f5c62c8e718
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/window_handle.rs:384:13
  50:     0x5612d6bdbdd1 - floem::app_handle::ApplicationHandle::handle_window_event::haca31b19228ede1d
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/app_handle.rs:177:17
  51:     0x5612d6b27c5b - floem::app::Application::run::{{closure}}::h533b0afa5a8d1fed
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/app.rs:140:21
  52:     0x5612d6b1433f - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::hfe52f31705fe758b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:294:13
  53:     0x5612d6b142e0 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::ha03ce58b2fc77c72
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:294:13
  54:     0x5612d6bc5d0e - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::single_iteration::ha530c454bc498418
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/platform_impl/linux/wayland/event_loop/mod.rs:461:13
  55:     0x5612d6bc9115 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::poll_events_with_timeout::h92db52b9d755ec79
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/platform_impl/linux/wayland/event_loop/mod.rs:323:9
  56:     0x5612d6bc49cd - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events::hcbe6125ea95e487d
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/platform_impl/linux/wayland/event_loop/mod.rs:237:13
  57:     0x5612d6bc4ee9 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand::hddb15118c9465508
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/platform_impl/linux/wayland/event_loop/mod.rs:201:19
  58:     0x5612d6a85125 - winit::platform_impl::platform::EventLoop<T>::run_on_demand::h3252b9a16442d4ba
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/platform_impl/linux/mod.rs:821:56
  59:     0x5612d6a8584a - winit::platform_impl::platform::EventLoop<T>::run::h707183f822e3c682
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/platform_impl/linux/mod.rs:814:9
  60:     0x5612d6c81078 - winit::event_loop::EventLoop<T>::run::h90866883cea74b18
                               at /home/phy/.cargo/git/checkouts/winit-1ee925e9c8358846/a75f412/src/event_loop.rs:249:9
  61:     0x5612d6b27a69 - floem::app::Application::run::h25892fe21e9871f4
                               at /home/phy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/92ba640/src/app.rs:133:17
  62:     0x5612d1f41905 - lapce_app::app::launch::h91c2689b89fba842
                               at /e/space/lapce/lapce-app/src/app.rs:3493:5
  63:     0x5612d1f30677 - lapce::main::hea895a607045c733
                               at /e/space/lapce/lapce-app/src/bin/lapce.rs:4:5
  64:     0x5612d1f3065b - core::ops::function::FnOnce::call_once::h98aed916d94b5046
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  65:     0x5612d1f305de - std::sys_common::backtrace::__rust_begin_short_backtrace::h9fb71da57f140949
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
  66:     0x5612d1f30711 - std::rt::lang_start::{{closure}}::h9162e5bd87fec16c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
  67:     0x5612d8d00167 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  68:     0x5612d8d00167 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  69:     0x5612d8d00167 - std::panicking::try::h3a52eefe24fe3c29
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  70:     0x5612d8d00167 - std::panic::catch_unwind::h24c28c23c02c3841
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  71:     0x5612d8d00167 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  72:     0x5612d8d00167 - std::panicking::try::do_call::ha21f52ba13158470
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  73:     0x5612d8d00167 - std::panicking::try::h5581346bf6aeb1f8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  74:     0x5612d8d00167 - std::panic::catch_unwind::h7919645a6b72e25b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  75:     0x5612d8d00167 - std::rt::lang_start_internal::h12de51168669836e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  76:     0x5612d1f306ea - std::rt::lang_start::h51e55567c02f959c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
  77:     0x5612d1f3069e - main
  78:     0x7ff2ffb6514a - __libc_start_call_main
  79:     0x7ff2ffb6520b - __libc_start_main_impl
  80:     0x5612d1f30505 - _start
  81:                0x0 - <unknown>
```

**Comment by planetoryd** [comment]
I also found that settings text box saves an extra "\n".

**Comment by TheQWERTYCodr** [comment]
can be triggered by typing some text and then spamming ctrl-a, ctrl-c, ctrl-v, and backspace in one of the text boxes in theme color settings. not sure exactly what triggers it - i've encountered the bug editing theme color settings normally. also occasionally triggers byte index n is out of bounds @ rope.rs:257:26.
