### ISSUE TITLE
Lapce not working at all on macOS

### ISSUE THREAD

**Issue by lukasbash** [lapce/lapce#2936]
## Lapce Version

v0.3.1

## System information

macOS Sonoma 14.3 (23D56)

## Describe the bug

Opening Lapce brings up its window. After this point regardless of the user action, the application does not perform any responses. Terminal does not load (cursor stuck forever). Cannot open a file. Cannot change UI preferences. Log file is empty. Checking for an update does not give any response.

It feels like its just stuck at some point.

## Additional information

Re-installing did not help.

**Comment by orangecoloured** [comment]
Same here. The editor launches fine, I open a project and then I can't navigate it, the folders do not expand and all the files are empty.

**Comment by nicolabeghin** [comment]
same here

**Comment by rehoehle** [comment]
I can't drag a file to the editor or say "open with". Then the editor is grey and i tried to open a TXT-File.

**Comment by BurnOutTrader** [comment]
same

**Comment by andrew-oxenburgh** [comment]
I had problems starting up on MacOS as well, which might have "just" been a UX issue.

If/when you get to the IDE window, in the title bar press the down arrow, NOT the search icon. This will allow you to open a folder.

![Screen Shot 2024-03-08 at 1 27 15 PM](https://github.com/lapce/lapce/assets/1282571/a663872f-223f-405f-a71d-618ef8a44d61)

**Comment by BurnOutTrader** [comment]
> I had problems starting up on MacOS as well, which might have "just" been a UX issue.

I cant seem to install any language support, so all my folders are empty and i cannot see files, except in git i can see changes to the files. I tried uninstalling rustup etc but no luck so i gave up for now.

**Comment by antti004** [comment]
Version 0.3.1
Same problem under Windows 11
But when using Portable version, then it is usable, until trying to connect ssh, then everything stops.

**Comment by asemarafa** [comment]
I encountered the same issue and managed to resolve it through a bit of debugging. Here's what I did:

First, I enabled full Rust backtraces to get more insight into the error by running:

```bash
export RUST_BACKTRACE=full
lapce -w
```

This resulted in the following error output, indicating a problem with loading keymaps and a panic related to the system locale configuration:

```bash
2024-04-13T07:04:23.484658Z ERROR lapce_app::keypress: Failed to load from "/Users/.../Library/Application Support/dev.lapce.Lapce-Stable/keymaps.toml": no keymaps
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/locale_config-0.3.0/src/macos.rs:16:76:
called `Result::unwrap()` on an `Err` value: NotWellFormed
stack backtrace:
   0:        0x1015c432c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4bff038afc05d0ab
   1:        0x1004f56b4 - core::fmt::write::he9fa43146d420946
   2:        0x10159f258 - std::io::Write::write_fmt::hf4fd30c8192b15d9
   3:        0x1015c8868 - std::sys_common::backtrace::print::h5d71f7b09493fc9b
   4:        0x1015c84b0 - std::panicking::default_hook::{{closure}}::hb75620628e95e648
   5:        0x1015c934c - std::panicking::rust_panic_with_hook::h81dc715fa5de32cf
   6:        0x1015c8ef0 - std::panicking::begin_panic_handler::{{closure}}::h26c73eb75670321f
   7:        0x1015c8e5c - std::sys_common::backtrace::__rust_end_short_backtrace::hef4773cf0f80485b
   8:        0x1015c8e50 - _rust_begin_unwind
   9:        0x101dcd6f0 - core::panicking::panic_fmt::h10bd3bfe5bb30d67
  10:        0x101dcda9c - core::result::unwrap_failed::h16d42dbc22454d03
  11:        0x10128630c - locale_config::macos::system_locale::h6064ec15009d2ea0
  12:        0x1012852a8 - std::sync::once::Once::call_once::{{closure}}::h99ad9bc7b268ae71
  13:        0x101e46ab8 - std::sys_common::once::queue::Once::call::he4b6301f8f9b0e9a
  14:        0x101286af4 - std::sync::once::Once::call_once::{{closure}}::h3d4400f39bccac80
  15:        0x101e46ab8 - std::sys_common::once::queue::Once::call::he4b6301f8f9b0e9a
  16:        0x1010596c4 - <lapce_proxy::dispatch::Dispatcher as lapce_rpc::proxy::ProxyHandler>::handle_notification::h597577b7c2668492
  17:        0x100f87824 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d5f1953dae0a659
  18:        0x100f87054 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4111dc76b1dd16ba
  19:        0x1015cc57c - std::sys::unix::thread::Thread::new::thread_start::h616a123cfe4994dc
  20:        0x19392af94 - __pthread_joiner_wake

```

The key part of the error was related to the system locale. To address this, I manually set the locale to `en_US.UTF-8` using the following commands:

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
lapce -w
```

After setting the locale variables manually, Lapce started without any errors. It seems the issue was indeed related to the system locale configuration, and manually specifying the locale as `en_US.UTF-8` provided a workaround.

**Comment by JimitSoni18** [comment]
not working for me as well:


```
❯ set -x LC_ALL=en_US.UTF-8
  set -x LANG=en_US.UTF-8
  lapce -w
set: LC_ALL=en_US.UTF-8: invalid variable name. See `help identifiers`
set: Did you mean `set LC_ALL en_US.UTF-8`?
(Type 'help set' for related documentation)
set: LANG=en_US.UTF-8: invalid variable name. See `help identifiers`
set: Did you mean `set LANG en_US.UTF-8`?
(Type 'help set' for related documentation)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
2024-07-28T08:14:28.767869Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/git/checkouts/floem-69eea0a757d1e3ee/a3dd759/tiny_skia/src/lib.rs:319:17
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   6: <floem::renderer::Renderer<W> as floem_renderer::Renderer>::draw_text
   7: lapce_app::terminal::view::TerminalView::paint_line_content
   8: <lapce_app::terminal::view::TerminalView as floem::view::Widget>::paint
   9: floem::context::PaintCx::paint_view
  10: floem::context::PaintCx::paint_view
  11: floem::view::Widget::paint
  12: floem::context::PaintCx::paint_view
  13: floem::view::Widget::paint
  14: floem::context::PaintCx::paint_view
  15: floem::view::Widget::paint
  16: floem::context::PaintCx::paint_view
  17: floem::context::PaintCx::paint_view
  18: floem::view::Widget::paint
  19: floem::context::PaintCx::paint_view
  20: floem::view::Widget::paint
  21: floem::context::PaintCx::paint_view
  22: floem::view::Widget::paint
  23: floem::context::PaintCx::paint_view
  24: floem::view::Widget::paint
  25: floem::context::PaintCx::paint_view
  26: floem::view::Widget::paint
  27: floem::context::PaintCx::paint_view
  28: floem::view::Widget::paint
  29: floem::context::PaintCx::paint_view
  30: floem::view::Widget::paint
  31: floem::context::PaintCx::paint_view
  32: floem::view::Widget::paint
  33: floem::context::PaintCx::paint_view
  34: floem::context::PaintCx::paint_view
  35: floem::view::Widget::paint
  36: floem::context::PaintCx::paint_view
  37: floem::view::Widget::paint
  38: floem::context::PaintCx::paint_view
  39: floem::window_handle::WindowHandle::paint
  40: floem::app::Application::run::{{closure}}
  41: lapce_app::app::launch
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
  43: main
  44: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  45: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  46: _start


~
❯ lapce --help
Usage: lapce [OPTIONS] [PATHS]...

Arguments:
  [PATHS]...  Paths to file(s) and/or folder(s) to open. When path is a file (that exists or not), it accepts `path:line:column` syntax to specify line and column at which it should open the file

Options:
  -n, --new                        Launch new window even if Lapce is already running
  -w, --wait                       Don't return instantly when opened in a terminal
      --plugin-path <PLUGIN_PATH>  Path(s) to plugins to load. This is primarily used for plugin development to make it easier to test changes to the plugin without needing to copy the plugin to the plugins directory. This will cause any plugin with the same author & name to not run
  -h, --help                       Print help
  -V, --version                    Print version

~
❯ set -x LC_ALL en_US.UTF-8
  set -x LANG en_US.UTF-8
  lapce -w
MESA-INTEL: warning: Haswell Vulkan support is incomplete
2024-07-28T08:15:21.317156Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/git/checkouts/floem-69eea0a757d1e3ee/a3dd759/tiny_skia/src/lib.rs:319:17
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   6: <floem::renderer::Renderer<W> as floem_renderer::Renderer>::draw_text
   7: lapce_app::terminal::view::TerminalView::paint_line_content
   8: <lapce_app::terminal::view::TerminalView as floem::view::Widget>::paint
   9: floem::context::PaintCx::paint_view
  10: floem::context::PaintCx::paint_view
  11: floem::view::Widget::paint
  12: floem::context::PaintCx::paint_view
  13: floem::view::Widget::paint
  14: floem::context::PaintCx::paint_view
  15: floem::view::Widget::paint
  16: floem::context::PaintCx::paint_view
  17: floem::context::PaintCx::paint_view
  18: floem::view::Widget::paint
  19: floem::context::PaintCx::paint_view
  20: floem::view::Widget::paint
  21: floem::context::PaintCx::paint_view
  22: floem::view::Widget::paint
  23: floem::context::PaintCx::paint_view
  24: floem::view::Widget::paint
  25: floem::context::PaintCx::paint_view
  26: floem::view::Widget::paint
  27: floem::context::PaintCx::paint_view
  28: floem::view::Widget::paint
  29: floem::context::PaintCx::paint_view
  30: floem::view::Widget::paint
  31: floem::context::PaintCx::paint_view
  32: floem::view::Widget::paint
  33: floem::context::PaintCx::paint_view
  34: floem::context::PaintCx::paint_view
  35: floem::view::Widget::paint
  36: floem::context::PaintCx::paint_view
  37: floem::view::Widget::paint
  38: floem::context::PaintCx::paint_view
  39: floem::window_handle::WindowHandle::paint
  40: floem::app::Application::run::{{closure}}
  41: lapce_app::app::launch
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
  43: main
  44: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  45: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  46: _start


~
```

**Comment by rehoehle** [comment]
The complete Editor is not usable on OSX. So how can that not be seen and fixed? That tells mich that this project here is dead.

**Comment by panekj** [comment]
> not working for me as well

What device are you using?

**Comment by JimitSoni18** [comment]
@panekj using thinkpad with void linux glibc

**Comment by panekj** [comment]
> @panekj using thinkpad with void linux glibc

Please create a new issue, this issue is macOS-only.
