### ISSUE TITLE
Window disapears after application start

### ISSUE THREAD

**Issue by kappilini** [lapce/lapce#2984]
## Lapce Version
0.3.1-1

## System information
OS: EndeavourOS
Kernel: 6.7.4-arch1-1
Desktop: Cinnamon 6.0.4
Windowmanager: Muffin (X11)
CPU: Intel(R) Core(TM) i7-4850HQ (8z
GPU 1: NVIDIA GeForce GT 750M Mac
Nvidia-Driver: nvidia-470xx-dkms
GPU 2: Intel Crystal Well Integrater

## Describe the bug
If lapce starts, the desktop wobbles where the lapce window appears after less than a second. 
Regardless on which point on the window I click, it disappears immediately. 
After restarting lapce, the window doesn't show at all.
I tested this behaviour  with the intel integrated GPU and the nvidia GPU via nvidia-prime but it remains the same.

**Comment by jt55401** [comment]
same.

Os: PopOS
Kernel: 6.6.10-76060610-generic
Windowmanager: GNOME Shell (X11)
CPU: Intel Core i9-13900K
GPU1: NVIDIA GeForce RTX 4090

**Comment by CarsonBurke** [comment]
same.

OS: Linux Mint 21.3
Kernel: 5.15.0-94-generic (64-bit)
Window manager: KDE Plasma 5.24.7 (X11)
CPU: Intel Core i5-9300H
GPU: NVIDIA GeForce GTX 1650/PCIe/SSE2

seems to be related to X11 maybe? <3

**Comment by CarsonBurke** [comment]
> same. Using latest flatpak version. Tested. Same for latest install from website too.
> 
> OS: Linux Mint 21.3 Kernel: 5.15.0-94-generic (64-bit) Window manager: KDE Plasma 5.24.7 (X11) CPU: Intel Core i5-9300H GPU: NVIDIA GeForce GTX 1650/PCIe/SSE2
> 
> seems to be related to X11 maybe? <3

Tested the same computer with Wayland, Gnome 45, 6.7.5-200 kernel. Works great. Hopefully that helps narrow it down

**Comment by wezm** [comment]
I am seeing this too (Arch Linux; X11; AwesomeWM; x86_64). The backtrace I get running a master (54e6682) debug build is captured below:

<details>
<summary>Backtrace</summary>
<pre>
2024-03-03T03:41:53.626760Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.0/src/buffer_line.rs:192:41
   0: lapce_app::app::panic_hook::{{closure}}
             at lapce-app/src/app.rs:3753:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
      core::panicking::panic_str
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
      core::option::expect_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
   7: core::option::Option<T>::expect
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:894:21
   8: floem_cosmic_text::buffer_line::TextLayoutLine::shape
             at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.0/src/buffer_line.rs:192:24
   9: floem_cosmic_text::buffer_line::TextLayoutLine::layout
             at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.0/src/buffer_line.rs:222:25
  10: floem_cosmic_text::buffer::TextLayout::shape_until
             at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.0/src/buffer.rs:395:26
  11: floem_cosmic_text::buffer::TextLayout::shape_until_scroll
             at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.0/src/buffer.rs:454:28
  12: floem_cosmic_text::buffer::TextLayout::set_text
             at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.0/src/buffer.rs:585:9
  13: lapce_app::window_tab::WindowTabData::new::{{closure}}
             at lapce-app/src/window_tab.rs:319:13
  14: floem_reactive::memo::create_memo::{{closure}}::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/memo.rs:85:29
  15: floem_reactive::signal::signal_with_untracked
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/signal.rs:401:5
  16: floem_reactive::signal::ReadSignal<T>::with_untracked
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/signal.rs:247:9
  17: floem_reactive::memo::create_memo::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/memo.rs:84:41
  18: <floem_reactive::effect::Effect<T,F> as floem_reactive::effect::EffectTrait>::run
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/effect.rs:235:25
  19: floem_reactive::effect::run_initial_effect::{{closure}}::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/effect.rs:154:13
  20: floem_reactive::scope::with_scope
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/scope.rs:129:18
  21: floem_reactive::effect::run_initial_effect::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/effect.rs:152:9
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  24: floem_reactive::effect::run_initial_effect
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/effect.rs:148:5
  25: floem_reactive::effect::create_effect
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/effect.rs:57:5
  26: floem_reactive::memo::create_memo
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/memo.rs:82:5
  27: floem_reactive::scope::Scope::create_memo::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/scope.rs:77:29
  28: floem_reactive::scope::with_scope
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/scope.rs:129:18
  29: floem_reactive::scope::Scope::create_memo
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/scope.rs:77:9
  30: lapce_app::window_tab::WindowTabData::new
             at lapce-app/src/window_tab.rs:308:30
  31: lapce_app::window::WindowData::new
             at lapce-app/src/window.rs:120:25
  32: lapce_app::app::AppData::app_view
             at lapce-app/src/app.rs:423:27
  33: lapce_app::app::AppData::create_windows::{{closure}}
             at lapce-app/src/app.rs:382:34
  34: floem::app::Application::window::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/src/app.rs:129:34
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  37: floem::window_handle::WindowHandle::new::{{closure}}
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/src/window_handle.rs:110:27
  38: floem_reactive::scope::with_scope
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/reactive/src/scope.rs:129:18
  39: floem::window_handle::WindowHandle::new
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/src/window_handle.rs:108:20
  40: floem::app_handle::ApplicationHandle::new_window
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/src/app_handle.rs:298:29
  41: floem::app::Application::window
             at /home/wmoore/.cargo/git/checkouts/floem-69eea0a757d1e3ee/341afd2/src/app.rs:127:9
  42: lapce_app::app::AppData::create_windows
             at lapce-app/src/app.rs:381:19
  43: lapce_app::app::launch
             at lapce-app/src/app.rs:3469:15
  44: lapce::main
             at lapce-app/src/bin/lapce.rs:4:5
  45: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  46: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  47: std::rt::lang_start::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  48: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  49: std::rt::lang_start
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  50: main
  51: <unknown>
  52: __libc_start_main
  53: _start
</pre>
</details>

That points at this this line in `floem-cosmic-text`:

https://github.com/lapce/cosmic-text/blob/c527aa1a1ceabfe191ace3b3d8474cd1a350777b/src/buffer_line.rs#L192

It seems that the default font families are currently hard-coded as follows:

https://github.com/lapce/cosmic-text/blob/163d8ef26e0eb1049f13e211071f7da5775cba1f/src/font/system.rs#L63-L65

Indeed after installing the following package Lapce appears: `ttf-dejavu`, `otf-fira-mono`, `otf-fira-sans`.

**Comment by mrsarm** [comment]
Got the same issue with latest Lapce v0.3.1, I tried installing Fira fonts but still the same.

I have Ubuntu 20.04 64 bits, Kernel 5.15.0-97-generic, GNOME 3.36.8, X11, NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q].

**Comment by mrsarm** [comment]
Oh installing the nightly build from Today (70cee3b) it does work, so looks like the error is fixed and only need to be released. Although still have similar issues drawing windows. As soon as I try to open a file, dialog boxes don't work:

![Lapce Open File Error 2024-03-08 11-22](https://github.com/lapce/lapce/assets/1608415/a3d38bc3-6cef-4a4f-b0ac-de3cab0023ca)

And this is the exception from the logs when I try to open the dialog:

```
2024-03-08T14:31:34.424573Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.0.1/src/abstractions/executor.rs:189:27
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: tokio::task::spawn::spawn_inner::panic_cold_display
   7: tokio::runtime::handle::Handle::current
   8: zbus::connection::builder::Builder::build_::{{closure}}
   9: ashpd::proxy::Proxy::connection::{{closure}}
  10: ashpd::desktop::file_chooser::FileChooserProxy::new::{{closure}}
  11: ashpd::desktop::file_chooser::OpenFileRequest::send::{{closure}}
  12: rfd::backend::xdg_desktop_portal::<impl rfd::backend::AsyncFilePickerDialogImpl for rfd::file_dialog::FileDialog>::pick_file_async::{{closure}}
  13: pollster::block_on
  14: rfd::file_dialog::FileDialog::pick_file
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  18: start_thread
  19: clone
```

**Comment by willypaz243** [comment]
I have a similar problem
I installed version 0.4.0 and nightly-43bdb12 on my machine and it closes as soon as I open it.
But version v0.2.8 does work, later versions no longer work.

These are the specifications of my system:
Os: Debian Trixie (Testing)
Kernel: 6.6.15-amd64
Windowmanager: Plasma 5.27.10 (X11)
CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 4.280GHz
GPU: NVIDIA GeForce RTX 3050 Ti Mobile
