### ISSUE TITLE
Getting very frequent panic errors, 5-7 per day 

### ISSUE THREAD

**Issue by ethereumdegen** [lapce/lapce#3027]
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 
0.2.8   (newer version gui is broken for me) 

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
Linux Mint 20 

## Describe the bug
Getting a panic.. here is log dump

```

[2024-02-27][18:18:00][panic][ERROR] thread 'main' panicked at 'byte index 17 is not a char boundary; it is inside '…' (bytes 15..18) of `apply_deferred(…) (alias apply_system_buffers)`': /github/home/.cargo/git/checkouts/parley-eb2adff70a5b8ee8/c37477b/src/context.rs:160
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: core::str::slice_error_fail_rt
   8: core::str::slice_error_fail
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/str/mod.rs:86:9
   9: <piet_wgpu::text_layout::WgpuTextLayoutBuilder as piet::text::TextLayoutBuilder>::build
  10: druid::contexts::PaintCtx::with_save
  11: <lapce_ui::completion::CompletionContainer as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint
  12: <lapce_ui::tab::LapceTab as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint
  13: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint
  14: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint
  15: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::paint
  16: <O as gtk::auto::gl_area::GLAreaExt>::connect_render::render_trampoline
  ```
  ```
  [2024-02-27][18:15:59][panic][ERROR] thread 'main' panicked at 'byte index 17 is not a char boundary; it is inside '…' (bytes 15..18) of `apply_deferred(…) (alias apply_system_buffers)`': /github/home/.cargo/git/checkouts/parley-eb2adff70a5b8ee8/c37477b/src/context.rs:160
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
      std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: core::str::slice_error_fail_rt
   8: core::str::slice_error_fail
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/str/mod.rs:86:9
   9: <piet_wgpu::text_layout::WgpuTextLayoutBuilder as piet::text::TextLayoutBuilder>::build
  10: druid::contexts::PaintCtx::with_save
  11: <lapce_ui::completion::CompletionContainer as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint
  12: <lapce_ui::tab::LapceTab as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint
  13: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint
  14: <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint
  15: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::paint
  16: <O as gtk::auto::gl_area::GLAreaExt>::connect_render::render_trampoline
  17: <unknown>
  18: <unknown>
  19: g_signal_emit_valist
  20: g_signal_emit
  21: <unknown>
  22: <unknown>
  23: gtk_container_propagate_draw
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: gtk_container_propagate_draw
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: gtk_main_do_event
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: g_signal_emit_valist
  42: g_signal_emit
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: g_main_context_dispatch
  47: <unknown>
  48: g_main_context_iteration
  49: g_application_run
  50: lapce_ui::app::launch
  51: std::sys_common::backtrace::__rust_begin_short_backtrace
  52: main
  53: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  54: _start

```

**Comment by panekj** [comment]
We don't have `parley` anymore since we don't use `druid` library
