### ISSUE TITLE
App crash on startup with custom theme applied (nightly build)

### ISSUE THREAD

**Issue by ash-sykes** [lapce/lapce#3121]
Not sure if this is the done thing (given its against a nightly build) but the last few nightlies have crashed on startup if you use a custom theme. Feel free to close if this is a known issue

## Lapce Version

Latest nightly (3ac55f9)

## System information

MacOS 14.4.1

## Describe the bug
App crashes on launch when a custom theme is configured

## Additional information

```
2024-03-28T10:03:30.616561Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://./lapce-app/src/config.rs:353:32
   0: backtrace::capture::Backtrace::new
   1: lapce_app::app::panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: lapce_app::config::LapceConfig::color
   8: floem_reactive::effect::create_updater::{{closure}}
   9: <floem_reactive::effect::UpdaterEffect<T,I,C,U> as floem_reactive::effect::EffectTrait>::run
  10: floem_reactive::effect::run_effect
  11: floem_reactive::signal::Signal::run_effects
  12: floem_reactive::signal::WriteSignal<T>::set
  13: lapce_app::window_tab::WindowTabData::reload_config
  14: <floem_reactive::effect::Effect<T,F> as floem_reactive::effect::EffectTrait>::run
  15: floem_reactive::effect::run_effect
  16: floem_reactive::signal::Signal::run_effects
  17: <floem_reactive::effect::Effect<T,F> as floem_reactive::effect::EffectTrait>::run
  18: floem_reactive::effect::run_effect
  19: floem_reactive::signal::Signal::run_effects
  20: floem_reactive::trigger::Trigger::notify
  21: floem::app_handle::ApplicationHandle::idle
  22: floem::app::Application::run::{{closure}}
  23: <floem_winit::platform_impl::platform::app_state::EventLoopHandler<T> as floem_winit::platform_impl::platform::app_state::EventHandler>::handle_user_events
  24: floem_winit::platform_impl::platform::observer::control_flow_end_handler
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: lapce_app::app::launch
  36: std::sys_common::backtrace::__rust_begin_short_backtrace
  37: _main

2024-03-28T10:03:30.625706Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/macos/app_state.rs:383:33
   0: backtrace::capture::Backtrace::new
   1: lapce_app::app::panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: floem_winit::platform_impl::platform::app_state::AppState::clear_callback
   9: lapce_app::app::launch
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: _main
```

**Comment by panekj** [comment]
Fixed via https://github.com/lapce/lapce/commit/9cd3bcc611637dc483bf0ad9b2e95e9fefc44ea7
