### ISSUE TITLE
Lapce crash on Linux Mint

### ISSUE THREAD

**Issue by AbstractiveNord** [lapce/lapce#3243]
## Lapce Version

Lapce v0.4.0 from `lapce --version`

## System information

Linux Mint 21.2

## Describe the bug
Just crash at start with no visible error indication, only screen blink.

## Additional information

`lapce --wait`

```
2024-05-05T19:36:29.629797Z ERROR floem_winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}    
2024-05-05T19:36:29.630092Z ERROR floem_winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}    
2024-05-05T19:36:29.630125Z ERROR floem_winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}    
2024-05-05T19:36:30.139011Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/registry/src/index.crates.io-*random*/floem-winit-0.29.4/src/platform_impl/linux/x11/window.rs:1084:14
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/result.rs:1649:5
   7: floem::window_handle::WindowHandle::process_update_messages
   8: floem::window_handle::WindowHandle::process_update_no_paint
   9: floem::app_handle::ApplicationHandle::idle
  10: lapce_app::app::launch
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  14: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  15: _start

```

That's may be related to 2 GPUs systems, like laptops.

**Comment by Sanghalap** [comment]
Same problem here

**Comment by gentlecolts** [comment]
lapce 0.4.0-2 installed from official repositories, manjaro kernel 6.6.32-1, kde plasma 6.0.5, on a laptop with multiple gpus as well.  Clicking on lapce produces no window and immediately crashes for me.  Running from command line produces the following not so helpful results:

```
$ lapce --wait
2024-06-14T13:51:09.113631Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:724:18
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_main
  15: <unknown>
```
```
$ lapce
Shutting down logging worker timed out after 1s.
```

**Comment by panekj** [comment]
@gentlecolts this is completely different issue, probably failing to use specific backend or some kind of issue with GPU selection

**Comment by sonulohani** [comment]
I am also facing the same crash.
