### ISSUE TITLE
`lapse` executable immediately quits on execution in Clear Linux OS, without showing any errors or warnings

### ISSUE THREAD

**Issue by volkertb** [lapce/lapce#3285]
## Lapce Version

I tried this (with the same result) with both release [v0.4.0](https://github.com/lapce/lapce/releases/tag/v0.4.0) and nightly 9d016fe (the [latest nightly](https://github.com/lapce/lapce/releases/tag/nightly) as of 2024-05-26).

## System information
[
Clear Linux OS](https://www.clearlinux.org/), version 41760 (rolling release distro)

Kernel: 
```
Linux [HOSTNAME REDACTED] 6.9.1-1436.native #1 SMP Fri May 17 12:06:23 PDT 2024 x86_64 GNU/Linux
```

The system that I tried this on has an Intel i5 Sandy Bridge CPU.

## Describe the bug

When I try to start the extracted `lapce` binary from the command line, the application immediately quits, without showing any errors or warnings on the console. Also, it doesn't create a log file or anything. And it doesn't even exit with an error code.

Steps to reproduce:

```
tar -zxvf lapce-linux-amd64.tar.gz
cd Lapce
./lapce
echo $?
```

The result of the echo command is `0`, which means that the `lapce` executable didn't yield an error code either.

## Additional information

When an application fails to start, it should at the very least show an explanatory error message on the console to provide some hints as to what's going wrong. Applications should never fail silently on errors.

**Comment by panekj** [comment]
run `./lapce -w`

**Comment by volkertb** [comment]
Thanks. I would really recommend that at least some error be thrown with a non-0 exit code, instead of failing silently. At the very least, perhaps give a general `An error occurred, run with -w for details`, and then exit with code 1 or -1 or something.

Anyway, here is the output of `./lapce -w`:

```text
2024-05-28T19:46:31.034110Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.1/src/buffer_line.rs:192:41
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:785:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   5: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   6: core::panicking::panic_display
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:196:5
      core::panicking::panic_str
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:171:5
      core::option::expect_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/option.rs:1988:5
   7: floem_cosmic_text::buffer_line::TextLayoutLine::layout
   8: floem_cosmic_text::buffer::TextLayout::shape_until
   9: floem_cosmic_text::buffer::TextLayout::set_text
  10: floem_cosmic_text::buffer::TextLayout::new
  11: <floem_reactive::effect::Effect<T,F> as floem_reactive::effect::EffectTrait>::run
  12: floem_reactive::effect::run_initial_effect
  13: lapce_app::window_tab::WindowTabData::new
  14: lapce_app::app::AppData::app_view
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: floem::app_handle::ApplicationHandle::new_window
  17: lapce_app::app::launch
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: main
  20: __libc_start_call_main
             at /builddir/build/BUILD/glibc-2.39/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21: __libc_start_main_impl
             at /builddir/build/BUILD/glibc-2.39/csu/../csu/libc-start.c:360:3
  22: _start
```

I hope this helps. Thanks!

**Comment by e2dk4r** [comment]
```
$ ./lapce --version
Lapce nightly-f2355aa
```

On my gentoo system without `[media-fonts/freefont](https://savannah.nongnu.org/projects/freefont/)` installed, `lapce` gives below error. Same issue with #3235. I think [floem_cosmic_text](https://github.com/lapce/floem) or [cosmic-text](https://github.com/pop-os/cosmic-text) specifies `FreeMono` or `FreeSerif` for their font selection hardcoded (in executable). This causes systems without `freefont` installed, failing to start `lapce`.
 
```
$ ./lapce -w 
2024-05-31T10:03:41.560731Z ERROR lapce_app::panic_hook: thread main panicked at <unknown> | file://.//cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-cosmic-text-0.7.2/src/buffer_line.rs:192:41
   0: lapce_app::app::panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   6: core::panicking::panic_display
   7: core::panicking::panic_str
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:172:5
      core::option::expect_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:1995:5
   8: floem_cosmic_text::buffer_line::TextLayoutLine::layout
   9: floem_cosmic_text::buffer::TextLayout::shape_until
  10: floem_cosmic_text::buffer::TextLayout::set_text
  11: floem_cosmic_text::buffer::TextLayout::new
  12: <floem_reactive::effect::Effect<T,F> as floem_reactive::effect::EffectTrait>::run
  13: floem_reactive::effect::run_initial_effect
  14: lapce_app::window_tab::WindowTabData::new
  15: lapce_app::app::AppData::app_view
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
  17: floem_reactive::scope::with_scope
  18: floem::app_handle::ApplicationHandle::new_window
  19: lapce_app::app::launch
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: main
  22: <unknown>
  23: __libc_start_main
  24: _start
```

You can install the font with your package manager or manually.
```
# Fetch freefont
cd /tmp
wget https://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip
tar xf freefont-ttf-20120503.zip
rm freefont-ttf-20120503.zip

# Copy to your fonts directory
mkdir -p $HOME/.fonts
mv /tmp/freefont-20120503/*.ttf $HOME/.fonts/

# Update font cache of your system
fc-cache -vf $HOME/.fonts/

# Open lapce
./lapce
```
