### ISSUE TITLE
Lapce Xi Rope panic on assertion

### ISSUE THREAD

**Issue by jrmoulton** [lapce/lapce#3321]
## Lapce Version

Latest Nightly

## System information

MacOS 10.14

## Describe the bug

Not entirely sure yet. I'll continue to update the issue as I find more. 

Panic on assertion

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

```
2024-06-11T23:08:42.296426Z ERROR lapce_app::panic_hook: thread main panicked at assertion failed: self.start >= amount | file://.//Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapce-xi-rope-0.3.2/src/interval.rs:135:9
   0: backtrace::backtrace::libunwind::trace
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/backtrace/libunwind.rs:105:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/backtrace/mod.rs:66:5
      backtrace::backtrace::trace
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/backtrace/mod.rs:53:14
      backtrace::capture::Backtrace::create
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/capture.rs:193:9
      backtrace::capture::Backtrace::new
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.71/src/capture.rs:158:22
   1: lapce_app::app::logging::panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/alloc/src/boxed.rs:2036:9
      std::panicking::rust_panic_with_hook
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/panicking.rs:799:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/panicking.rs:656:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/sys_common/backtrace.rs:171:18
   5: rust_begin_unwind
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/panicking.rs:652:5
   6: core::panicking::panic_fmt
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/core/src/panicking.rs:72:14
   7: core::panicking::panic
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/core/src/panicking.rs:141:5
   8: lapce_xi_rope::interval::Interval::translate_neg
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapce-xi-rope-0.3.2/src/interval.rs:135:9
   9: lapce_xi_rope::spans::SpansBuilder<T>::add_span
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapce-xi-rope-0.3.2/src/spans.rs:135:41
  10: lapce_xi_rope::spans::<impl lapce_xi_rope::tree::Node<lapce_xi_rope::spans::SpansInfo<T>>>::merge
  11: lapce_app::doc::Doc::get_semantic_styles::{{closure}}::{{closure}}
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  13: std::panicking::try::do_call
  14: ___rust_try
  15: std::panicking::try
  16: rayon_core::registry::Registry::catch_unwind
  17: rayon_core::spawn::spawn_job::{{closure}}
  18: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  19: rayon_core::job::JobRef::execute
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/job.rs:64:9
      rayon_core::registry::WorkerThread::execute
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:860:13
      rayon_core::registry::WorkerThread::wait_until_cold
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:794:26
  20: rayon_core::registry::WorkerThread::wait_until
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:769:13
      rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:818:9
      rayon_core::registry::main_loop
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:923:5
      rayon_core::registry::ThreadBuilder::run
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:53:18
  21: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /Users/jaredmoulton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.1/src/registry.rs:98:20
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/sys_common/backtrace.rs:155:18
  22: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/thread/mod.rs:542:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/panicking.rs:559:40
      std::panicking::try
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/panicking.rs:523:19
      std::panic::catch_unwind
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/panic.rs:149:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/thread/mod.rs:541:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/core/src/ops/function.rs:250:5
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/alloc/src/boxed.rs:2022:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/alloc/src/boxed.rs:2022:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/7f2fc33da6633f5a764ddc263c769b6b2873d167/library/std/src/sys/pal/unix/thread.rs:108:17
  24: __pthread_joiner_wake
  
  ```

**Comment by panekj** [comment]
What file it happens on?

**Comment by jrmoulton** [comment]
Any/all. I think it's related to using Multiline Error lens

**Comment by MinusGix** [comment]
This bug has existed before multiline error lens. See #2677, and I feel like I had another statement of it (maybe on discord) with a bit more thought... unsure where. Anyway, I presume it has something to do with our handling of semantic highlighting.
