### ISSUE TITLE
LSP on remote SSH Server via Proxy doesn't work

### ISSUE THREAD

**Issue by rotkohlsuppe** [lapce/lapce#3479]
## Lapce Version

0.4.2 (1)

## System information

MacOS 10.14.6 (Intel)
MacOS 13.4.1 (M1)

## Describe the bug
I have tested on two machines.
Installed the plugins in lapce. Installed the language servers and made sure they work locally. Then I open a remote project on a Ubuntu Server LTS 20 and on a local Linux Server. Made sure the proxy is running (htop / ps aux). None of the LSP features work on the remote machine. Did I get this wrong and this feature is not supported?

## Additional information

I see the vue Server is running on the remote machine. But even vue files don't show any signs of LSP features.

The stderr.log:
```
thread '<unnamed>' panicked at lapce-proxy/src/plugin/psp.rs:547:36:
called `Result::unwrap()` on an `Err` value: RecvError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at lapce-proxy/src/plugin/psp.rs:547:36:
called `Result::unwrap()` on an `Err` value: RecvError
thread '<unnamed>' panicked at lapce-proxy/src/plugin/psp.rs:547:36:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by jm-observer** [comment]
This feature maybe needs to be revalidated and tested.

**Comment by rotkohlsuppe** [comment]
Thank you for your reply! I think this is a killer feature and makes this editor outstanding. Looking forward for a solution.

**Comment by dzhou121** [comment]
It would be the vue plugin I would guess. Have you tried if the plugin is working fine locally?

**Comment by rotkohlsuppe** [comment]
True, after disabling the error message didn't come back. But unfortunately it didn't solve the problem.

On the other hand I have megabytes of one error message in the log file. But this doesn't seems to be related to the issue.
```
2024-09-10T00:00:12.072229Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72473    
2024-09-10T00:00:12.568286Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72474    
2024-09-10T00:00:13.069173Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72475    
2024-09-10T00:00:13.615297Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72476    
2024-09-10T00:00:14.091719Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72477    
2024-09-10T00:00:14.603217Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72478    
2024-09-10T00:00:15.106010Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72479    
2024-09-10T00:00:15.606011Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72480    
2024-09-10T00:00:16.108787Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72481    
2024-09-10T00:00:16.609945Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72482    
2024-09-10T00:00:17.110930Z  INFO wgpu_core::device::resource: Device::maintain: waiting for submission index 72483    
```
Every half a second a new entry is created.
