### ISSUE TITLE
Crash on `undo`

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#376]
Steps to reproduce:
 - delete all contents of a file
 - press tab
 - press `ctrl-z`

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'byte index 1 is out of bounds of ``', library\core\src\str\mod.rs:107:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\/library\core\src\panicking.rs:143
   2: core::str::slice_error_fail_rt
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\/library\core\src\str\mod.rs:107
   3: core::ops::function::FnOnce::call_once<never$ (*)(str,usize,usize),tuple$<str,usize,usize> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\/library\core\src\ops\function.rs:227
   4: core::intrinsics::const_eval_select<tuple$<str,usize,usize>,never$ (*)(str,usize,usize),never$ (*)(str,usize,usize),never$>
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\/library\core\src\intrinsics.rs:2366
   5: core::str::slice_error_fail
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\/library\core\src\str\mod.rs:86
   6: core::str::traits::impl$9::index
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\core\src\str\traits.rs:370
   7: core::str::traits::impl$4::index<core::ops::range::RangeFrom<usize> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\core\src\str\traits.rs:65
   8: alloc::string::impl$27::index
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\alloc\src\string.rs:2249
   9: xi_rope::tree::Cursor<xi_rope::rope::RopeInfo>::next_codepoint
             at C:\Users\bugad\.cargo\git\checkouts\xi-editor-32bce836970a2e41\5578c72\rust\rope\src\rope.rs:663
  10: lapce_data::buffer::WordCursor::next_code_boundary
             at .\lapce-data\src\buffer.rs:2148
  11: lapce_data::buffer::Buffer::next_code_boundary
             at .\lapce-data\src\buffer.rs:1607
  12: lapce_data::editor::LapceEditorBufferData::update_completion
             at .\lapce-data\src\editor.rs:695
  13: lapce_data::editor::impl$1::run_command
             at .\lapce-data\src\editor.rs:1928
  14: lapce_data::keypress::KeyPressData::run_command<lapce_data::editor::LapceEditorBufferData>
             at .\lapce-data\src\keypress\mod.rs:228
  15: lapce_data::keypress::KeyPressData::key_down<lapce_data::editor::LapceEditorBufferData>
             at .\lapce-data\src\keypress\mod.rs:331
  16: lapce_ui::editor::view::impl$1::event
             at .\lapce-ui\src\editor\view.rs:439
  17: druid::widget::widget::impl$1::event<lapce_data::data::LapceTabData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\widget.rs:268
  18: druid::core::WidgetPod<lapce_data::data::LapceTabData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<lapce_data::data::LapceTabData> >,alloc::alloc::Global> >::event<lapce_data::data::LapceTabData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\core.rs:856
  19: lapce_ui::editor::tab::impl$1::event
             at .\lapce-ui\src\editor\tab.rs:360
  20: druid::widget::widget::impl$1::event<lapce_data::data::LapceTabData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\widget.rs:268
  21: druid::core::WidgetPod<lapce_data::data::LapceTabData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<lapce_data::data::LapceTabData> >,alloc::alloc::Global> >::event<lapce_data::data::LapceTabData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\core.rs:856
  22: lapce_ui::split::impl$3::event
             at .\lapce-ui\src\split.rs:933
  23: druid::widget::widget::impl$1::event<lapce_data::data::LapceTabData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\widget.rs:268
  24: druid::core::WidgetPod<lapce_data::data::LapceTabData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<lapce_data::data::LapceTabData> >,alloc::alloc::Global> >::event<lapce_data::data::LapceTabData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\core.rs:856
  25: lapce_ui::tab::impl$1::event
             at .\lapce-ui\src\tab.rs:998
  26: druid::widget::lens_wrap::impl$1::event::closure$0<lapce_data::data::LapceWindowData,lapce_data::data::LapceTabData,lapce_data::data::LapceTabLens,lapce_ui::tab::LapceTabNew>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\lens_wrap.rs:105
  27: lapce_data::data::impl$8::with_mut<tuple$<>,druid::widget::lens_wrap::impl$1::event::closure_env$0<lapce_data::data::LapceWindowData,lapce_data::data::LapceTabData,lapce_data::data::LapceTabLens,lapce_ui::tab::LapceTabNew> >
             at .\lapce-data\src\data.rs:1677
  28: druid::widget::lens_wrap::impl$1::event<lapce_data::data::LapceWindowData,lapce_data::data::LapceTabData,lapce_data::data::LapceTabLens,lapce_ui::tab::LapceTabNew>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\lens_wrap.rs:104
  29: druid::widget::widget::impl$1::event<lapce_data::data::LapceWindowData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\widget.rs:268
  30: druid::core::WidgetPod<lapce_data::data::LapceWindowData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<lapce_data::data::LapceWindowData> >,alloc::alloc::Global> >::event<lapce_data::data::LapceWindowData,alloc::boxed::Box<dyn$<druid::widget::widge
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\core.rs:856
  31: lapce_ui::window::impl$1::event
             at .\lapce-ui\src\window.rs:376
  32: druid::widget::lens_wrap::impl$1::event::closure$0<lapce_data::data::LapceData,lapce_data::data::LapceWindowData,lapce_data::data::LapceWindowLens,lapce_ui::window::LapceWindowNew>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\lens_wrap.rs:105
  33: lapce_data::data::impl$9::with_mut<tuple$<>,druid::widget::lens_wrap::impl$1::event::closure_env$0<lapce_data::data::LapceData,lapce_data::data::LapceWindowData,lapce_data::data::LapceWindowLens,lapce_ui::window::LapceWindowNew> >
             at .\lapce-data\src\data.rs:1705
  34: druid::widget::lens_wrap::impl$1::event<lapce_data::data::LapceData,lapce_data::data::LapceWindowData,lapce_data::data::LapceWindowLens,lapce_ui::window::LapceWindowNew>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\lens_wrap.rs:104
  35: druid::widget::widget::impl$1::event<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\widget\widget.rs:268
  36: druid::core::WidgetPod<lapce_data::data::LapceData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<lapce_data::data::LapceData> >,alloc::alloc::Global> >::event<lapce_data::data::LapceData,alloc::boxed::Box<dyn$<druid::widget::widget::Widget<lapce_da
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\core.rs:856
  37: druid::window::Window<lapce_data::data::LapceData>::event<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\window.rs:330
  38: druid::win_handler::InnerAppState<lapce_data::data::LapceData>::do_window_event<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\win_handler.rs:437
  39: druid::win_handler::AppState<lapce_data::data::LapceData>::do_window_event<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\win_handler.rs:692
  40: druid::win_handler::AppState<lapce_data::data::LapceData>::do_winit_window_event<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\win_handler.rs:681
  41: druid::app::impl$1::launch::closure$1<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\app.rs:493
  42: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum$<druid_shell::window::WinitEvent>,druid::app::impl$1::launch::closure_env$1<lapce_data::data::LapceData> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:225
  43: alloc::boxed::impl$45::call_mut<tuple$<enum$<winit::event::Event<enum$<druid_shell::window::WinitEvent> > >,ref_mut$<enum$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum$<winit::event::Event<enum$<druid_shell::window::Wini
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\alloc\src\boxed.rs:1868
  44: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop\runner.rs:247
  45: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum$<druid_shell::window::WinitEvent> > >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\core\src\panic\unwind_safe.rs:271
  46: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum$<druid_shell::window::WinitEvent> > >,tuple$<> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\std\src\panicking.rs:492
  47: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$6<enum$<druid_shell::window::WinitEvent> > >,tuple$<> >
  48: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum$<druid_shell::window::WinitEvent> > > >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\std\src\panicking.rs:456
  49: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum$<druid_shell::window::WinitEvent> > >,tuple$<> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\std\src\panic.rs:137
  50: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::catch_unwind<enum$<druid_shell::window::WinitEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::clos
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop\runner.rs:152
  51: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::call_event_handler<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop\runner.rs:239
  52: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::send_event<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop\runner.rs:220
  53: winit::platform_impl::platform::event_loop::WindowData<enum$<druid_shell::window::WinitEvent> >::send_event<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:103
  54: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$2<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:927
  55: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$2<enum$<druid_shell::window::WinitEvent> >,tuple$<> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\core\src\ops\function.rs:227
  56: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$2<enum$<druid_shell::window::WinitEvent> > >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\core\src\panic\unwind_safe.rs:271
  57: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$2<enum$<druid_shell::window::WinitEvent> > >,tuple$<> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\std\src\panicking.rs:492
  58: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$6<enum$<druid_shell::window::WinitEvent> > >,tuple$<> >
  59: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$2<enum$<druid_shell::window::WinitEvent> > > >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\std\src\panicking.rs:456
  60: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$2<enum$<druid_shell::window::WinitEvent> > >,tuple$<> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\std\src\panic.rs:137
  61: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<druid_shell::window::WinitEvent> >::catch_unwind<enum$<druid_shell::window::WinitEvent>,tuple$<>,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_en
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop\runner.rs:152
  62: winit::platform_impl::platform::event_loop::public_window_callback_inner<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:937
  63: winit::platform_impl::platform::event_loop::public_window_callback<enum$<druid_shell::window::WinitEvent> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:875
  64: CallWindowProcW
  65: CallWindowProcW
  66: <unknown>
  67: CallWindowProcW
  68: DispatchMessageW
  69: winit::platform_impl::platform::event_loop::EventLoop<enum$<druid_shell::window::WinitEvent> >::run_return<enum$<druid_shell::window::WinitEvent>,druid::app::impl$1::launch::closure_env$1<lapce_data::data::LapceData> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:240
  70: winit::platform_impl::platform::event_loop::EventLoop<enum$<druid_shell::window::WinitEvent> >::run<enum$<druid_shell::window::WinitEvent>,druid::app::impl$1::launch::closure_env$1<lapce_data::data::LapceData> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\platform_impl\windows\event_loop.rs:210
  71: winit::event_loop::EventLoop<enum$<druid_shell::window::WinitEvent> >::run<enum$<druid_shell::window::WinitEvent>,druid::app::impl$1::launch::closure_env$1<lapce_data::data::LapceData> >
             at C:\Users\bugad\.cargo\git\checkouts\winit-1ee925e9c8358846\75e9569\src\event_loop.rs:179
  72: druid::app::AppLauncher<lapce_data::data::LapceData>::launch<lapce_data::data::LapceData>
             at C:\Users\bugad\.cargo\git\checkouts\druid-f6980810fb848923\ce62050\druid\src\app.rs:284
  73: lapce_ui::app::launch
             at .\lapce-ui\src\app.rs:52
  74: lapce::main
             at .\lapce-ui\src\bin\lapce.rs:6
  75: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941\library\core\src\ops\function.rs:227
```

</details>

**Comment by bugadani** [comment]
The following test case (based on #350) also crashes in a similar (maybe identical) case:

```rust
    #[test]
    fn undo_resulting_in_an_empty_buffer_does_not_crash() {
        let mut editor = MockEditor::new("<$0>");

        // Insert a tab. The command shouldn't matter here, just that the internal state changes.
        editor.command(EditCommandKind::InsertTab);
        assert_ne!("<$0>", editor.state());

        editor.command(EditCommandKind::Undo);

        assert_eq!("<$0>", editor.state());
    }
```

**Comment by bugadani** [comment]
No longer reproduces
