### ISSUE TITLE
Lapce crashes trying to bring up code completion suggestions

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#396]
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', C:\Users\bugad\.cargo\git\checkouts\xi-editor-32bce836970a2e41\5578c72\rust\rope\src\spans.rs:141:25
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\/library\core\src\panicking.rs:143
   2: core::panicking::panic
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\/library\core\src\panicking.rs:48
   3: xi_rope::spans::SpansBuilder<lapce_rpc::style::Style>::build<lapce_rpc::style::Style>
             at C:\Users\bugad\.cargo\git\checkouts\xi-editor-32bce836970a2e41\5578c72\rust\rope\src\spans.rs:141
   4: lapce_data::proxy::impl$0::handle_notification::closure$0
             at .\lapce-data\src\proxy.rs:88
   5: core::panic::unwind_safe::impl$23::call_once<tuple$<>,lapce_data::proxy::impl$0::handle_notification::closure_env$0>
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\library\core\src\panic\unwind_safe.rs:271
   6: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<lapce_data::proxy::impl$0::handle_notification::closure_env$0>,tuple$<> >
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\library\std\src\panicking.rs:492
   7: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<lapce_data::data::impl$0::load::closure_env$1,tuple$<> > >,tuple$<> >
   8: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<lapce_data::proxy::impl$0::handle_notification::closure_env$0> >
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\library\std\src\panicking.rs:456
   9: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<lapce_data::proxy::impl$0::handle_notification::closure_env$0>,tuple$<> >
             at /rustc/8f36334ca939a67cce3f37f24953ff6f2d3f3d33\library\std\src\panic.rs:137
  10: rayon_core::unwind::halt_unwinding<lapce_data::proxy::impl$0::handle_notification::closure_env$0,tuple$<> >
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\unwind.rs:17
  11: rayon_core::spawn::spawn_job::closure$0<lapce_data::proxy::impl$0::handle_notification::closure_env$0>
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\spawn\mod.rs:97
  12: rayon_core::job::impl$6::execute<rayon_core::spawn::spawn_job::closure_env$0<lapce_data::proxy::impl$0::handle_notification::closure_env$0> >
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\job.rs:167
  13: rayon_core::job::JobRef::execute
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\job.rs:59
  14: rayon_core::registry::WorkerThread::execute
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\registry.rs:749
  15: rayon_core::registry::WorkerThread::wait_until_cold
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\registry.rs:726
  16: rayon_core::registry::WorkerThread::wait_until<rayon_core::latch::CountLatch>
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\registry.rs:700
  17: rayon_core::registry::main_loop
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\registry.rs:833
  18: rayon_core::registry::ThreadBuilder::run
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\registry.rs:55
  19: rayon_core::registry::impl$2::spawn::closure$0
             at C:\Users\bugad\.cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.1\src\registry.rs:100
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bugadani** [comment]
Offending commit: https://github.com/lapce/lapce/commit/fcac68412dce618fc34defdb7f1623a7393df982

**Comment by ghishadow** [comment]
are you still getting this error ?
