### ISSUE TITLE
App failed on start

### ISSUE THREAD

**Issue by balroggg** [lapce/lapce#40]
Error:
```
Running `target/debug/lapce`
start to watch path "/home/balrog/.config/lapce/settings.toml"
palette update process stopped
buffer update process stopped
thread 'main' panicked at 'launch failed: WindowDropped', core/src/app.rs:35:10
```
OS: ArchLinux
WM: Sway
Lapce: build from source, commit a61d3b2966f4634ebad6b639692cffd0536d99c0

**Comment by balroggg** [comment]
I try some druid examples and all work fine for me.

**Comment by balroggg** [comment]
When enable Xwayland, lapce is starting, but showing empty white screen.
Log:
```
Running `target/debug/lapce`
start to watch path "/home/balrog/.config/lapce/settings.toml"
2021-12-17T21:51:50.982543Z DEBUG druid::localization: available locales [], current en-US
2021-12-17T21:51:50.982677Z DEBUG druid::localization: resolved: [en-US]
primitives buffer size 80000
plugin reload from paths
proxy mainfiest paths []
size is (3836×2110)
```

**Comment by rayanfer32** [comment]
```sh
$ ./lapce
start to watch path "C:\\Users\\rayanf\\AppData\\Roaming\\Lapce\\config\\settings.toml"
2021-12-19T17:56:38.348426Z DEBUG druid::localization: available locales [], current en-US
2021-12-19T17:56:38.348481Z DEBUG druid::localization: resolved: [en-US]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', C:\Users\runneradmin\.cargo\git\checkouts\druid-f6980810fb848923\72cc534\druid\src\window.rs:91:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
palette update process stopped
buffer update process stopped
```

**Comment by Brixus3** [comment]
I have the same issue. Could these be related?
[WGU: Failed to initialize window when libwayland is not symllinked properly](https://github.com/gfx-rs/wgpu/issues/2335)

**Comment by balroggg** [comment]
I think problem is in outdated druid crate. I try examples from lapce/druid and they have similar error on startup.
Examples from druid master is working fine( run calc example).

Druid commit 3790463cf4e724719dc0c1867afe59c3f2d22b3b

**Comment by AlexanderMisel** [comment]
```
start to watch path "C:\\Users\\xxx\\AppData\\Roaming\\Lapce\\config\\settings.toml"
2022-01-07T05:41:48.009001Z DEBUG hyper::client::connect::dns: resolving host="lapce.github.io"
2022-01-07T05:41:48.021001Z DEBUG hyper::client::connect::http: connecting to 185.199.111.153:443
2022-01-07T05:41:48.023001Z DEBUG druid::localization: available locales [], current en-US
2022-01-07T05:41:48.023001Z DEBUG druid::localization: resolved: [en-US]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', C:\Users\runneradmin\.cargo\git\checkouts\druid-f6980810fb848923\72cc534\druid\src\window.rs:91:55
stack backtrace:
   0:        0x1405ec13f - git_odb_object_data
   1:        0x14060ac8a - git_odb_object_data
   2:        0x1405e29c8 - git_odb_object_data
   3:        0x1405eed76 - git_odb_object_data
   4:        0x1405ee777 - git_odb_object_data
   5:        0x1405ef3d5 - git_odb_object_data
   6:        0x1405eefbb - git_odb_object_data
   7:        0x1405eca67 - git_odb_object_data
   8:        0x1405eef19 - git_odb_object_data
   9:        0x1407696a0 - git_proxy_options_init
  10:        0x1407697b3 - git_proxy_options_init
  11:        0x13fd119a3 - git_patch_owner
  12:        0x13fc72b18 - git_patch_owner
  13:        0x13fd73ca9 - git_patch_owner
  14:        0x13fa2c98c - <unknown>
  15:        0x13fa01006 - <unknown>
  16:        0x13fa0105c - <unknown>
  17:        0x1405ebc2b - git_odb_object_data
  18:        0x13fa01047 - <unknown>
  19:        0x14072641c - git_proxy_options_init
  20:         0x775f556d - BaseThreadInitThunk
  21:         0x7785385d - RtlUserThreadStart
palette update process stopped
buffer update process stopped
```

**Comment by fraschm1998** [comment]
Getting the same issue:
```
thread 'main' panicked at 'launch failed: WindowDropped', core/src/app.rs:50:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fredlahde** [comment]
I also got this

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/window.rs:92:55
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /rustc/1.59.0/library/core/src/result.rs:1018:23
   4: druid::window::Window<T>::new
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/window.rs:92:28
   5: druid::win_handler::Windows<T>::connect
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/win_handler.rs:121:23
   6: druid::win_handler::InnerAppState<T>::connect
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/win_handler.rs:254:9
   7: druid::win_handler::AppState<T>::connect_window
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/win_handler.rs:568:9
   8: <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::connect
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/win_handler.rs:1051:9
   9: druid::win_handler::AppState<T>::build_native_window
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/win_handler.rs:1031:17
  10: druid::app::WindowDesc<T>::build_native
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/app.rs:870:9
  11: druid::app::AppLauncher<T>::launch
             at /home/pleb/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/app.rs:278:26
  12: lapce_core::app::lanuch
             at ./core/src/app.rs:50:5
  13: lapce::main
             at ./core/src/bin/lapce.rs:6:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/1.59.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
pleb@london lapce 101 % 
```

I'm using x11 on Linux

**Comment by qrilka** [comment]
I see a similar error on Ubuntu/i3:
```
$ RUST_BACKTRACE=full LANG=c nix run nixpkgs.lapce -c lapce 
xkbcommon: ERROR: couldn't find a Compose file for locale "c" (mapped to "c")
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', /build/lapce-0.0.10-vendor.tar.gz/druid/src/window.rs:92:55
stack backtrace:
   0:     0x556008d3cba6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ceec17bcbdb5c25
   1:     0x556008d5a0ec - core::fmt::write::h58e5282d62be0ade
   2:     0x556008d27ce5 - std::io::Write::write_fmt::h66f7942ff99c956d
   3:     0x556008d29590 - std::panicking::default_hook::{{closure}}::hfa0c5e485657cde8
   4:     0x556008d2911d - std::panicking::default_hook::h58da11468c76312b
   5:     0x556008d29bdb - std::panicking::rust_panic_with_hook::h671957801cdd213a
   6:     0x556008d3d510 - std::panicking::begin_panic_handler::{{closure}}::h95e203bb3e1d7b92
   7:     0x556008d3ccd4 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e335f70cf5032de
   8:     0x556008d29682 - rust_begin_unwind
   9:     0x5560076bdfb1 - core::panicking::panic_fmt::hbdb7c8dba8be62e6
  10:     0x5560076bdd03 - core::result::unwrap_failed::h2c385645c0c07bd3
  11:     0x5560079f9aa2 - druid::window::Window<T>::new::h2c27e1c786e503e0
  12:     0x5560079011f2 - druid::win_handler::AppState<T>::build_native_window::hbb5a599b1f93d0df
  13:     0x556007713e03 - lapce_core::app::lanuch::h579ab5ef7aee6cc7
  14:     0x5560076be1e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf90fea132dd7eca
  15:     0x5560076be1f9 - std::rt::lang_start::{{closure}}::h9bf041c5425794d4
  16:     0x556008d240c1 - std::rt::lang_start_internal::h275ec2e3ce2206f1
  17:     0x5560076be1d2 - main
  18:     0x7f6d09cfe790 - __libc_start_main
  19:     0x5560076be0da - _start
  20:                0x0 - <unknown>
```

**Comment by fraschm1998** [comment]
> Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

I get the same error with the latest release

**Comment by qrilka** [comment]
The latest release works for me (but it's not in nixpkgs yet). Also tried building the sources and I get `cargo build` failing with both `develop` and `v0.1.0` but that's probably not the topic of this issue.

**Comment by bugadani** [comment]
> `cargo build` failing

You probably need to update your rust compiler. Lapce uses [a feature](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features) stabilized in 1.60

**Comment by qrilka** [comment]
I have 1.60

**Comment by bugadani** [comment]
Alright, would you please open a new issue with the compile error so we can debug this?

**Comment by qrilka** [comment]
It looks like a problem with not matching GLIBC when building deps, probably because of me using nix, I don't think it's a problem of lapce itself

**Comment by balroggg** [comment]
Close, because now the app starts.
