### ISSUE TITLE
thread 'main' panicked at 'byte index 40 is not a char boundary;

### ISSUE THREAD

**Issue by sebastian-de** [lapce/lapce#534]
I get the following panic, when building Lapce from commit 0f02410
```
thread 'main' panicked at 'byte index 40 is not a char boundary; it is inside '€' (bytes 38..41) of `    assert_eq!(flats[0].rent, "530,00 €");
`', library/core/src/str/mod.rs:127:5
stack backtrace:
   0:     0x557628a71c0d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557628a71c0d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557628a71c0d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x557628a71c0d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x557628a9af0c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x557628a696f1 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x557628a73895 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x557628a73895 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x557628a73895 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x557628a73549 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x557628a73de2 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x557628a73cc7 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  12:     0x557628a720c4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x557628a739f9 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  14:     0x5576275d04b3 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  15:     0x557628a9e767 - core::str::slice_error_fail_rt::h4a702334d6a8cbe3
  16:     0x557628a928f7 - core::ops::function::FnOnce::call_once::h82ad8e60b04d5dd8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  17:     0x557628a97aa8 - core::intrinsics::const_eval_select::h6f036bf6ff0cbd0d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/intrinsics.rs:2361:5
  18:     0x5576275d0772 - core::str::slice_error_fail::h83fedaa865594a4f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/str/mod.rs:86:9
  19:     0x557628814625 - parley::context::RangedBuilder<B,T>::build::hab653815baaaee60
  20:     0x557628825fd4 - <piet_wgpu::text_layout::WgpuTextLayoutBuilder as piet::text::TextLayoutBuilder>::build::h98d3062f20d08cfb
  21:     0x557627aa11fa - lapce_data::document::Document::get_text_layout::h233424be28639260
  22:     0x5576277dffc2 - lapce_ui::editor::LapceEditor::paint_content::h36df84660ef92462
  23:     0x55762779e58a - druid::core::WidgetPod<T,W>::paint_raw::h208b77c50dbfb9ac
  24:     0x5576277b3afc - druid::contexts::PaintCtx::with_save::h106f91f008d3bf99
  25:     0x5576277a2084 - druid::core::WidgetPod<T,W>::paint_raw::h6c55ebdcaec45065
  26:     0x5576277c54e8 - druid::contexts::PaintCtx::with_save::h9a39a8ab25759598
  27:     0x55762774ed25 - druid::core::WidgetPod<T,W>::paint::h5368358c22a5f214
  28:     0x5576277a7d72 - druid::core::WidgetPod<T,W>::paint_raw::hdd8a095e28e41e63
  29:     0x5576277c1ba8 - druid::contexts::PaintCtx::with_save::h80c042474b17ece7
  30:     0x55762774d925 - druid::core::WidgetPod<T,W>::paint::h255d9c61867240e1
  31:     0x55762763ee93 - <lapce_ui::editor::view::LapceEditorView as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint::h302ef8943221db88
  32:     0x55762779cf91 - druid::core::WidgetPod<T,W>::paint_raw::h03d79069f62a036c
  33:     0x5576277cd838 - druid::contexts::PaintCtx::with_save::hf0dd2c4f6758f1df
  34:     0x557627750925 - druid::core::WidgetPod<T,W>::paint::hb1c4121a70c93b93
  35:     0x5576276164d8 - <lapce_ui::editor::tab::LapceEditorTab as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint::h16e9784393a0b800
  36:     0x55762779cf91 - druid::core::WidgetPod<T,W>::paint_raw::h03d79069f62a036c
  37:     0x5576277cd838 - druid::contexts::PaintCtx::with_save::hf0dd2c4f6758f1df
  38:     0x557627750925 - druid::core::WidgetPod<T,W>::paint::hb1c4121a70c93b93
  39:     0x557627709ec5 - <lapce_ui::split::LapceSplitNew as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint::h69c8c93d9dd3e0b0
  40:     0x55762779cf91 - druid::core::WidgetPod<T,W>::paint_raw::h03d79069f62a036c
  41:     0x5576277cd838 - druid::contexts::PaintCtx::with_save::hf0dd2c4f6758f1df
  42:     0x557627750925 - druid::core::WidgetPod<T,W>::paint::hb1c4121a70c93b93
  43:     0x55762780250d - <lapce_ui::tab::LapceTabNew as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint::h1a3a8cb8a668cdbb
  44:     0x5576276d62e2 - <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint::hfd9ce59d34e890b4
  45:     0x5576277a4bb1 - druid::core::WidgetPod<T,W>::paint_raw::h8f2618cc71dc5ef5
  46:     0x5576277be1a8 - druid::contexts::PaintCtx::with_save::h65e71ee37ff95256
  47:     0x55762774db98 - druid::core::WidgetPod<T,W>::paint::h2c31758190922e3e
  48:     0x5576277bae70 - druid::contexts::PaintCtx::with_save::h5211027d9265dd02
  49:     0x5576276abb12 - <lapce_ui::window::LapceWindowNew as druid::widget::widget::Widget<lapce_data::data::LapceWindowData>>::paint::h2e6f95014d0a7880
  50:     0x5576276d57d2 - <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint::he9eac37eb24e0e7c
  51:     0x5576277a9991 - druid::core::WidgetPod<T,W>::paint_raw::hf373d645adc5ed33
  52:     0x5576277ae869 - druid::contexts::PaintCtx::with_child_ctx::h8094891436813a6c
  53:     0x5576275e20f6 - tracing::span::Span::in_scope::h450e247c832db5d3
  54:     0x5576276e79f1 - druid::window::Window<T>::do_paint::h8a628d98c3283f73
  55:     0x557627637386 - <druid::win_handler::DruidHandler<T> as druid_shell::window::WinHandler>::paint::h267d20ca9b70d2e6
  56:     0x5576287ed008 - druid_shell::backend::gtk::window::WindowState::with_handler_and_dont_check_the_other_borrows::hf1cadbcfd71904f9
  57:     0x557628803c91 - <O as gtk::auto::gl_area::GLAreaExt>::connect_render::render_trampoline::hf61d68b77b98c977
  58:     0x7faa13b5a413 - <unknown>
  59:     0x7faa142feb59 - g_signal_emit_valist
  60:     0x7faa142fec93 - g_signal_emit
  61:     0x7faa13c7e747 - <unknown>
  62:     0x7faa13e32604 - <unknown>
  63:     0x7faa13be3f1a - gtk_container_propagate_draw
  64:     0x7faa13be4085 - <unknown>
  65:     0x7faa13b822c9 - <unknown>
  66:     0x7faa13be8353 - <unknown>
  67:     0x7faa13beed6c - <unknown>
  68:     0x7faa13b8a920 - <unknown>
  69:     0x7faa13e32604 - <unknown>
  70:     0x7faa13be3f1a - gtk_container_propagate_draw
  71:     0x7faa13be4085 - <unknown>
  72:     0x7faa13e32604 - <unknown>
  73:     0x7faa13e36530 - <unknown>
  74:     0x7faa13cc9c33 - gtk_main_do_event
  75:     0x7faa139f6463 - <unknown>
  76:     0x7faa139fe9e9 - <unknown>
  77:     0x7faa13a038a2 - <unknown>
  78:     0x7faa13a03a98 - <unknown>
  79:     0x7faa142feb59 - g_signal_emit_valist
  80:     0x7faa142fec93 - g_signal_emit
  81:     0x7faa139fa208 - <unknown>
  82:     0x7faa139e71fb - <unknown>
  83:     0x7faa13528751 - <unknown>
  84:     0x7faa13527f4f - g_main_context_dispatch
  85:     0x7faa1357d168 - <unknown>
  86:     0x7faa135258e0 - g_main_context_iteration
  87:     0x7faa136ed96d - g_application_run
  88:     0x557628804eba - <O as gio::application::ApplicationExtManual>::run::hbbcd3b9ac6e1f4f4
  89:     0x5576287f2188 - druid_shell::backend::gtk::application::Application::run::haa646e9440c2989e
  90:     0x5576287f697e - druid_shell::application::Application::run::h24b9eb15f7ef0406
  91:     0x5576276304ed - druid::app::AppLauncher<T>::launch::h624c906acbe88385
  92:     0x5576275e6dad - lapce_ui::app::launch::h1ab609744478d02b
  93:     0x5576275d27e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7e840dbdad5a163b
  94:     0x5576275d27f9 - std::rt::lang_start::{{closure}}::h1dd284bfd60a2539
  95:     0x557628a61bce - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  96:     0x557628a61bce - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  97:     0x557628a61bce - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  98:     0x557628a61bce - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  99:     0x557628a61bce - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
 100:     0x557628a61bce - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
 101:     0x557628a61bce - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
 102:     0x557628a61bce - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
 103:     0x557628a61bce - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
 104:     0x5576275d2852 - main
 105:     0x7faa131f9590 - __libc_start_call_main
 106:     0x7faa131f9649 - __libc_start_main_alias_1
 107:     0x5576275d2715 - _start
 108:                0x0 - <unknown>
```
Additional information:
```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
system

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```

**Comment by sebastian-de** [comment]
This seems to be different from https://github.com/lapce/lapce/issues/84 as this happens when a `€` is found in the displayed rust code. Typing `€` in the command palette works fine.

**Comment by sebastian-de** [comment]
Sounds like this: https://github.com/rust-lang/rust-analyzer/issues/10219

**Comment by bugadani** [comment]
@sebastian-de can you please confirm this issue still affects you on 0.2.0?

**Comment by sebastian-de** [comment]
@bugadani  I'm currently running 6b596cb - I can't reproduce this issue anymore. Closing.
