### ISSUE TITLE
don't work fedora34

### ISSUE THREAD

**Issue by winq2008** [lapce/lapce#55]
Building
warning: `lapce-proxy` (lib) generated 80 warnings
warning: `lapce-core` (lib) generated 712 warnings

[winq@fedora release]$ ./lapce
start to watch path "/home/winq/.config/lapce/settings.toml"
2022-01-07T02:59:12.148157Z DEBUG druid::localization: available locales [], current en-US
2022-01-07T02:59:12.238086Z DEBUG druid::localization: resolved: [en-US]
2022-01-07T02:59:13.597010Z DEBUG hyper::client::connect::dns: resolving host="lapce.github.io"
2022-01-07T02:59:13.922266Z DEBUG hyper::client::connect::http: connecting to 185.199.110.153:443
2022-01-07T02:59:13.946583Z DEBUG hyper::client::connect::http: connected to 185.199.110.153:443
2022-01-07T02:59:15.394017Z DEBUG hyper::proto::h1::io: flushed 66 bytes
2022-01-07T02:59:15.750549Z DEBUG hyper::proto::h1::io: parsed 23 headers
2022-01-07T02:59:15.750644Z DEBUG hyper::proto::h1::conn: incoming body is content-length (22 bytes)
2022-01-07T02:59:15.750880Z DEBUG hyper::proto::h1::conn: incoming body completed
2022-01-07T02:59:15.751562Z DEBUG hyper::client::pool: pooling idle connection for ("https", lapce.github.io)
2022-01-07T02:59:19.203685Z DEBUG hyper::client::connect::dns: resolving host="raw.githubusercontent.com"
2022-01-07T02:59:19.740008Z DEBUG hyper::client::connect::http: connecting to 198.18.0.1:443
2022-01-07T02:59:19.740628Z DEBUG hyper::client::connect::http: connected to 198.18.0.1:443
2022-01-07T02:59:20.852694Z DEBUG hyper::proto::h1::io: flushed 99 bytes
2022-01-07T02:59:21.233730Z DEBUG hyper::proto::h1::io: parsed 23 headers
2022-01-07T02:59:21.233768Z DEBUG hyper::proto::h1::conn: incoming body is content-length (305 bytes)
2022-01-07T02:59:21.233828Z DEBUG hyper::proto::h1::conn: incoming body completed
2022-01-07T02:59:21.233904Z DEBUG hyper::client::pool: pooling idle connection for ("https", raw.githubusercontent.com)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(RequestDeviceError)', /home/winq/.cargo/git/checkouts/druid-f6980810fb848923/72cc534/druid/src/window.rs:91:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
palette update process stopped
buffer update process stopped

**Comment by VarLad** [comment]
@winq2008  Same as https://github.com/lapce/lapce/issues/53

**Comment by dzhou121** [comment]
@VarLad Can you try to build from source on the latest git ffaa111572514f772a532133879a06a4a6b94a4b

**Comment by VarLad** [comment]
@dzhou121 Building from the latest git and running with `RUST_BACKTRACE=full ./lapce`

```sh

start to watch path "/home/username/.config/lapce/settings.toml"
2022-01-08T22:17:12.957349Z DEBUG druid::localization: available locales [], current en-US
2022-01-08T22:17:12.957378Z DEBUG druid::localization: resolved: [en-US]
2022-01-08T22:17:12.959234Z DEBUG hyper::client::connect::dns: resolving host="lapce.github.io"
2022-01-08T22:17:12.961189Z DEBUG hyper::client::connect::http: connecting to [2606:50c0:8002::153]:443
2022-01-08T22:17:13.005226Z DEBUG hyper::client::connect::http: connected to [2606:50c0:8002::153]:443
2022-01-08T22:17:13.053413Z DEBUG hyper::proto::h1::io: flushed 66 bytes
primitives buffer size 80000
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x55c6bebbd0cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3264ad1edb4a78ca
   1:     0x55c6bebe540c - core::fmt::write::h85b247e856e081ad
   2:     0x55c6bebb4c05 - std::io::Write::write_fmt::he3b80a66fc2ba5d3
   3:     0x55c6bebbf110 - std::panicking::default_hook::{{closure}}::hf2bcdea8e51c0c13
   4:     0x55c6bebbecc5 - std::panicking::default_hook::h8864cfaaed08e53a
   5:     0x55c6bebbf7c4 - std::panicking::rust_panic_with_hook::hb272975096b9f3ce
   6:     0x55c6bebbf2a0 - std::panicking::begin_panic_handler::{{closure}}::hbbd6c4e11858ba52
   7:     0x55c6bebbd594 - std::sys_common::backtrace::__rust_end_short_backtrace::hdd56e8729123abc5
   8:     0x55c6bebbf209 - rust_begin_unwind
   9:     0x55c6bdd109fb - std::panicking::begin_panic_fmt::hd76138c622de6537
  10:     0x55c6be8cd019 - wgpu::backend::direct::Context::handle_error_fatal::h58edcbd218996255
  11:     0x55c6be8cd9c2 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::hef6ea1b1076e7018
  12:     0x55c6be7a3f95 - piet_wgpu::WgpuRenderer::set_size::h2793c0920e1f0dd9
  13:     0x55c6be0bbbc5 - druid::window::Window<T>::new::h15b0997b82c8bb2b
  14:     0x55c6bdf1c3cb - druid::win_handler::AppState<T>::build_native_window::hfefe1f32a60665e3
  15:     0x55c6bde46370 - druid::app::AppLauncher<T>::launch::h64288506da93acab
  16:     0x55c6bdd2a71a - lapce_core::app::lanuch::hd94a873587dc18b2
  17:     0x55c6bdd11fc3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7543f04c0a7acf68
  18:     0x55c6bdd11f99 - std::rt::lang_start::{{closure}}::hf18f11b89038e988
  19:     0x55c6bebbcdab - std::rt::lang_start_internal::hcbc5d1079a591413
  20:     0x55c6bdd12002 - main
  21:     0x7f9a6bfe4560 - __libc_start_call_main
  22:     0x7f9a6bfe460c - __libc_start_main@@GLIBC_2.34
  23:     0x55c6bdd11ec5 - _start
  24:                0x0 - <unknown>
palette update process stopped
buffer update process stopped
```

**Comment by VarLad** [comment]
Noticeably, the error message is different now

**Comment by dzhou121** [comment]
Would you mind letting me know your CPU and GPU model? Looks to do with graphics card driver or something.

**Comment by winq2008** [comment]
[winq@fedora ~]$ lscpu
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
字节序：                         Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU:                             2
在线 CPU 列表：                  0,1
每个核的线程数：                 1
每个座的核数：                   2
座：                             1
NUMA 节点：                      1
厂商 ID：                        GenuineIntel
CPU 系列：                       6
型号：                           23
型号名称：                       Intel(R) Core(TM)2 Duo CPU     T9550  @ 2.66GHz
步进：                           10
Frequency boost:                 enabled
CPU MHz：                        800.154
CPU 最大 MHz：                   2667.0000
CPU 最小 MHz：                   800.0000
BogoMIPS：                       5319.92
虚拟化：                         VT-x
L1d 缓存：                       64 KiB
L1i 缓存：                       64 KiB
L2 缓存：                        6 MiB
NUMA 节点0 CPU：                 0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm 
                                 pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est 
                                 tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm ida




[winq@fedora ~]$ lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation G96GLM [Quadro FX 770M] (rev a1)

**Comment by VarLad** [comment]
@winq2008 @dzhou121 Looks like a Wayland + NVIDIA specific problem
Works on X11

**Comment by JayDoubleu** [comment]
You could try forcing it to use xwayland with `env -u WAYLAND_DISPLAY  target/release/lapce`

**Comment by DuckDuckWhale** [comment]
Encountered the same problem, although it panics outright:

```
$ RUST_BACKTRACE=1 lapce
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Error in Surface::configure: parent device is lost', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: wgpu::backend::direct::Context::handle_error_fatal
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
   4: piet_wgpu::WgpuRenderer::set_size
   5: druid::window::Window<T>::new
   6: druid::win_handler::AppState<T>::build_native_window
   7: lapce_ui::app::lanuch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Using Ubuntu 21.10 Wayland Nivida 510 Gnome rustc 1.59.0 commit `1baaa041581e4a514033b50b91624860c5b97096`

<details>
  <summary>Full backtrace</summary>

```
RUST_BACKTRACE=full lapce
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Error in Surface::configure: parent device is lost', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x56297376580c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56297376580c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56297376580c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56297376580c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x562973791fcc - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x56297375b303 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x562973768312 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x562973768312 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x562973768312 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x562973767ef5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x562973768963 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x562973768680 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x562973765cb4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5629737683b9 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x56297219d701 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x5629734a20d9 - wgpu::backend::direct::Context::handle_error_fatal::h64093037c424dcf2
  16:     0x5629734a2c82 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::h9ba88c9b94955646
  17:     0x5629733a44e5 - piet_wgpu::WgpuRenderer::set_size::h28b8a607a924b60c
  18:     0x5629723ecb20 - druid::window::Window<T>::new::h32b78a81af526f84
  19:     0x5629722df5d6 - druid::win_handler::AppState<T>::build_native_window::h8b518b67ee54f3d6
  20:     0x5629721b0725 - lapce_ui::app::lanuch::h86a70d8c6748e59f
  21:     0x56297219dfd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6e6dcb08090847a8
  22:     0x56297219dfc9 - std::rt::lang_start::{{closure}}::hd23af614ecb9620a
  23:     0x562973764ec0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  24:     0x562973764ec0 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  25:     0x562973764ec0 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  26:     0x562973764ec0 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  27:     0x562973764ec0 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  28:     0x562973764ec0 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  29:     0x562973764ec0 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  30:     0x562973764ec0 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  31:     0x562973764ec0 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  32:     0x56297219df92 - main
  33:     0x7f51fdb81fd0 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  34:     0x7f51fdb8207d - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:409:3
  35:     0x56297219de95 - _start
  36:                0x0 - <unknown>
```
</summary>

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by DuckDuckWhale** [comment]
```
$ lapce
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a
```

**Comment by DuckDuckWhale** [comment]
I no longer have this problem on 2.0 and Ubuntu 22.04 (except for working around an egl-wayland bug).
