### ISSUE TITLE
thread 'main' panicked at 'Failed to initialize any backend! 

### ISSUE THREAD

**Issue by whitis** [lapce/lapce#591]
lapce goes splat on startup  on Ubuntu 18.04 in wayland "X11" session.

```
$ sudo snap install lapce
$ lapce
[splat]
$ RUST_BACKTRACE=1 lapce
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: winit::platform_impl::platform::EventLoop<T>::new
   3: druid::app::AppLauncher<T>::launch
   4: lapce_ui::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

$ RUST_BACKTRACE=1 lapce
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: winit::platform_impl::platform::EventLoop<T>::new
   3: druid::app::AppLauncher<T>::launch
   4: lapce_ui::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

$ uname -a; lsb_release -a
Linux cervantes 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

$ ldd /snap/bin/lapce
	linux-vdso.so.1 (0x00007fffa178b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb78a4ec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb78a0fb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb78c0ab000)
$ ps axlww | egrep "X11|xserver|wayland|composit"
4   121  6701  5357  20   0 189364  3724 -      Ssl+ tty1       0:00 /usr/lib/gdm3/gdm-wayland-session gnome-session --autostart /usr/share/gdm/greeter/autostart
0   121  6898  6775  20   0 831472  5244 -      Sl+  tty1       0:02 /usr/bin/Xwayland :1024 -rootless -terminate -accessx -core -listen 4 -listen 5 -displayfd 6
1  1000 25904 25880  20   0 1423080 2724 futex_ Sl   pts/5      0:03 /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess --type=renderer --disable-accelerated-video-decode --disable-gpu-memory-buffer-video-frames --disable-shared-workers --enable-threaded-compositing --use-gl=desktop --disable-webrtc-hw-encoding --primordial-pipe-token=FF0651AED94DDD04337C0F6CD03D302A --lang=en-US --enable-pinch --num-raster-threads=3 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;

$ printenv | fgrep -i display
DISPLAY=:0
$ WAYLAND_DISPLAY=wayland=0 lapce
[splat]
$ neofetch
            .-/+oossssoo+/-.               whitis@cervantes 
        `:+ssssssssssssssssss+:`           ---------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.6 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.4.0-109-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 32 days, 18 hours, 24 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 7973 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 4.4.20 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 3840x2160 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 3.28.4 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Ambiance [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Ubuntu-mono-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: AMD Phenom II X6 1090T (6) @ 3. 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: AMD Radeon HD 6950 
    .ossssssssssssssssssdMMMNysssso.       Memory: 7541MiB / 16007MiB 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-. 

$ printenv | fgrep -i SESSION
GNOME_SHELL_SESSION_MODE=ubuntu
XDG_SESSION_ID=60
DESKTOP_SESSION=ubuntu
XDG_SESSION_TYPE=x11
XDG_SESSION_DESKTOP=ubuntu
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SESSION_MANAGER=local/cervantes:@/tmp/.ICE-unix/11598,unix/cervantes:/tmp/.ICE-unix/11598

 libraries for X C Binding -- cursor
$ sudo apt-get install libxcursor1
[sudo] password for whitis: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxcursor1 is already the newest version (1:1.1.15-1).
[...]

$ ls -lgF /usr/lib/x86_64-linux-gnu/libXcursor*
-rw-r--r-- 1 root 53994 Dec 19  2017 /usr/lib/x86_64-linux-gnu/libXcursor.a
lrwxrwxrwx 1 root    19 Dec 19  2017 /usr/lib/x86_64-linux-gnu/libXcursor.so -> libXcursor.so.1.0.2
lrwxrwxrwx 1 root    19 May  2  2019 /usr/lib/x86_64-linux-gnu/libXcursor.so.1 -> libXcursor.so.1.0.2
-rw-r--r-- 1 root 39240 Dec 19  2017 /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2

$ sudo ldconfig

$ lapce
[splat]

$ sudo snap refresh --beta lapce

$ lapce
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by yonip23** [comment]
Hey there!
I wanted to try out lapce and also failed on a similar error:
```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)" })', /root/.cargo/git/checkouts/winit-58efae9df3f5264a/59eb01c/src/platform_impl/linux/mod.rs:626:9
```

This is my setup:
![image](https://user-images.githubusercontent.com/67855609/173203116-2eae474c-bd3a-418c-a391-06d3dfa7969a.png)

And also, running `sudo apt install libxcursor1` didn't help

**Comment by yonip23** [comment]
update: building from source did work 🙂

**Comment by bugadani** [comment]
I'm suspecting this issue affects only very old versions. If you experience this on 0.2.0, please reopen. Thank you!
