### ISSUE TITLE
Program crashing when going editing a section with non-standard chars.

### ISSUE THREAD

**Issue by Laar3** [lapce/lapce#618]
When i am editing some code in lapce and i edit a part which has a nerdfont the program crashes. this is a picture of what the code appears as in lapse and vscode,
![image](https://user-images.githubusercontent.com/77225642/174020046-c65789f7-2317-4c40-bd05-5ecfe55b385c.png)
![image](https://user-images.githubusercontent.com/77225642/174020261-22a2b165-c20f-4143-8c06-ea52f76f1610.png)

 if i try to remove a character in the line. this does not seem to happen when adding characters. This also happens in other parts of the code (which also have non-standard characters. 
 
 This is the error log when run with RUST_BACKTRACE=1. 
[error.log](https://github.com/lapce/lapce/files/8916763/error.log)
Thanks for making this project, other than this issue i'm loving it.

**Comment by crystal-growth** [comment]
Lapce crashes on files containing unicode subscript/superscript characters.
For example,after opening [uom](https://github.com/iliekturtles/uom) crate, lapce crashes with following message

thread 'main' panicked at 'byte index 62 is not a char boundary; it is inside '⁻' (bytes 60..63) of `//! Available energy (base unit joule per kilogram, m² · s⁻²).
`', library/core/src/str/mod.rs:127:5

os: Linux
lapce installed from flatpak

**Comment by MaMrEzO** [comment]
And the same, Linux, Release 0.3.1, 

```
thread 'main' panicked at /github/home/.cargo/git/checkouts/cosmic-text-fff8c4a78b1e732f/f7a2070/src/shape.rs:104:17:
begin <= end (4 <= 2) when slicing `بلة`
stack backtrace:
   0:     0x55fcc49b72cf - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fcc49b72cf - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fcc49b72cf - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55fcc49b72cf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fcc344768c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55fcc344768c - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55fcc49809fd - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55fcc49b996e - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fcc49b996e - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fcc49b9553 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55fcc49ba519 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55fcc49ba519 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x55fcc49ba04c - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x55fcc49b9fa6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55fcc49b9f91 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x55fcc326ecb4 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x55fcc344ffc1 - core::str::slice_error_fail_rt::h69806d6a2cda9027
  17:     0x55fcc326f406 - core::str::slice_error_fail::h605af33f8cd178b6
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/str/mod.rs:87:9
  18:     0x55fcc3472fb4 - cosmic_text::shape::shape_fallback::h2b2667ae04a1f304
  19:     0x55fcc347149e - cosmic_text::shape::shape_run::hd109ad0fe5ff5e16
  20:     0x55fcc346fb5e - cosmic_text::shape::ShapeWord::new::hc673cd337fa9a2da
  21:     0x55fcc346ee80 - cosmic_text::shape::ShapeSpan::new::h2246e3cd07a735e8
  22:     0x55fcc3463da3 - cosmic_text::buffer_line::TextLayoutLine::layout::h19821fe909a45848
  23:     0x55fcc34607a6 - cosmic_text::buffer::TextLayout::shape_until::h47a6915dcaf6abe0
  24:     0x55fcc346013c - cosmic_text::buffer::TextLayout::set_text::h62e24f6d61f9feb2
  25:     0x55fcc3a25a66 - lapce_app::doc::Document::get_text_layout::h62d7618b3445fcf7
  26:     0x55fcc3a23548 - lapce_app::editor::view_data::EditorViewData::get_text_layout::h72f776942ea9b881
  27:     0x55fcc3b554b8 - <lapce_app::editor::view::EditorView as floem::view::View>::layout::h11974eb646ce906b
  28:     0x55fcc3b14f38 - floem::view::View::layout::he2d20c8917604af8
  29:     0x55fcc3ae0df8 - floem::view::View::layout::h5eb06e7c8426641c
  30:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  31:     0x55fcc3ae0df8 - floem::view::View::layout::h5eb06e7c8426641c
  32:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  33:     0x55fcc3ae0df8 - floem::view::View::layout::h5eb06e7c8426641c
  34:     0x55fcc3c1f58f - floem::view::View::layout::h5411637965b88720
  35:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  36:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  37:     0x55fcc3ae0df8 - floem::view::View::layout::h5eb06e7c8426641c
  38:     0x55fcc3b7937f - floem::view::View::layout::h0df3d7cd58870daa
  39:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  40:     0x55fcc3ae0df8 - floem::view::View::layout::h5eb06e7c8426641c
  41:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  42:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  43:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  44:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  45:     0x55fcc3ade5f2 - floem::view::View::layout::h0d7b5fd0d8d8df01
  46:     0x55fcc3918200 - floem::view::View::layout::hfd6f6e35277f9e32
  47:     0x55fcc36e9de8 - floem::view::View::layout::h5041274c21ddcf70
  48:     0x55fcc36da986 - floem::view::View::layout::h2f89d1419cd64a33
  49:     0x55fcc3708379 - floem::view::View::layout::h9b913f88b7929db2
  50:     0x55fcc36920b7 - floem::window_handle::WindowHandle::process_update_no_paint::h90439520915c8e75
  51:     0x55fcc366705f - floem::app_handle::ApplicationHandle::idle::h83705ae038299656
  52:     0x55fcc3667959 - floem::app::Application::run::{{closure}}::h20be85bb26c520c0
  53:     0x55fcc366d2a0 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::poll_events_with_timeout::hce92b16cf28bd370
  54:     0x55fcc4193ff4 - lapce_app::app::launch::h46fc00ea5799c667
  55:     0x55fcc3356623 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbd23bd1a12cd408d
  56:     0x55fcc3356a95 - main
  57:     0x7ffbdab22cd0 - <unknown>
  58:     0x7ffbdab22d8a - __libc_start_main
  59:     0x55fcc335610a - _start
  60:                0x0 - <unknown>
```
