### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', core\src\split.rs:818:72

### ISSUE THREAD

**Issue by minecrosters** [lapce/lapce#66]
this happened when i clicked the search icon then the terminal icon

logs
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', core\src\split.rs:818:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
palette update process stopped
buffer update process stopped
error: process didn't exit successfully: `target\release\lapce.exe` (exit code: 101)
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence

**Comment by bugadani** [comment]
Thanks for reporting! I think this issue has been fixed (though I don't know when), so I'm going to close this issue. If you are still experiencing this crash, please feel free reopen.
