### ISSUE TITLE
Bug: Lapce crashes when using `dG` vim command

### ISSUE THREAD

**Issue by StHagel** [lapce/lapce#676]
When using the vim shortcuts for lapce, the editor crashes when using the `dG` command at the first line of a file with the following error message:
```thread 'main' panicked at 'line number 2 beyond last line 1', /home/sthagel/.cargo/git/checkouts/xi-editor-32bce836970a2e41/5578c72/rust/rope/src/rope.rs:481:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'rust-analyzer server thread' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', crates/rust-analyzer/src/global_state.rs:305:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: rust_analyzer::global_state::GlobalState::send
   4: rust_analyzer::lsp_utils::<impl rust_analyzer::global_state::GlobalState>::report_progress
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   6: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   7: rust_analyzer::main_loop::main_loop
   8: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.```

**Comment by bugadani** [comment]
I can't reproduce this. Can we consider the issue fixed?

**Comment by StHagel** [comment]
In the newest versions I cannot reproduce this either, so it can probably be closed.

**Comment by bugadani** [comment]
Please reopen if you experience this again :)
