### ISSUE TITLE
Crashing on file save

### ISSUE THREAD

**Issue by jath03** [lapce/lapce#713]
Hi, this looks like the beginnings of a really nice editor.  However, when testing with multiple windows open, I noticed that saving a file was pretty consistently causing a crash.  I tested this on both 0.1.2 and the latest git version.  

System:
Arch Linux
Kernel 5.18.7
KDE Plasma

```
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/home/jack/projects/<non-rust project>/")]
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/home/jack/projects/<non-rust project>/")]
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lapce-data/src/data.rs:1930:44
stack backtrace:
   0:     0x55971fe87dfd - <unknown>
   1:     0x55971feb19fc - <unknown>
   2:     0x55971fe80181 - <unknown>
   3:     0x55971fe89775 - <unknown>
   4:     0x55971fe893e9 - <unknown>
   5:     0x55971fe89d48 - <unknown>
   6:     0x55971fe89bb9 - <unknown>
   7:     0x55971fe882b4 - <unknown>
   8:     0x55971fe89929 - <unknown>
   9:     0x55971e76d0b3 - <unknown>
  10:     0x55971e76cf7d - <unknown>
  11:     0x55971ebe2971 - <unknown>
  12:     0x55971ebe2a5c - <unknown>
  13:     0x55971e7c2248 - <unknown>
  14:     0x55971e7c4927 - <unknown>
  15:     0x55971e7cae9a - <unknown>
  16:     0x55971e860a7b - <unknown>
  17:     0x55971e917fba - <unknown>
  18:     0x55971e8b6425 - <unknown>
  19:     0x55971e7ccc40 - <unknown>
  20:     0x55971e8614eb - <unknown>
  21:     0x55971e920891 - <unknown>
  22:     0x55971e782826 - <unknown>
  23:     0x55971e7f2262 - <unknown>
  24:     0x55971e7ec252 - <unknown>
  25:     0x55971e7fe871 - <unknown>
  26:     0x55971fc0720c - <unknown>
  27:     0x55971fc1907e - <unknown>
  28:     0x7f3a91641c6b - g_main_context_dispatch
  29:     0x7f3a91698001 - <unknown>
  30:     0x7f3a9163f392 - g_main_context_iteration
  31:     0x7f3a917fe19e - g_application_run
  32:     0x55971fc1bd37 - <unknown>
  33:     0x55971fc0dd0e - <unknown>
  34:     0x55971e81f706 - <unknown>
  35:     0x55971e788ba4 - <unknown>
  36:     0x55971e76f0f3 - <unknown>
  37:     0x55971e76f0c9 - <unknown>
  38:     0x55971fe785be - <unknown>
  39:     0x55971e76f132 - <unknown>
  40:     0x7f3a91303290 - <unknown>
  41:     0x7f3a9130334a - __libc_start_main
  42:     0x55971e76efe5 - <unknown>
  43:                0x0 - <unknown>
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
```

**Comment by jath03** [comment]
I've been learning the code base a bit, trying to figure this one out myself.  Looks like the `OpenFile` command is being called twice and is maybe being handled by the wrong window?

```
[2022-07-01][11:16:42][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:16:42][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/home/jack/projects/qmk_firmware/")]
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace
[2022-07-01][11:16:49][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:16:49][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/home/jack/projects/openrgb-python/")]
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace
[2022-07-01][11:16:54][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:16:54][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
Opening file "/home/jack/projects/openrgb-python/openrgb/network.py"
Inserting "/home/jack/projects/openrgb-python/openrgb/network.py" into open_docs
[2022-07-01][11:17:10][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:10][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
Checking if open_docs contains "/home/jack/projects/openrgb-python/openrgb/network.py"
open_docs: "/home/jack/projects/openrgb-python/openrgb/network.py" 
Checking if open_docs contains "/home/jack/projects/openrgb-python/openrgb/network.py"
open_docs: "/home/jack/projects/openrgb-python/openrgb/network.py" 
[2022-07-01][11:17:30][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:30][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:30][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:30][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("/home/jack/projects/qmk_firmware/")]
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to discover workspace
[2022-07-01][11:17:48][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:48][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:48][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
[2022-07-01][11:17:48][lapce_data::keypress][ERROR] Failed to load from "/home/jack/.config/lapce/debug-keymaps.toml": no keymaps
Opening file "/home/jack/projects/qmk_firmware/.gitignore"
Inserting "/home/jack/projects/qmk_firmware/.gitignore" into open_docs
Opening file "/home/jack/projects/qmk_firmware/.gitignore"
Checking if open_docs contains "/home/jack/projects/qmk_firmware/.gitignore"
open_docs: "/home/jack/projects/openrgb-python/openrgb/network.py" 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lapce-data/src/data.rs:1936:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
[ERROR rust_analyzer] Unexpected error: expected initialize request, got error: receiving on an empty and disconnected channel
expected initialize request, got error: receiving on an empty and disconnected channel
[ERROR rust_analyzer] Unexpected error: client exited without proper shutdown sequence
client exited without proper shutdown sequence
```

**Comment by jath03** [comment]
I can no longer reproduce this issue, so I'm going to close it under the assumption that it was fixed unintentionally.
