### ISSUE TITLE
Can't run on NVIDIA nouveau drive 

### ISSUE THREAD

**Issue by Mofiqul** [lapce/lapce#75]
Can not run with NVIDIA nouveau drive on Gnome with Wayland and X11 

```
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x55ab7407225c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ab7407225c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ab7407225c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55ab7407225c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55ab7409e48c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x55ab74068843 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x55ab74074d62 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55ab74074d62 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55ab74074d62 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x55ab74074945 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x55ab740753b3 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x55ab740750d0 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x55ab74072704 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55ab74074e09 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x55ab72ac5ca1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x55ab73da4f99 - wgpu::backend::direct::Context::handle_error_fatal::h3c1660e9ad1853b9
  16:     0x55ab73da59b2 - <wgpu::backend::direct::Context as wgpu::Context>::surface_configure::h0b1ac43dd38f98d7
  17:     0x55ab73caeab5 - piet_wgpu::WgpuRenderer::set_size::h159106f8e93d4d97
  18:     0x55ab72d6ec00 - druid::window::Window<T>::new::ha47da59c715d62da
  19:     0x55ab72c44d0f - druid::win_handler::AppState<T>::build_native_window::h7b0ff73a5d36993e
  20:     0x55ab72ef2f25 - druid::app::AppLauncher<T>::launch::h310784752f964e0c
  21:     0x55ab72acff03 - lapce_core::app::lanuch::h4eb28edc53c5bc48
  22:     0x55ab72ac6543 - std::sys_common::backtrace::__rust_begin_short_backtrace::he6f3289d5f988fd2
  23:     0x55ab72ac6579 - std::rt::lang_start::{{closure}}::h47eb7e54fd2f2175
  24:     0x55ab74071910 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  25:     0x55ab74071910 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  26:     0x55ab74071910 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27:     0x55ab74071910 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28:     0x55ab74071910 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  29:     0x55ab74071910 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  30:     0x55ab74071910 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  31:     0x55ab74071910 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  32:     0x55ab74071910 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  33:     0x55ab72ac6532 - main
  34:     0x7f69a4a84560 - __libc_start_call_main
  35:     0x7f69a4a8460c - __libc_start_main_alias_1
  36:     0x55ab72ac643e - _start
  37:                0x0 - <unknown>

```

**Comment by oleid** [comment]
Does nouveau have a Vulkan driver these days?
If so, do the wgpu examples work for you?

https://github.com/gfx-rs/wgpu

**Comment by RomanMunar** [comment]
Hey I found a solution just now. Don't know what's causing the issue. I'm not a Rust dev/user. Just wanted to try lapce out.  
1. Use this script to install vulkan from https://packages.lunarg.com
```
wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.204-focal.list https://packages.lunarg.com/vulkan/1.3.204/lunarg-vulkan-1.3.204-focal.list
sudo apt update
sudo apt install vulkan-sdk
```
2. Install libgtk-3-dev. A requirement on linux for [Druid(UI used by lapce)](https://github.com/linebender/druid) 
`sudo apt-get install libgtk-3-dev`

> ### **I'm not sure If installing vulkan is necessary here. I just happened to install it before reading [druid's linux requirements](https://github.com/linebender/druid)**. So try installing libgtk-3-dev only first.

Similar/Related issues on wgpu:
https://github.com/lapce/lapce/issues/53
https://github.com/lapce/lapce/issues/55
