### ISSUE TITLE
Successful compiling, but window don't start

### ISSUE THREAD

**Issue by peterwilfride** [lapce/lapce#93]
OS: EndevourOS
Session type: X11
Cargo version: 1.58

Problem: I follow the steps in README.md for compiling, but I wasn't able to start the window

```shell
❯ ./target/release/lapce 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(RequestDeviceError)', /home/neuromancer/.cargo/git/checkouts/druid-f6980810fb848923/ce62050/druid/src/window.rs:92:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: druid::window::Window<T>::new
   4: druid::win_handler::AppState<T>::build_native_window
   5: lapce_core::app::lanuch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MadScientist2854** [comment]
experienced the same error on Pop!_OS running Ubuntu 20.04 with X11. it seems to be occuring on initialization of `WgpuRenderer` from the piet fork, and looking at the docs that's probably because the adapter features requested don't function on our devices. the other potential culprit, the device descriptor, is just set to default. i haven't used any of these libraries before so i don't know what options to even try to change, but i will try my best in the morning.

**Comment by bugadani** [comment]
Could you please try [the latest release](https://github.com/lapce/lapce/releases/tag/v0.1.0) ?

**Comment by panekj** [comment]
Should be fixed after switch to OpenGL
